### ISSUE TITLE
Pre-release 1.76.5: Startup connection file could not be loaded 

### ISSUE THREAD

**Issue by alexmartinio** [mRemoteNG/mRemoteNG#1061]
For version 1.76.5.31227 (portable zip) and 1.76.5.31190 (msi installer) on starting mRemoteNG the error the startup connection file could not be loaded.

## Expected Behavior
mRemoteNG starts like previous version

## Current Behavior

```
Could not load startup file.
The startup connection file could not be loaded.
C:\Users\<snipped path>\confCons.xml
Object reference not set to an instance of an object
In order to prevent data loss, mRemoteNG will now exit.
```
Log file: [mRemoteNG.log](https://github.com/mRemoteNG/mRemoteNG/files/2257062/mRemoteNG.log)
confCons.xml: [confCons.xml.txt](https://github.com/mRemoteNG/mRemoteNG/files/2257097/confCons.xml.txt)

## Possible Solution

Workaround - revert to previous version.
1.76.4.16229 works. 

## Steps to Reproduce (for bugs)

1. Uninstall mRemoteNG
2. Remove %AppData%\mRemoteNG
3. Install msi or download and extract portable version
4. Start mRemoteNG.exe - get error.

## Context

N/A 

## Your Environment

* Version used: 1.76.5.31227 (portable zip) and 1.76.5.31190 (msi installer) 
* Operating System and version (e.g. Windows 10 1709 x64): Windows 10 Pro 1803 x64

(my first issue report! Hope this helps)

**Comment by sparerd** [comment]
Thanks for the report, @alexmartinio! So far not able to replicate. I think this log entry might be what caused the crash though:
```
Object reference not set to an instance of an object.
   at mRemoteNG.Config.Putty.PuttySessionsRegistryProvider.GetSession(String sessionName)
   at mRemoteNG.Config.Putty.AbstractPuttySessionsProvider.GetSessions()
   at mRemoteNG.Config.Putty.PuttySessionsManager.AddSessionsFromProvider(AbstractPuttySessionsProvider provider)
   at mRemoteNG.Config.Putty.PuttySessionsManager.AddSessions()
   at mRemoteNG.Connection.ConnectionsService.LoadConnections(Boolean useDatabase, Boolean import, String connectionFileName)
   at mRemoteNG.App.Runtime.LoadConnections(Boolean withDialog)
```

I've added an extra safety check in that section of code that should help. I need to do a quick release for an unrelated issue today, so look for 1.76.6 soon.

**Comment by rhardy613** [comment]
On Win 10 1.76.6.14594 doesn't fix #1061.
Steps to reproduce: Complete delete directory contents and sub dirs of C:\Users\username\AppData\Roaming\mRemoteNG
Attempt to launch mRemoteNG and tell it to create a new config. It will be only does half the job. You can't create any connections in the new empty file. Eventually this gets logged:
2018-08-04 17:29:40,976 [1] ERROR - Couldn't create new connections file!
Object reference not set to an instance of an object.
2018-08-04 17:29:41,021 [1] WARN  - XmingPortablePuttySessions.Watcher.StartWatching() failed: 'sessions' does not exist.
After you close the program subsequent launches crash the program.

**Comment by sparerd** [comment]
I made a few more changes in v1.76.7 that may resolve this. @alexmartinio and @rhardy613, can you both retest with the new version?

**Comment by alexmartinio** [comment]
Apologies for the delay, I've just tried v1.76.8.17254 portable and it seems to start fine now. The log however does have a few odd messages - I might open a new report if it's not already listed. 
```
Invalid cast from 'System.String' to 'mRemoteNG.Connection.Protocol.ProtocolType'.
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at System.String.System.IConvertible.ToType(Type type, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType)
   at mRemoteNG.Connection.DefaultConnectionInfo.LoadFrom[TSource](TSource sourceInstance, Func`2 propertyNameMutator)
```

**Comment by sparerd** [comment]
Good to hear @alexmartinio. Yea I've seen them too - still need to look into it. No need to open a ticket. Thanks for checking!

**Comment by kmscode** [comment]
Fixed Invalid casts in commit 793095900b3721efba2c0010087a45b022291819 via #1092

**Comment by CameronPHAGGAR** [comment]
In the same locate as the 'confCons.xml' file you will have the backup files. These backups are taken frequently and will more than likely have backed up a version of mRemote 5 minutes prior to this issue occuring. Simply delete the 'confCons.xml' file and rename the latest backup and convert to xml. When you next load mRemote it will start using that backup file and it will continue to work as normal

**Comment by ydbank** [comment]
还是很多问题，卡死，无响应，
2019-11-20 13:26:28,467 [1] INFO  - mRemoteNG 1.76.20.24669 便携版本 starting.
2019-11-20 13:26:28,476 [1] INFO  - Command Line: C:\Program Files (x86)\mRemoteNG-Portable-1.76.20.24669\mRemoteNG.exe
2019-11-20 13:26:29,707 [1] INFO  - Microsoft Windows 7 旗舰版 Service Pack 1 64-bit
2019-11-20 13:26:29,707 [1] INFO  - Microsoft .NET CLR 4.0.30319.42000
2019-11-20 13:26:29,708 [1] INFO  - System Culture: zh-CN/中文(中华人民共和国)
2019-11-20 13:26:29,710 [1] INFO  - Checking FIPS Policy...
2019-11-20 13:26:29,713 [1] INFO  - Checking Lenovo AutoScroll Utility...
2019-11-20 13:26:29,816 [1] WARN  - Loading External Apps failed: Could not FIND file!
2019-11-20 13:26:30,401 [1] WARN  - XmingPortablePuttySessions.Watcher.StartWatching() failed: 'sessions' does not exist.
2019-11-20 13:26:40,603 [1] INFO  - 切换到远程桌面客户端 6.3.9600 控制台会话。
2019-11-20 13:26:40,606 [1] INFO  - 支持远程桌面网关。
2019-11-20 13:26:41,718 [6] INFO  - Saving connections...
2019-11-20 13:26:41,792 [6] INFO  - Successfully saved connections
2019-11-20 13:26:51,149 [1] INFO  - 切换到远程桌面客户端 6.3.9600 控制台会话。
2019-11-20 13:26:51,151 [1] INFO  - 支持远程桌面网关。
2019-11-20 13:26:51,196 [10] INFO  - Saving connections...
2019-11-20 13:26:51,216 [10] INFO  - Successfully saved connections
