### ISSUE TITLE
Invalid Cast Exceptions loading default connectioninfo

### ISSUE THREAD

**Issue by kmscode** [mRemoteNG/mRemoteNG#1092]
As reported i #1061

## Expected Behavior
No exceptions

## Current Behavior
Invalid Cast Exceptions:

```
2018-08-28 08:37:38,065 [1] ERROR - Error loading default connectioninfo property Protocol
Invalid cast from 'System.String' to 'mRemoteNG.Connection.Protocol.ProtocolType'.
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at System.String.System.IConvertible.ToType(Type type, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType)
   at mRemoteNG.Connection.DefaultConnectionInfo.LoadFrom[TSource](TSource sourceInstance, Func`2 propertyNameMutator)
2018-08-28 08:37:38,065 [1] ERROR - Error loading default connectioninfo property ICAEncryptionStrength
Invalid cast from 'System.String' to 'mRemoteNG.Connection.Protocol.ICA.IcaProtocol+EncryptionStrength'.
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at System.String.System.IConvertible.ToType(Type type, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType)
   at mRemoteNG.Connection.DefaultConnectionInfo.LoadFrom[TSource](TSource sourceInstance, Func`2 propertyNameMutator)
2018-08-28 08:37:38,065 [1] ERROR - Error loading default connectioninfo property RDPAuthenticationLevel
Invalid cast from 'System.String' to 'mRemoteNG.Connection.Protocol.RDP.RdpProtocol+AuthenticationLevel'.
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at System.String.System.IConvertible.ToType(Type type, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType)
   at mRemoteNG.Connection.DefaultConnectionInfo.LoadFrom[TSource](TSource sourceInstance, Func`2 propertyNameMutator)
2018-08-28 08:37:38,065 [1] ERROR - Error loading default connectioninfo property RenderingEngine
Invalid cast from 'System.String' to 'mRemoteNG.Connection.Protocol.Http.HTTPBase+RenderingEngine'.
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at System.String.System.IConvertible.ToType(Type type, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType)
   at mRemoteNG.Connection.DefaultConnectionInfo.LoadFrom[TSource](TSource sourceInstance, Func`2 propertyNameMutator)
2018-08-28 08:37:38,065 [1] ERROR - Error loading default connectioninfo property RDGatewayUsageMethod
Invalid cast from 'System.String' to 'mRemoteNG.Connection.Protocol.RDP.RdpProtocol+RDGatewayUsageMethod'.
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at System.String.System.IConvertible.ToType(Type type, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType)
   at mRemoteNG.Connection.DefaultConnectionInfo.LoadFrom[TSource](TSource sourceInstance, Func`2 propertyNameMutator)
2018-08-28 08:37:38,065 [1] ERROR - Error loading default connectioninfo property RDGatewayUseConnectionCredentials
Invalid cast from 'System.String' to 'mRemoteNG.Connection.Protocol.RDP.RdpProtocol+RDGatewayUseConnectionCredentials'.
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at System.String.System.IConvertible.ToType(Type type, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType)
   at mRemoteNG.Connection.DefaultConnectionInfo.LoadFrom[TSource](TSource sourceInstance, Func`2 propertyNameMutator)
2018-08-28 08:37:38,065 [1] ERROR - Error loading default connectioninfo property Resolution
Invalid cast from 'System.String' to 'mRemoteNG.Connection.Protocol.RDP.RdpProtocol+RDPResolutions'.
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at System.String.System.IConvertible.ToType(Type type, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType)
   at mRemoteNG.Connection.DefaultConnectionInfo.LoadFrom[TSource](TSource sourceInstance, Func`2 propertyNameMutator)
2018-08-28 08:37:38,081 [1] ERROR - Error loading default connectioninfo property Colors
Invalid cast from 'System.String' to 'mRemoteNG.Connection.Protocol.RDP.RdpProtocol+RDPColors'.
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at System.String.System.IConvertible.ToType(Type type, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType)
   at mRemoteNG.Connection.DefaultConnectionInfo.LoadFrom[TSource](TSource sourceInstance, Func`2 propertyNameMutator)
2018-08-28 08:37:38,081 [1] ERROR - Error loading default connectioninfo property RedirectSound
Invalid cast from 'System.String' to 'mRemoteNG.Connection.Protocol.RDP.RdpProtocol+RDPSounds'.
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at System.String.System.IConvertible.ToType(Type type, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType)
   at mRemoteNG.Connection.DefaultConnectionInfo.LoadFrom[TSource](TSource sourceInstance, Func`2 propertyNameMutator)
2018-08-28 08:37:38,081 [1] ERROR - Error loading default connectioninfo property SoundQuality
Invalid cast from 'System.String' to 'mRemoteNG.Connection.Protocol.RDP.RdpProtocol+RDPSoundQuality'.
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at System.String.System.IConvertible.ToType(Type type, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType)
   at mRemoteNG.Connection.DefaultConnectionInfo.LoadFrom[TSource](TSource sourceInstance, Func`2 propertyNameMutator)
2018-08-28 08:37:38,081 [1] ERROR - Error loading default connectioninfo property VNCCompression
Invalid cast from 'System.String' to 'mRemoteNG.Connection.Protocol.VNC.ProtocolVNC+Compression'.
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at System.String.System.IConvertible.ToType(Type type, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType)
   at mRemoteNG.Connection.DefaultConnectionInfo.LoadFrom[TSource](TSource sourceInstance, Func`2 propertyNameMutator)
2018-08-28 08:37:38,081 [1] ERROR - Error loading default connectioninfo property VNCEncoding
Invalid cast from 'System.String' to 'mRemoteNG.Connection.Protocol.VNC.ProtocolVNC+Encoding'.
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at System.String.System.IConvertible.ToType(Type type, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType)
   at mRemoteNG.Connection.DefaultConnectionInfo.LoadFrom[TSource](TSource sourceInstance, Func`2 propertyNameMutator)
2018-08-28 08:37:38,081 [1] ERROR - Error loading default connectioninfo property VNCAuthMode
Invalid cast from 'System.String' to 'mRemoteNG.Connection.Protocol.VNC.ProtocolVNC+AuthMode'.
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at System.String.System.IConvertible.ToType(Type type, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType)
   at mRemoteNG.Connection.DefaultConnectionInfo.LoadFrom[TSource](TSource sourceInstance, Func`2 propertyNameMutator)
2018-08-28 08:37:38,081 [1] ERROR - Error loading default connectioninfo property VNCProxyType
Invalid cast from 'System.String' to 'mRemoteNG.Connection.Protocol.VNC.ProtocolVNC+ProxyType'.
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at System.String.System.IConvertible.ToType(Type type, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType)
   at mRemoteNG.Connection.DefaultConnectionInfo.LoadFrom[TSource](TSource sourceInstance, Func`2 propertyNameMutator)
2018-08-28 08:37:38,081 [1] ERROR - Error loading default connectioninfo property VNCColors
Invalid cast from 'System.String' to 'mRemoteNG.Connection.Protocol.VNC.ProtocolVNC+Colors'.
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at System.String.System.IConvertible.ToType(Type type, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType)
   at mRemoteNG.Connection.DefaultConnectionInfo.LoadFrom[TSource](TSource sourceInstance, Func`2 propertyNameMutator)
2018-08-28 08:37:38,081 [1] ERROR - Error loading default connectioninfo property VNCSmartSizeMode
Invalid cast from 'System.String' to 'mRemoteNG.Connection.Protocol.VNC.ProtocolVNC+SmartSizeMode'.
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at System.String.System.IConvertible.ToType(Type type, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType)
   at mRemoteNG.Connection.DefaultConnectionInfo.LoadFrom[TSource](TSource sourceInstance, Func`2 propertyNameMutator)
```

## Possible Solution

Looks like the problem properties are all enums. Parse the enums properly.

Also reference commit: 35582a5e6aee078d3920e5a5c702de79a1df35ec

Previously there were checks to see if the properties could be converted.  

## Steps to Reproduce (for bugs)

1. Open mRemoteNG
2. Open mRemoteNG.log -> See exceptions

**Comment by kmscode** [comment]
fixed in commit 793095900b3721efba2c0010087a45b022291819
