### ISSUE TITLE
mremoteng startup error object reference not set to an instance of an object

### ISSUE THREAD

**Issue by djsimmers** [mRemoteNG/mRemoteNG#1108]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):

**Comment by sparerd** [comment]
Can we get more details about the error you are seeing?

- Which version of mRemoteNG are you using?
- Can you provide the [log entries](https://github.com/mRemoteNG/mRemoteNG/wiki/Troubleshooting-and-Logging) from the time of the error?
- Does this happen every time?
- Does mRemoteNG still open, or does it crash?

**Comment by djsimmers** [comment]
I ended up removing every trace of mremoteng from the server and registry and was able to get it running.  I don’t know why all of a sudden this happened, but it did, is there a way to back it up so I don’t lose everything if it happens again?

 

   DJ

**Comment by sparerd** [comment]
The only really important file is the connections file. Backups are created automatically on save
See https://github.com/mRemoteNG/mRemoteNG/wiki/Backups-and-Recovery

**Comment by pruperting** [comment]
I also experienced this issue today. After using the app for no problems for months, today suddenly the app asked me for a password when opening it (I've not set a password previously). I assume the connections file was somehow password protected now. I obviously don't know the password, so tried a few combinations and then got the object reference error. 

Here is the log:

`2019-12-31 18:43:38,229 [1] INFO  - mRemoteNG 1.76.20.24615 starting.
2019-12-31 18:43:38,238 [1] INFO  - Command Line: C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe
2019-12-31 18:43:39,370 [1] INFO  - Microsoft Windows 10 Home  64-bit
2019-12-31 18:43:39,370 [1] INFO  - Microsoft .NET CLR 4.0.30319.42000
2019-12-31 18:43:39,371 [1] INFO  - System Culture: en-US/English (United States)
2019-12-31 18:43:39,373 [1] INFO  - Checking FIPS Policy...
2019-12-31 18:43:39,375 [1] INFO  - Checking Lenovo AutoScroll Utility...
2019-12-31 18:43:39,523 [1] WARN  - Loading External Apps failed: Could not FIND file!
2019-12-31 18:43:46,088 [1] WARN  - You are trying to load a connection file that was created using an very early version of mRemote, this could result in an runtime error.
If you run into such an error, please create a new connection file!
2019-12-31 18:43:46,097 [1] ERROR - AddNodeFromXML failed!
Object reference not set to an instance of an object.
   at mRemoteNG.Config.Serializers.Xml.XmlConnectionsDeserializer.AddNodesFromXmlRecursive(XmlNode parentXmlNode, ContainerInfo parentContainer) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\Xml\XmlConnectionsDeserializer.cs:line 167
2019-12-31 18:43:46,098 [1] ERROR - Load From XML failed!
Object reference not set to an instance of an object.
   at mRemoteNG.Config.Serializers.Xml.XmlConnectionsDeserializer.AddNodesFromXmlRecursive(XmlNode parentXmlNode, ContainerInfo parentContainer) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\Xml\XmlConnectionsDeserializer.cs:line 200
   at mRemoteNG.Config.Serializers.Xml.XmlConnectionsDeserializer.Deserialize(String xml, Boolean import) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\Xml\XmlConnectionsDeserializer.cs:line 78
2019-12-31 18:43:46,099 [1] ERROR - Connections file "C:\Users\rupert\AppData\Roaming\mRemoteNG\confCons.xml" could not be loaded!
Object reference not set to an instance of an object.
   at mRemoteNG.Config.Serializers.Xml.XmlConnectionsDeserializer.AddNodesFromXmlRecursive(XmlNode parentXmlNode, ContainerInfo parentContainer) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\Xml\XmlConnectionsDeserializer.cs:line 200
   at mRemoteNG.Config.Serializers.Xml.XmlConnectionsDeserializer.Deserialize(String xml, Boolean import) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\Xml\XmlConnectionsDeserializer.cs:line 89
   at mRemoteNG.Config.Serializers.Xml.XmlConnectionsDeserializer.Deserialize(String xml) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\Xml\XmlConnectionsDeserializer.cs:line 42
   at mRemoteNG.Config.Connections.XmlConnectionsLoader.Load() in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Connections\XmlConnectionsLoader.cs:line 31
   at mRemoteNG.Connection.ConnectionsService.LoadConnections(Boolean useDatabase, Boolean import, String connectionFileName) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Connection\ConnectionsService.cs:line 121
   at mRemoteNG.App.Runtime.LoadConnections(Boolean withDialog) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\App\Runtime.cs:line 87
2019-12-31 18:43:54,233 [1] WARN  - XmingPortablePuttySessions.Watcher.StartWatching() failed: 'sessions' does not exist.
2019-12-31 18:47:49,818 [1] INFO  - mRemoteNG 1.76.20.24615 starting.
2019-12-31 18:47:49,841 [1] INFO  - Command Line: C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe
2019-12-31 18:47:51,066 [1] INFO  - Microsoft Windows 10 Home  64-bit
2019-12-31 18:47:51,066 [1] INFO  - Microsoft .NET CLR 4.0.30319.42000
2019-12-31 18:47:51,068 [1] INFO  - System Culture: en-US/English (United States)
2019-12-31 18:47:51,070 [1] INFO  - Checking FIPS Policy...
2019-12-31 18:47:51,072 [1] INFO  - Checking Lenovo AutoScroll Utility...
2019-12-31 18:47:51,227 [1] INFO  - Loading External Apps from: C:\Users\rupert\AppData\Roaming\mRemoteNG\extApps.xml
`

**Comment by pruperting** [comment]
And this is the full error message:

`---------------------------
Could not load startup file.
---------------------------
The startup connection file could not be loaded.



C:\Users\rupert\AppData\Roaming\mRemoteNG\confCons.xml

Object reference not set to an instance of an object.



In order to prevent data loss, mRemoteNG will now exit.
---------------------------
OK   
---------------------------
`

**Comment by Zoheb786** [comment]
I am also facing the same issue. Don't know what to do..anyone could suggest please I am attaching the snapshot of error
![mRemote](https://github.com/mRemoteNG/mRemoteNG/assets/58637643/62dcd4c9-80a5-4631-94f6-e6912e5c628f)

**Comment by TimurBozkurtogullari** [comment]
> And this is the full error message:
> 
> ## `---------------------------
> Could not load startup file.
> The startup connection file could not be loaded.
> 
> C:\Users\rupert\AppData\Roaming\mRemoteNG\confCons.xml
> 
> Object reference not set to an instance of an object.
> 
> ## In order to prevent data loss, mRemoteNG will now exit.
> ## OK
> `

Press Windows key+r and open the run area. Write %appdata% and enter. After that, the Windows file manager opened, double-clicking the mRemoteNG folder. Find the confCons.xml file and change the file name to confCons.xml.back (Take backup for the worst scenario.) and find the last working backup file, for example, confCons.xml.20240808-0821346338.backup change the name confConf.xml, and then open mremoteng. In this way, my problem is solved.

**Comment by Kvarkas** [comment]
not relevant anymore
