### ISSUE TITLE
Error setting "enable themes"

### ISSUE THREAD

**Issue by evilbaschdi** [mRemoteNG/mRemoteNG#1124]
************** Exception Text **************
System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at WeifenLuo.WinFormsUI.Docking.VisualStudioToolStripExtender.SetStyle(ToolStrip strip, VsVersion version, ThemeBase theme)
   at mRemoteNG.UI.Window.ConnectionTreeWindow.ApplyTheme() in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Window\ConnectionTreeWindow.cs:line 93
   at mRemoteNG.Themes.ThemeManager.ThemeChangedEventHandler.Invoke()
   at mRemoteNG.Themes.ThemeManager.NotifyThemeChanged(Object sender, PropertyChangedEventArgs e) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Themes\ThemeManager.cs:line 203
   at mRemoteNG.Themes.ThemeManager.set_ActiveTheme(ThemeInfo value) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Themes\ThemeManager.cs:line 232
   at mRemoteNG.UI.Forms.OptionsPages.ThemePage.cboTheme_SelectionChangeCommitted(Object sender, EventArgs e) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Forms\OptionsPages\ThemePage.cs:line 121
   at mRemoteNG.UI.Forms.OptionsPages.ThemePage.LoadSettings() in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Forms\OptionsPages\ThemePage.cs:line 67
   at mRemoteNG.UI.Forms.frmOptions.AddOptionsPagesToListView() in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Forms\frmOptions.cs:line 86
   at mRemoteNG.UI.Forms.frmOptions.frmOptions_Load(Object sender, EventArgs e) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Forms\frmOptions.cs:line 33
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by sparerd** [comment]
Thanks for reporting this @evilbaschdi. I'll be releasing a fix for this shortly.

This was caused due to a fix I made for #1110. Goes to show that even small changes are risky :(
