### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by danbuntu** [mRemoteNG/mRemoteNG#1283]
I had mremoteng 1.76.11 installed, connected to a database and working fine. it was then pointed out to me that it was saving the passwords in plain text. 
So I upgraded to 1.76.13 and I get the message 'Object reference not set to an instance of an object'.
I have tried to uninstall mremote, delete the folders in AppData and run a registry cleaner and then reinstalling.

## Expected Behavior
mremote should connect to the database and let me use connections in it - passwords should be encrypted

## Steps to Reproduce (for bugs)

1.Install 1.76.11
2.Connect it to a database
3.upgrade to 1.76.13
4.Try to connect to a database again

## Debug Error log

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at mRemoteNG.Config.Connections.SqlConnectionsLoader.GetDecryptionKey(SqlConnectionListMetaData metaData) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Connections\SqlConnectionsLoader.cs:line 61
   at mRemoteNG.Config.Connections.SqlConnectionsLoader.Load() in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Connections\SqlConnectionsLoader.cs:line 45
   at mRemoteNG.Connection.ConnectionsService.LoadConnections(Boolean useDatabase, Boolean import, String connectionFileName) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Connection\ConnectionsService.cs:line 121
   at mRemoteNG.UI.Forms.OptionsPages.SqlServerPage.ReinitializeSqlUpdater() in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Forms\OptionsPages\SqlServerPage.cs:line 82
   at mRemoteNG.UI.Forms.OptionsPages.SqlServerPage.SaveSettings() in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Forms\OptionsPages\SqlServerPage.cs:line 71
   at mRemoteNG.UI.Forms.frmOptions.btnOK_Click(Object sender, EventArgs e) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Forms\frmOptions.cs:line 112
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3260.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
mRemoteNG
    Assembly Version: 1.76.13.1186
    Win32 Version: 1.76.13.1186
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/mRemoteNG.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3314.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Assembly Version: 2.16.0.0
    Win32 Version: 2.16.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
mRemoteNG.resources
    Assembly Version: 1.76.13.1186
    Win32 Version: 1.76.13.1186
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/en-US/mRemoteNG.resources.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking.ThemeVS2003
    Assembly Version: 2.16.0.0
    Win32 Version: 2.16.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/WeifenLuo.WinFormsUI.Docking.ThemeVS2003.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking.ThemeVS2012
    Assembly Version: 2.16.0.0
    Win32 Version: 2.16.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/WeifenLuo.WinFormsUI.Docking.ThemeVS2012.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking.ThemeVS2013
    Assembly Version: 2.16.0.0
    Win32 Version: 2.16.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/WeifenLuo.WinFormsUI.Docking.ThemeVS2013.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking.ThemeVS2015
    Assembly Version: 2.16.0.0
    Win32 Version: 2.16.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/WeifenLuo.WinFormsUI.Docking.ThemeVS2015.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
MagicLibrary
    Assembly Version: 1.7.4.0
    Win32 Version: 1.7.4.0
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/MagicLibrary.DLL
----------------------------------------
log4net
    Assembly Version: 2.0.8.0
    Win32 Version: 2.0.8.0
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/log4net.DLL
----------------------------------------
BouncyCastle.Crypto
    Assembly Version: 1.8.1.0
    Win32 Version: 1.8.15362.1
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/BouncyCastle.Crypto.DLL
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
ObjectListView
    Assembly Version: 2.9.1.1072
    Win32 Version: 2.9.1.0
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/ObjectListView.DLL
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3282.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3260.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
System.Runtime.Caching
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Caching/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.Caching.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by NislAr98** [comment]
I have the same issue with v1.76.13 prerelease.

**Comment by robertpopa22** [comment]
**Fix available for testing**

A fix for this issue has been implemented in our community fork (`robertpopa22/mRemoteNG`, branch `main`). A beta build including this fix is available from the fork's Releases page.

Please test and report if this resolves your issue.

---

> *We sincerely appreciate the mRemoteNG maintainers and the wonderful community that has kept this project alive and thriving for over a decade. Your work powers thousands of IT professionals worldwide, including us. Our fork builds entirely on your foundation — we're preparing a consolidated Pull Request to contribute these improvements back to the official project. Thank you for everything you've built.*
>
> *— robertpopa22, community contributor*
