### ISSUE TITLE
Random Errors When Closing Tab

### ISSUE THREAD

**Issue by cinquestl** [mRemoteNG/mRemoteNG#1286]
Closing panel with single connection throws error

## Expected Behavior
When closing the panel that contains a single connection will periodically toss an error window.

## Current Behavior
The tab and connection will close, but the error window will display as follows:
Error (1/24/2019 10:40:43 AM)
Couldn't add panel
Object reference notset to an instance of an object.

Clicking OK closes the dialog. mRemoteNG continues to run normally. No loss of connections in other tabs.

## Possible Solution
None known at this time.

## Steps to Reproduce (for bugs)
The error occurred when closing a web connection using port 9675
Here is the text from the log when the error occurred:
2019-01-24 10:40:43,214 [9] INFO  - Saving connections...
2019-01-24 10:40:43,336 [10] ERROR - Couldn't add panel
Object reference not set to an instance of an object.
2019-01-24 10:40:43,336 [9] INFO  - Successfully saved connections
2019-01-24 10:41:04,537 [10] ERROR - Opening connection failed!
Object reference not set to an instance of an object.
   at mRemoteNG.Connection.ConnectionInitiator.SetConnectionForm(Form conForm, String connectionPanel) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Connection\ConnectionInitiator.cs:line 196
   at mRemoteNG.Connection.ConnectionInitiator.OpenConnection(ConnectionInfo connectionInfo, Force force, Form conForm) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Connection\ConnectionInitiator.cs:line 107

## Context
 Simply closing the window. It did not disrupt any other tabs or connections.

## Your Environment

* Version used:
* Windows 10 Pro 64 bit Version 1803 OS Build 17134.523
8 Gb memory
Intel Core I5-6500 processor

**Comment by sparerd** [comment]
It is likely that #155 solves this issue since we removed the library that did the paneling. This will be testable in v1.77

**Comment by cinquestl** [comment]
Thank you. I will let you know once 1.77 is available and running on my
machine.

**Comment by LeonvanHeerden** [comment]
Using Version v1.77.1
I can still simulate this issue by:
Open connection that has a Panel
Then closing the Panel while the Connection is still active. 
I use SSH connections most of the time.

Work Around:
Currently i try to make sure that I close each connection first before closing the Panel. 
Currently I am making sure that i close each

**Comment by farosch** [comment]
Duplicate of #1445

**Comment by farosch** [comment]
I have been able to replicate this on the latest `develop` branch with the steps provided by @LeonvanHeerden 

```
Exception Message
"Cannot access a disposed object.
Object name: 'ConnectionWindow'."

Stack trace
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Delegate method)
   at mRemoteNG.UI.Window.ConnectionWindow.Prot_Event_Closed(Object sender)
   at mRemoteNG.Connection.Protocol.ProtocolBase.ClosedEventHandler.Invoke(Object sender)
   at mRemoteNG.Connection.Protocol.ProtocolBase.CloseBG()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Environment
OS: Microsoft Windows NT 10.0.18362.0
mRemoteNG Version: 1.77.1.27713
Edition: Portable
Cmd line args: 

```
