### ISSUE TITLE
Config is wiped when importing multiple *.RDG files

### ISSUE THREAD

**Issue by Fantomovich** [mRemoteNG/mRemoteNG#1304]
File confCons.xml is wiped If I import *.RDG files (from RDCMan v2.7 build 1406.0). Also wipes as many "confCons.xml.<DATE-TIME>.backup" files, as I imported RDG files (some were with saved credentials).
Domain field in some imported connections cotains "Object reference not set to an instance of an object." and cannot be changed.
Application cannot be started because of zero-sized confCons.xml file.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):

**Comment by Gswaffy** [comment]
I have also had the same problem, creating an export before closing also results in a 0 byte export file.

**Comment by sparerd** [comment]
Does the mRemoteNG.log file show anything? (https://github.com/mRemoteNG/mRemoteNG/wiki/Troubleshooting-and-Logging)

**Comment by Gswaffy** [comment]
Logfile extract:
`2019-03-04 11:54:33,306 [13] ERROR - SaveToXml failed
Value cannot be null.
Parameter name: value
   at System.Xml.Linq.XAttribute..ctor(XName name, Object value)
   at mRemoteNG.Config.Serializers.Xml.XmlConnectionNodeSerializer26.SetElementAttributes(XContainer element, ConnectionInfo connectionInfo) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\Xml\XmlConnectionNodeSerializer26.cs:line 51
   at mRemoteNG.Config.Serializers.Xml.XmlConnectionNodeSerializer26.Serialize(ConnectionInfo connectionInfo) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\Xml\XmlConnectionNodeSerializer26.cs:line 34
   at mRemoteNG.Config.Serializers.Xml.XmlConnectionsDocumentCompiler.CompileConnectionInfoNode(ConnectionInfo connectionInfo) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\Xml\XmlConnectionsDocumentCompiler.cs:line 87
   at mRemoteNG.Config.Serializers.Xml.XmlConnectionsDocumentCompiler.CompileRecursive(ConnectionInfo serializationTarget, XContainer parentElement) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\Xml\XmlConnectionsDocumentCompiler.cs:line 55
   at mRemoteNG.Config.Serializers.Xml.XmlConnectionsDocumentCompiler.CompileRecursive(ConnectionInfo serializationTarget, XContainer parentElement) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\Xml\XmlConnectionsDocumentCompiler.cs:line 61
   at mRemoteNG.Config.Serializers.Xml.XmlConnectionsDocumentCompiler.CompileRecursive(ConnectionInfo serializationTarget, XContainer parentElement) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\Xml\XmlConnectionsDocumentCompiler.cs:line 61
   at mRemoteNG.Config.Serializers.Xml.XmlConnectionsDocumentCompiler.CompileDocument(ConnectionInfo serializationTarget, Boolean fullFileEncryption) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\Xml\XmlConnectionsDocumentCompiler.cs:line 42
   at mRemoteNG.Config.Serializers.Xml.XmlConnectionsSerializer.SerializeConnectionsData(ConnectionInfo serializationTarget) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\Xml\XmlConnectionsSerializer.cs:line 45
2019-03-04 11:54:33,309 [13] INFO  - Successfully saved connections
2019-03-04 11:54:57,592 [13] INFO  - Saving connections...
2019-03-04 11:54:57,603 [13] ERROR - SaveToXml failed
Value cannot be null.
Parameter name: value
   at System.Xml.Linq.XAttribute..ctor(XName name, Object value)
   at mRemoteNG.Config.Serializers.Xml.XmlConnectionNodeSerializer26.SetElementAttributes(XContainer element, ConnectionInfo connectionInfo) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\Xml\XmlConnectionNodeSerializer26.cs:line 51
   at mRemoteNG.Config.Serializers.Xml.XmlConnectionNodeSerializer26.Serialize(ConnectionInfo connectionInfo) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\Xml\XmlConnectionNodeSerializer26.cs:line 34
   at mRemoteNG.Config.Serializers.Xml.XmlConnectionsDocumentCompiler.CompileConnectionInfoNode(ConnectionInfo connectionInfo) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\Xml\XmlConnectionsDocumentCompiler.cs:line 87
   at mRemoteNG.Config.Serializers.Xml.XmlConnectionsDocumentCompiler.CompileRecursive(ConnectionInfo serializationTarget, XContainer parentElement) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\Xml\XmlConnectionsDocumentCompiler.cs:line 55
   at mRemoteNG.Config.Serializers.Xml.XmlConnectionsDocumentCompiler.CompileRecursive(ConnectionInfo serializationTarget, XContainer parentElement) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\Xml\XmlConnectionsDocumentCompiler.cs:line 61
   at mRemoteNG.Config.Serializers.Xml.XmlConnectionsDocumentCompiler.CompileRecursive(ConnectionInfo serializationTarget, XContainer parentElement) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\Xml\XmlConnectionsDocumentCompiler.cs:line 61
   at mRemoteNG.Config.Serializers.Xml.XmlConnectionsDocumentCompiler.CompileDocument(ConnectionInfo serializationTarget, Boolean fullFileEncryption) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\Xml\XmlConnectionsDocumentCompiler.cs:line 42
   at mRemoteNG.Config.Serializers.Xml.XmlConnectionsSerializer.SerializeConnectionsData(ConnectionInfo serializationTarget) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\Xml\XmlConnectionsSerializer.cs:line 45`

**Comment by sparerd** [comment]
Thanks for providing that, that does help narrow it down a bit. I will look into which property may be causing the issue.

**Comment by sparerd** [comment]
I am releasing v1.76.15 which has a few changes which will hopefully resolve this issue for you both.
