### ISSUE TITLE
Exception while attempting to create a new theme

### ISSUE THREAD

**Issue by kmscode** [mRemoteNG/mRemoteNG#1341]
Creating new theme causes an exception

## Expected Behavior
New theme should be created

## Steps to Reproduce (for bugs)

1. Tools -> Options -> Themes
2. Click New
3. Get exception

![image](https://user-images.githubusercontent.com/16654335/54091082-10d0a800-4352-11e9-8ded-442522ea4cb9.png)

```
Exception Message
"The path is not of a legal form."

Stack trace
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at System.IO.Path.GetDirectoryName(String path)
   at mRemoteNG.Themes.ThemeSerializer.SaveToXmlFile(ThemeInfo themeToSave, ThemeInfo baseTheme) in C:\projects\mremoteng-ke3rl\mRemoteV1\Themes\ThemeSerializer.cs:line 18
   at mRemoteNG.Themes.ThemeManager.addTheme(ThemeInfo baseTheme, String newThemeName) in C:\projects\mremoteng-ke3rl\mRemoteV1\Themes\ThemeManager.cs:line 245
   at mRemoteNG.UI.Forms.OptionsPages.ThemePage.btnThemeNew_Click(Object sender, EventArgs e) in C:\projects\mremoteng-ke3rl\mRemoteV1\UI\Forms\OptionsPages\ThemePage.cs:line 190
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):

**Comment by kmscode** [comment]
Discovered while attempting to re-test #1093

**Comment by robertpopa22** [comment]
**Fix available for testing**

A fix for this issue has been implemented in our community fork (`robertpopa22/mRemoteNG`, branch `main`). A beta build including this fix is available from the fork's Releases page.

Please test and report if this resolves your issue.

---

> *We sincerely appreciate the mRemoteNG maintainers and the wonderful community that has kept this project alive and thriving for over a decade. Your work powers thousands of IT professionals worldwide, including us. Our fork builds entirely on your foundation — we're preparing a consolidated Pull Request to contribute these improvements back to the official project. Thank you for everything you've built.*
>
> *— robertpopa22, community contributor*
