### ISSUE TITLE
Exception When Applying Certain Themes

### ISSUE THREAD

**Issue by erniefarias** [mRemoteNG/mRemoteNG#1387]
## Expected Behavior

After applying a theme, the window's theme should change (and finish changing after a restart).

## Current Behavior

There are exceptions when changing between certain themes - generally switching from a dark theme to another dark theme.
Example: If the current theme is "vs2015Dark" and the theme is changed to "vs2012Dark", an exception pops up.

************** Exception Text **************
System.ArgumentException: Parameter is not valid.
   at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.FillRectangle(Brush brush, Int32 x, Int32 y, Int32 width, Int32 height)
   at System.Drawing.Graphics.FillRectangle(Brush brush, Rectangle rect)
   at WeifenLuo.WinFormsUI.ThemeVS2013.VS2013SplitterControl.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

## Steps to Reproduce (for bugs)

1. Choose a dark theme.
2. Restart to finish applying the theme (not sure if this step is needed)
3. Choose another dark theme.

## Your Environment

* Version used: 1.76.18.26260
* Operating System and version (e.g. Windows 10 1709 x64): Windows 10 1809 x64

**Comment by kmscode** [comment]
This is fixed in the develop branch and will be included in 1.77 - lots of theming related fixed included in the next release.
