### ISSUE TITLE
Issue when Importing RDC man files

### ISSUE THREAD

**Issue by declan-marks** [mRemoteNG/mRemoteNG#1401]
When importing RDCMan file we get the following error.

`2019-04-11 09:47:17,681 [7] INFO  - Successfully saved connections
2019-04-11 09:47:23,167 [9] INFO  - Saving connections...
2019-04-11 09:47:23,167 [9] ERROR - SaveToXml failed
Value cannot be null.
Parameter name: value
   at System.Xml.Linq.XAttribute..ctor(XName name, Object value)
   at 
mRemoteNG.Config.Serializers.Xml.XmlConnectionNodeSerializer26.SetElementAttributes(XContainer element, ConnectionInfo connectionInfo) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\Xml\XmlConnectionNodeSerializer26.cs:line 51
   at mRemoteNG.Config.Serializers.Xml.XmlConnectionNodeSerializer26.Serialize(ConnectionInfo connectionInfo) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\Xml\XmlConnectionNodeSerializer26.cs:line 34
   at mRemoteNG.Config.Serializers.Xml.XmlConnectionsDocumentCompiler.CompileConnectionInfoNode(ConnectionInfo connectionInfo) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\Xml\XmlConnectionsDocumentCompiler.cs:line 87
   at mRemoteNG.Config.Serializers.Xml.XmlConnectionsDocumentCompiler.CompileRecursive(ConnectionInfo serializationTarget, XContainer parentElement) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\Xml\XmlConnectionsDocumentCompiler.cs:line 55
   at 
mRemoteNG.Config.Serializers.Xml.XmlConnectionsDocumentCompiler.CompileRecursive(ConnectionInfo serializationTarget, XContainer parentElement) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\Xml\XmlConnectionsDocumentCompiler.cs:line 61
   at mRemoteNG.Config.Serializers.Xml.XmlConnectionsDocumentCompiler.CompileRecursive(ConnectionInfo serializationTarget, XContainer parentElement) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\Xml\XmlConnectionsDocumentCompiler.cs:line 61
   at mRemoteNG.Config.Serializers.Xml.XmlConnectionsDocumentCompiler.CompileRecursive(ConnectionInfo serializationTarget, XContainer parentElement) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\Xml\XmlConnectionsDocumentCompiler.cs:line 61
   at mRemoteNG.Config.Serializers.Xml.XmlConnectionsDocumentCompiler.CompileRecursive(ConnectionInfo serializationTarget, XContainer parentElement) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\Xml\XmlConnectionsDocumentCompiler.cs:line 61
   at mRemoteNG.Config.Serializers.Xml.XmlConnectionsDocumentCompiler.CompileDocument(ConnectionInfo serializationTarget, Boolean fullFileEncryption) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\Xml\XmlConnectionsDocumentCompiler.cs:line 42
   at mRemoteNG.Config.Serializers.Xml.XmlConnectionsSerializer.SerializeConnectionsData(ConnectionInfo serializationTarget) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\Xml\XmlConnectionsSerializer.cs:line 45
`

The file import successfully with no errors. The issue is when trying to save the the xml. The file is 0KB. I can't even export as CSV. When looking in Domain field their is an error 'Object reference is not set to an instance of an object'. I have tried doing this such as setting the domain on the error to inherit and set the domain on the folder. This still didn't fix the issue. 

## Expected Behavior
The file should save successfully

## Current Behavior
The file doesn't save correctly.

## Steps to Reproduce (for bugs)
1. Import RDCMan file.
2. Save the file

## Context
This has slowed workflow because all connections now have to be added manually.

## Environment
Windows 10.0.17763.379 x64
mRemote-NG 1.76.19

**Comment by sparerd** [comment]
Taking a look

**Comment by sparerd** [comment]
I've fixed the issue that was causing this, a new version will be released shortly.

**Comment by sparerd** [comment]
v1.76.20 has been released which includes the fix for this issue:
https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.76.20
