### ISSUE TITLE
MRemote won't start

### ISSUE THREAD

**Issue by mmcnay** [mRemoteNG/mRemoteNG#1478]
## Expected Behavior
 Expecting the product to lauch

## Current Behavior

From application Log
Application: mRemoteNG.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Xml.XmlException
   at System.Xml.XmlTextReaderImpl.Throw(System.Exception)
   at System.Xml.XmlTextReaderImpl.Throw(System.String, System.String[])
   at System.Xml.XmlTextReaderImpl.ThrowInvalidChar(Char[], Int32, Int32)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Configuration.XmlUtil..ctor(System.IO.Stream, System.String, Boolean, System.Configuration.ConfigurationSchemaErrors)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(System.Configuration.ConfigurationSchemaErrors)
   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs)

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs)
   at System.Configuration.Internal.InternalConfigRoot.OnConfigRemoved(System.Configuration.Internal.InternalConfigEventArgs)
   at System.Configuration.Internal.InternalConfigRoot.RemoveConfigImpl(System.String, System.Configuration.BaseConfigurationRecord)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(System.String, Boolean, Boolean, Boolean, Boolean, System.Object ByRef, System.Object ByRef)
   at System.Configuration.BaseConfigurationRecord.GetSection(System.String)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(System.String)
   at System.Configuration.ConfigurationManager.GetSection(System.String)
   at System.Configuration.ClientSettingsStore.ReadSettings(System.String, Boolean)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(System.Configuration.SettingsContext, System.Configuration.SettingsPropertyCollection)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(System.Configuration.SettingsProvider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(System.String)
   at System.Configuration.SettingsBase.get_Item(System.String)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(System.String)
   at System.Configuration.ApplicationSettingsBase.get_Item(System.String)
   at mRemoteNG.Settings.get_SingleInstance()
   at mRemoteNG.App.ProgramRoot.Main(System.String[])

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: 1.76.20.24615
* Operating System and version (e.g. Windows 10 1709 x64):
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.17134 Build 17134
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	SAC-LT-MASON
System Manufacturer	Dell Inc.
System Model	Latitude E7450
System Type	x64-based PC
System SKU	062E
Processor	Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz, 2594 Mhz, 2 Core(s), 4 Logical Processor(s)
BIOS Version/Date	Dell Inc. A16, 5/5/2017
SMBIOS Version	2.8
Embedded Controller Version	255.255
BIOS Mode	Legacy
BaseBoard Manufacturer	Dell Inc.
BaseBoard Model	Not Available
BaseBoard Name	Base Board
Platform Role	Mobile
Secure Boot State	Unsupported
PCR7 Configuration	Binding Not Possible
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.17134.619"
User Name	TOTLCOM\mason
Time Zone	Pacific Daylight Time
Installed Physical Memory (RAM)	8.00 GB
Total Physical Memory	7.87 GB
Available Physical Memory	2.33 GB
Total Virtual Memory	20.4 GB
Available Virtual Memory	14.0 GB
Page File Space	12.5 GB

**Comment by sparerd** [comment]
@mmcnay Sorry for the delay in responding. It looks like the app is having some issues with loading the settings file. Try deleting your `user.settings` file and starting mRemoteNG again. File location here: https://github.com/mRemoteNG/mRemoteNG/wiki/User-settings-file

General troubleshooting tips here: https://mremoteng.readthedocs.io/en/latest/troubleshooting.html#crash-at-startup

**Comment by mmcnay** [comment]
I got it working thank you.

Mason McNay
TOTLCOM Inc.
916-873-1160 direct
www.totlcom.com<http://www.totlcom.com/>
Customer satisfaction is our standard, not our goal.

**Comment by sparerd** [comment]
Glad to hear, I'll close out this issue.

**Comment by cbotsikas** [comment]
Thank you. I just had the same issue. Here's how my user.config file looked like:
![image](https://user-images.githubusercontent.com/1640100/63049082-2dac7100-bed8-11e9-876e-cf7cbc7955cc.png)

**Comment by mm-riteshr** [comment]
the advised solution to remove user.setting worked.
In my case I had to delete the folder as well and then repair mRemoteNG installation. then got all as fresh.

**Comment by KC-WANG** [comment]
> Thank you. I just had the same issue. Here's how my user.config file looked like: ![image](https://user-images.githubusercontent.com/1640100/63049082-2dac7100-bed8-11e9-876e-cf7cbc7955cc.png)

After Windows 11 2024 Update, the same issue occurs and is fixed by this method. Thanks a lot.
