### ISSUE TITLE
FIPS compliance regression

### ISSUE THREAD

**Issue by PipeItToDevNull** [mRemoteNG/mRemoteNG#1557]
Issue #222 is closed with the 1.76.13+ line being compatible but the 1.77 line seems to have regressed, with FIPS again braking the application.

**Comment by sparerd** [comment]
By "breaking the application", do you mean that a dialog is shown about a "compatibility problem" or something like that?

After a quick look, I can't find anything that has changed in the actual FIPS detection logic. Do you still get the option to proceed anyway?

**Comment by PipeItToDevNull** [comment]
I did receive the "Continue" prompt but after the first launch I am unable to open the "Options" menu receiving this error:

```
Exception Message
"Decryption failed. {0}"

Stack trace
   at mRemoteNG.Security.SymmetricEncryption.LegacyRijndaelCryptographyProvider.Decrypt(String ciphertextBase64, SecureString password)
   at mRemoteNG.UI.Forms.OptionsPages.CredentialsPage.LoadSettings()
   at mRemoteNG.UI.Forms.FrmOptions.AddOptionsPagesToListView()
   at mRemoteNG.UI.Forms.FrmOptions.frmOptions_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Environment
OS: Microsoft Windows NT 10.0.18362.0
mRemoteNG Version: 1.77.1.27713
Edition: Portable
Cmd line args: 

```

**Comment by PipeItToDevNull** [comment]
Ok, I cleaned out the directory I was using and grabbed fresh files to reproduce this. When I use the Credentials tab in Options I am unable to set a global credential. I receive the error:
```
----------
ErrorMsg
09/03/2019 08:56:45
Encryption failed. This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.
----------
```

After this I am no longer to open the options dialog.

**Comment by sparerd** [comment]
Ok, I'll take a look at why that might be happening.

**Comment by sparerd** [comment]
Did you say that v1.76.13+ was working for you when you perform the same actions?

**Comment by PipeItToDevNull** [comment]
OK, I assumed the issue would not be present in 1.76.13+ because #222 was closed. I checked on a clean set of 1.76.20 and have the same error.

**Comment by sparerd** [comment]
Was FIPS only recently enabled on your system, or has it been for a while now?

The reason I ask is that in certain parts of our code, we use the `RijndaelManaged` crypto class provided by Microsoft which checks the system FIPS setting. It is being phased out from our code, but is still used in some places, like with the default credentials setting on the credential page. I would expect that this has been an issue for a long time, but only now noticed since we allow users to continue using the app even though FIPS is enabled.

There may be ways around this, but the real solution will be to remove the deprecated calls to `RijndaelManaged`.

**Comment by PipeItToDevNull** [comment]
FIPS has been in use for a long time for me. I do not believe I ever used this feature though because I didnt know that it existed until I installed it on another machine.

**Comment by jmoneste** [comment]
Good afternoon,

Is this bug being tracked for any future version?
We're unable to use on FIPS enabled servers as well. Clean install of 1.76.20.24615.
It seems to be caused by the ciphers and algorithms used by FIPS.
