### ISSUE TITLE
mRemoteNG Version Update: 1.77.1.27654

### ISSUE THREAD

**Issue by NiiTRaNE** [mRemoteNG/mRemoteNG#1559]
```
Exception Message
"Column 'VmId' does not belong to table ."

Stack trace
   at System.Data.DataRow.GetDataColumn(String columnName)
   at System.Data.DataRow.get_Item(String columnName)
   at mRemoteNG.Config.Serializers.MsSql.DataTableDeserializer.PopulateConnectionInfoFromDatarow(DataRow dataRow, ConnectionInfo connectionInfo) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\MsSql\DataTableDeserializer.cs:line 92
   at mRemoteNG.Config.Serializers.MsSql.DataTableDeserializer.DeserializeContainerInfo(DataRow row) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\MsSql\DataTableDeserializer.cs:line 73
   at mRemoteNG.Config.Serializers.MsSql.DataTableDeserializer.CreateNodesFromTable(DataTable table) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\MsSql\DataTableDeserializer.cs:line 53
   at mRemoteNG.Config.Serializers.MsSql.DataTableDeserializer.Deserialize(DataTable table) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\MsSql\DataTableDeserializer.cs:line 35
   at mRemoteNG.Config.Connections.SqlConnectionsLoader.Load() in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Connections\SqlConnectionsLoader.cs:line 57
   at mRemoteNG.Connection.ConnectionsService.LoadConnections(Boolean useDatabase, Boolean import, String connectionFileName) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Connection\ConnectionsService.cs:line 126
   at mRemoteNG.UI.Forms.OptionsPages.SqlServerPage.ReinitializeSqlUpdater() in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Forms\OptionsPages\SqlServerPage.cs:line 82
   at mRemoteNG.UI.Forms.OptionsPages.SqlServerPage.SaveSettings() in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Forms\OptionsPages\SqlServerPage.cs:line 72
   at mRemoteNG.UI.Forms.FrmOptions.btnOK_Click(Object sender, EventArgs e) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Forms\FrmOptions.cs:line 128
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Environment
OS: Microsoft Windows NT 10.0.17134.0
mRemoteNG Version: 1.77.1.27654
Edition: MSI
Cmd line args: 

```

**Comment by NiiTRaNE** [comment]
![mRemoteNG_UpdateSQL](https://user-images.githubusercontent.com/14690419/64306506-f5410580-cf60-11e9-8cb7-3f3d32069f7e.png)

**Comment by jcg-amper** [comment]
For MySQL this would be:
```
ALTER TABLE mRemoteNG.tblCons  
ADD VmId varchar(128) NOT NULL DEFAULT '',
ADD UseVmId tinyint(1) NOT NULL DEFAULT 0,
ADD InheritVmId tinyint(1) NOT NULL DEFAULT 0,
ADD InheritUseVmId tinyint(1) NOT NULL DEFAULT 0,
ADD RdpVersion varchar(128) NOT NULL DEFAULT '',
ADD InheritRdpVersion TINYINT(1) NOT NULL DEFAULT 0;
```

**Comment by grimson73** [comment]
Clean portable v1.76.20 -> SQL connect ok, add some connections.
Update v1.76.20 portable to v1.77.1 portable -> start program -> msgbox 'load from sql failed'

**Comment by danmed** [comment]
Having the same issue with Prerelease v1.77.1

Wether i import from on old connection file or start a fresh DB, as soon as i enter a single connection and close, i cannot open and read from the DB again with this same error.

**Comment by farosch** [comment]
**You are running an experimental feature of mrng in a developer build of the software.
Expect things to not work!**
In the future there might be some kind of pupop/indication that notifies you about table changes or even an automated way without notifying users at all but for now you will need to be able to read and understand error messages.
If you are not, simply don't use the SQL feature or at least stick with the stable build! (as @grimson73 said: it works in the latest stable)

**Comment by polyakovrbc** [comment]
> For MySQL this would be:
> 
> ```
> ALTER TABLE mRemoteNG.tblCons  
> ADD VmId varchar(128) NOT NULL DEFAULT '',
> ADD UseVmId tinyint(1) NOT NULL DEFAULT 0,
> ADD InheritVmId tinyint(1) NOT NULL DEFAULT 0,
> ADD InheritUseVmId tinyint(1) NOT NULL DEFAULT 0,
> ADD RdpVersion varchar(128) NOT NULL DEFAULT '',
> ADD InheritRdpVersion TINYINT(1) NOT NULL DEFAULT 0;
> ```

It's helped me!
