### ISSUE TITLE
Faulting application name: mRemoteNG.exe, version: 1.76.20.24615 since windows update KB4507419.

### ISSUE THREAD

**Issue by TieleDeclercq** [mRemoteNG/mRemoteNG#1573]
Since this afternoon, mRemoteNG stops working immediately after starting. mRemote was freezing and I could not even exit the process. I had to do a hard reset. Afterward, mRemote would not boot and event log is showing .NET runtime errors. I noticed that windows update KB4507419 had just been installed.

Remove & reinstall using the latest version did not fix the issue.

## Expected Behavior
Start & function

## Current Behavior
Start & close

Event log shows Application Error:
Faulting application name: mRemoteNG.exe, version: 1.76.20.24615, time stamp: 0x5cb09552
Faulting module name: KERNELBASE.dll, version: 10.0.17763.652, time stamp: 0x57e2061a
Exception code: 0xe0434352
Fault offset: 0x0011fd82
Faulting process id: 0xb8c
Faulting application start time: 0x01d567c9c0aaf7b7
Faulting application path: C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 45df9f06-67ef-480f-9343-6f5f59d37348
Faulting package full name: 
Faulting package-relative application ID: 

and .NET Runtime:
Application: mRemoteNG.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Xml.XmlException
   at System.Xml.XmlTextReaderImpl.Throw(System.Exception)
   at System.Xml.XmlTextReaderImpl.Throw(System.String, System.String[])
   at System.Xml.XmlTextReaderImpl.ParseText(Int32 ByRef, Int32 ByRef, Int32 ByRef)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlTextReaderImpl.Skip()
   at System.Xml.XmlTextReader.Skip()
   at System.Configuration.XmlUtil.StrictSkipToNextElement(System.Configuration.ExceptionAction)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   at System.Configuration.BaseConfigurationRecord.ScanSections(System.Configuration.XmlUtil)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(System.Configuration.ConfigurationSchemaErrors)
   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs)

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs)
   at System.Configuration.Internal.InternalConfigRoot.OnConfigRemoved(System.Configuration.Internal.InternalConfigEventArgs)
   at System.Configuration.Internal.InternalConfigRoot.RemoveConfigImpl(System.String, System.Configuration.BaseConfigurationRecord)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(System.String, Boolean, Boolean, Boolean, Boolean, System.Object ByRef, System.Object ByRef)
   at System.Configuration.BaseConfigurationRecord.GetSection(System.String)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(System.String)
   at System.Configuration.ConfigurationManager.GetSection(System.String)
   at System.Configuration.ClientSettingsStore.ReadSettings(System.String, Boolean)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(System.Configuration.SettingsContext, System.Configuration.SettingsPropertyCollection)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(System.Configuration.SettingsProvider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(System.String)
   at System.Configuration.SettingsBase.get_Item(System.String)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(System.String)
   at System.Configuration.ApplicationSettingsBase.get_Item(System.String)
   at mRemoteNG.Settings.get_SingleInstance()
   at mRemoteNG.App.ProgramRoot.Main(System.String[])

## Possible Solution
Kiss some MS butt

## Steps to Reproduce (for bugs)
It wasn't me!

## Context
Had to go look for alternatives since mRemoteNG didn't work anymore

## Your Environment
Microsoft Windows [Version 10.0.17763.678]
A bunch of dev & it tools installed

**Comment by farosch** [comment]
Please provide the mrng logfile and a dump. See https://mremoteng.readthedocs.io/en/latest/troubleshooting.html on how to do this.

**Comment by farosch** [comment]
Closed due to OP not responding. btw this is most likely due to a broken .Net Framework installation. https://www.microsoft.com/en-us/download/details.aspx?id=30135 might very well fix this.
