### ISSUE TITLE
Unable to Use MSSQL for connections

### ISSUE THREAD

**Issue by techtutorials** [mRemoteNG/mRemoteNG#1585]
OS: Microsoft Windows NT 10.0.18362.0
mRemoteNG Version: 1.77.1.27654
Edition: MSI

MSSQL Server 10.50.1600

Error Message
 at mRemoteNG.Tools.Extensions.ThrowIfNullOrEmpty(String value, String argName) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Tools\Extensions.cs:line 51
   at mRemoteNG.Security.Authentication.PasswordAuthenticator..ctor(ICryptographyProvider cryptographyProvider, String cipherText, Func`1 authenticationRequestor) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Security\Authentication\PasswordAuthenticator.cs:line 22
   at mRemoteNG.Config.Connections.SqlConnectionsLoader.GetDecryptionKey(SqlConnectionListMetaData metaData) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Connections\SqlConnectionsLoader.cs:line 66
   at mRemoteNG.Config.Connections.SqlConnectionsLoader.Load() in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Connections\SqlConnectionsLoader.cs:line 49
   at mRemoteNG.Connection.ConnectionsService.LoadConnections(Boolean useDatabase, Boolean import, String connectionFileName) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Connection\ConnectionsService.cs:line 126
   at mRemoteNG.UI.Forms.OptionsPages.SqlServerPage.ReinitializeSqlUpdater() in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Forms\OptionsPages\SqlServerPage.cs:line 82
   at mRemoteNG.UI.Forms.OptionsPages.SqlServerPage.SaveSettings() in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Forms\OptionsPages\SqlServerPage.cs:line 72
   at mRemoteNG.UI.Forms.FrmOptions.btnOK_Click(Object sender, EventArgs e) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Forms\FrmOptions.cs:line 128
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by techtutorials** [comment]
After deleting database and re-created with new SQL script, able to connect database however unable to create new connections.

----------
ErrorMsg
09/23/2019 11:18:14
Couldn't save connections file as ""!
The given ColumnMapping does not match up with any column in the source or destination.
----------

**Comment by CarstenFabian** [comment]
Hi,
I have the same problem:
"Couldn't save connections file as ""! The given ColumnMapping does not match up with any column in the source or destination."
I'm using mRemoteNG 1.76.18.26260 an MS SQL Server Standard 12.0.6293.0.
Any help would be appreciated.
Solutions on https://github.com/mRemoteNG/mRemoteNG/issues/408 didn't help.

**Comment by Filippo125** [comment]
I think the last change on database behaviour in the development branch would fix it.

**Comment by jamesaepp** [comment]
I also have this issue. Brand new database the user has db_owner permission to. mRemoteNG 1.77.0.41252. 

I copied the script from the readthedocs using the 'latest' version. However I had to edit the readthedocs to be:
"        [Favorite] int NOT NULL,"
instead of:
"        [Favorite] tinyint(1) NOT NULL,"
before the script would complete successfully.

**Comment by Elsarild** [comment]
I ran into the same issue that I can't create the database with the current creation scripts. I tried your fix, but now I'm getting 

Couldn't save connections file as ""!
The given ColumnMapping does not match up with any column in the source or destination.

However, i noticed you're running 1.77.0.41252., I'm on 1.76.20.24615 where do I get that version?

**Comment by bite-byte-ru** [comment]
> I ran into the same issue that I can't create the database with the current creation scripts. I tried your fix, but now I'm getting
> 
> Couldn't save connections file as ""!
> The given ColumnMapping does not match up with any column in the source or destination.

Hi! 
Did you manage to find a solution?

**Comment by Elsarild** [comment]
> 
> 
> > I ran into the same issue that I can't create the database with the current creation scripts. I tried your fix, but now I'm getting
> > Couldn't save connections file as ""!
> > The given ColumnMapping does not match up with any column in the source or destination.
> 
> Hi!
> Did you manage to find a solution?

No we decided to invest in Royal TS and use a shared connection file via. OneDrive instead.

**Comment by bite-byte-ru** [comment]
> > > I ran into the same issue that I can't create the database with the current creation scripts. I tried your fix, but now I'm getting
> > > Couldn't save connections file as ""!
> > > The given ColumnMapping does not match up with any column in the source or destination.
> > 
> > 
> > Hi!
> > Did you manage to find a solution?
> 
> No we decided to invest in Royal TS and use a shared connection file via. OneDrive instead.
We can talk about royalapps? My E-mail: bite-byte@yandex.ru
