### ISSUE TITLE
Value Dispose() cannot be called while doing CreateHandle()

### ISSUE THREAD

**Issue by tommybuck** [mRemoteNG/mRemoteNG#1620]
Error message appeared when closing tab.
## Expected Behavior

tab should close without error.
## Current Behavior

Error message popped up randomly when I closed a tab.
## Steps to Reproduce (for bugs)

1. Not sure how to reproduce as it was a one off?

## From debug window:
```
Exception Message
"Value Dispose() cannot be called while doing CreateHandle()."

Stack trace
   at System.Windows.Forms.Control.Dispose(Boolean disposing)
   at mRemoteNG.Connection.InterfaceControl.Dispose(Boolean disposing) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Connection\InterfaceControl.Designer.cs:line 18
   at System.ComponentModel.Component.Dispose()
   at System.Windows.Forms.Control.Dispose(Boolean disposing)
   at System.Windows.Forms.Form.Dispose(Boolean disposing)
   at mRemoteNG.UI.Tabs.ConnectionTab.Dispose(Boolean disposing) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Tabs\ConnectionTab.Designer.cs:line 20
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Environment
OS: Microsoft Windows NT 10.0.18362.0
mRemoteNG Version: 1.77.1.27654
Edition: MSI
Cmd line args: 

```
## from log file:
`2019-10-14 11:37:51,694 [12] ERROR - Couldn't dispose control, probably form is already closed (Connection.Protocol.Base)
Cannot access a disposed object.
Object name: 'InterfaceControl'.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Delegate method)
   at mRemoteNG.Connection.Protocol.ProtocolBase.DisposeControl() in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Connection\Protocol\ProtocolBase.cs:line 236
   at mRemoteNG.Connection.Protocol.ProtocolBase.CloseBG() in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Connection\Protocol\ProtocolBase.cs:line 163`

**Comment by robertpopa22** [comment]
**Fix available for testing**

**Commit:** [`7425f54f`](https://github.com/robertpopa22/mRemoteNG/commit/7425f54fa49ad06b4115fafa16a58fff3b4d9e2b)
**Branch:** `main`
**What changed:** Guard Dispose() calls with IsHandleCreated check and marshal

**Download latest beta:** [v1.81.0-beta.2](https://github.com/robertpopa22/mRemoteNG/releases)

Please test and report if this resolves your issue.

---
_Automated by mRemoteNG Issue Intelligence System_
