### ISSUE TITLE
Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index

### ISSUE THREAD

**Issue by guillermorgil** [mRemoteNG/mRemoteNG#1636]
at System.Collections.ArrayList.get_Item(Int32 index)
   at System.Collections.ArrayList.IListWrapper.get_Item(Int32 index)
   at BrightIdeasSoftware.TreeListView.Tree.RebuildObjectMap(Int32 startIndex)
   at BrightIdeasSoftware.TreeListView.Tree.RebuildChildren(Object model)
   at BrightIdeasSoftware.TreeListView.RefreshObjects(IList modelObjects)
   at BrightIdeasSoftware.ObjectListView.RefreshObject(Object modelObject)
   at mRemoteNG.UI.Controls.ConnectionTree.HandleCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.Specialized.NotifyCollectionChangedEventHandler.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
   at mRemoteNG.Tree.ConnectionTreeModel.RaiseCollectionChangedEvent(Object sender, NotifyCollectionChangedEventArgs args)
   at mRemoteNG.Container.ContainerInfo.RaiseCollectionChangedEvent(Object sender, NotifyCollectionChangedEventArgs args)
   at mRemoteNG.Container.ContainerInfo.RaiseCollectionChangedEvent(Object sender, NotifyCollectionChangedEventArgs args)
   at mRemoteNG.Container.ContainerInfo.RaiseCollectionChangedEvent(Object sender, NotifyCollectionChangedEventArgs args)
   at mRemoteNG.Container.ContainerInfo.SortOn[TProperty](Func`2 propertyToCompare, ListSortDirection sortDirection)
   at mRemoteNG.Container.ContainerInfo.SortOnRecursive[TProperty](Func`2 propertyToCompare, ListSortDirection sortDirection)
   at mRemoteNG.Container.ContainerInfo.SortOnRecursive[TProperty](Func`2 propertyToCompare, ListSortDirection sortDirection)
   at mRemoteNG.Container.ContainerInfo.SortOnRecursive[TProperty](Func`2 propertyToCompare, ListSortDirection sortDirection)
   at mRemoteNG.Container.ContainerInfo.SortRecursive(ListSortDirection sortDirection)
   at mRemoteNG.UI.Controls.ConnectionTree.SortRecursive(ConnectionInfo sortTarget, ListSortDirection sortDirection)
   at mRemoteNG.UI.Window.ConnectionTreeWindow.<SetMenuEventHandlers>b__34_2(Object sender, EventArgs args)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.MenuStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Enviroment
OS: Microsoft Windows NT 10.0.18362.0
mRemoteNG Version: 1.77.1.27713
Edition: Portable
Cmd line args:

**Comment by farosch** [comment]
What were you doing when the error occured? @guillermorgil

**Comment by ryankpaul** [comment]
Same error.  This happens after I update an existing record Name field and <Tab> out of that field to the last field in the connection, but then forget that the Tab key takes me back instead of forward (maybe that's a setting that I messed up?) so instead I press <Shift>+<Tab> to get back into the Name field in the same record, and then the unhandled exception window pops up.  I can close the window and continue working as normal, but I figure it's at least useful for you to know there's an issue somewhere.

If I do not update the Name field first, the issue does not occur.

This happens often for me because my workflow involves producing duplicate connection records, and then renaming them.

Also - feature request to change the <Tab> behavior to advance down the fields rather than up.  (Unless of course, as I suggested before, I am just too thick to realize I changed it myself, and/or too lazy to change it back.)

This software has changed my life.  THANK YOU for working on it!

**Comment by robertpopa22** [comment]
Triage refresh (P2): this issue has been inactive for a long time. Please retest on the latest build and share reproducible steps, expected vs actual behavior, and logs/screenshots. If there is no confirmation/update, maintainers can close it as stale or not reproducible.
