### ISSUE TITLE
Crash after closing panel

### ISSUE THREAD

**Issue by roni75020** [mRemoteNG/mRemoteNG#1642]
## Current Behavior
When closing a panel with severl sessions opened the application crashes. 

 Stacktrace
Cannot access a disposed object.
Object name: 'ConnectionWindow'.
at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
at System.Windows.Forms.Control.Invoke(Delegate method)
at mRemoteNG.UI.Window.ConnectionWindow.Prot_Event_Closed(Object sender)
at mRemoteNG.Connection.Protocol.ProtocolBase.ClosedEventHandler.Invoke(Object sender)
at mRemoteNG.Connection.Protocol.ProtocolBase.CloseBG()
at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

## Steps to Reproduce (for bugs)

1. Open 2 connections in pannel1
2. Open 2 other connections in pannel2
3. Close one of the panels

## Your Environment
OS: Microsoft Windows NT 10.0.17134.0
mRemoteNG Version: 1.77.1.27713
Edition: Portable
Cmd line args:

**Comment by ydbank** [comment]
我遇到的是相同问题，我是win7 64bit

**Comment by vlf** [comment]
Also happens on:
OS: Microsoft Windows NT 10.0.17763.0
mRemoteNG Version: 1.77.1.27654
Edition: MSI

Reproducible by: 
1. View > Add connection panel
2. Open any **SSH** connection in that panel
3. Close panel with the SSH connection 

Closing the connection first, before closing the tab, does not throw the exception.

**Comment by alpa80** [comment]
reproduced Two ssh tab opened under one group tab

```
Exception Message
"Cannot access a disposed object.
Object name: 'ConnectionWindow'."

Stack trace
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Delegate method)
   at mRemoteNG.UI.Window.ConnectionWindow.Prot_Event_Closed(Object sender)
   at mRemoteNG.UI.Window.ConnectionWindow.Prot_Event_Closed(Object sender)
   at mRemoteNG.Connection.Protocol.ProtocolBase.ClosedEventHandler.Invoke(Object sender)
   at mRemoteNG.Connection.Protocol.ProtocolBase.CloseBG()
   at mRemoteNG.Connection.Protocol.ProtocolBase.CloseBG()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
   at System.Threading.ThreadHelper.ThreadStart()

Environment
OS: Microsoft Windows NT 6.1.7601 Service Pack 1
mRemoteNG Version: 1.77.1.27713
Edition: Portable
Cmd line args: 

```

**Comment by Kvarkas** [comment]
not relevant
