### ISSUE TITLE
An Unhandled Exception has occured

### ISSUE THREAD

**Issue by raghuariga1** [mRemoteNG/mRemoteNG#1675]
Issue with login to server

```
Exception Message
"Object reference not set to an instance of an object."

Stack trace
   at WeifenLuo.WinFormsUI.Docking.DockPaneStripBase.SelectClosestPane(Int32 index)
   at WeifenLuo.WinFormsUI.Docking.DockPaneStripBase.TryCloseTab(Int32 index)
   at mRemoteNG.UI.Tabs.DockPaneStripNG.TabCloseButtonHit(Int32 index) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Tabs\DockPaneStripNG.cs:line 1166
   at mRemoteNG.UI.Tabs.DockPaneStripNG.OnMouseClick(MouseEventArgs e) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Tabs\DockPaneStripNG.cs:line 1158
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at WeifenLuo.WinFormsUI.Docking.DockPaneStripBase.WndProc(Message& m)
   at mRemoteNG.UI.Tabs.DockPaneStripNG.WndProc(Message& m) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Tabs\DockPaneStripNG.cs:line 1409
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Environment
OS: Microsoft Windows NT 10.0.17763.0
mRemoteNG Version: 1.77.1.27654
Edition: MSI
Cmd line args: 

```

**Comment by farosch** [comment]
Closed for voidnes
