### ISSUE TITLE
Gecko not runs

### ISSUE THREAD

**Issue by JaRaBcN** [mRemoteNG/mRemoteNG#1702]
When check components, it's showing OK. But if I click over refresh appears that error, showing traces to search files to C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Window\ComponentsCheckWindow.cs and D:\temp\339b193\Geckofx-Core, that paths not exists on my computer.

```
Exception Message
"Unable to load DLL 'mozglue': The specified module could not be found. (Exception from HRESULT: 0x8007007E)"

Stack trace
   at Gecko.Xpcom.Alloc(IntPtr size)
   at Gecko.nsAString..ctor() in D:\temp\339b193\Geckofx-Core\nsString.cs:line 883
   at Gecko.nsAString..ctor(String value) in D:\temp\339b193\Geckofx-Core\nsString.cs:line 895
   at Gecko.Xpcom.Initialize(String binDirectory) in D:\temp\339b193\Geckofx-Core\Xpcom.cs:line 324
   at mRemoteNG.UI.Window.ComponentsCheckWindow.CheckGeckoBrowser() in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Window\ComponentsCheckWindow.cs:line 707
   at mRemoteNG.UI.Window.ComponentsCheckWindow.CheckComponents() in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Window\ComponentsCheckWindow.cs:line 547
   at mRemoteNG.UI.Window.ComponentsCheckWindow.btnCheckAgain_Click(Object sender, EventArgs e) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Window\ComponentsCheckWindow.cs:line 516
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Environment
OS: Microsoft Windows NT 10.0.18363.0
mRemoteNG Version: 1.77.1.27654
Edition: MSI
Cmd line args: 

```

## Expected Behavior

Open the URL when use Gecko.

## Current Behavior

Not opens nothing. Selecting IE is open correctly.

## Possible Solution

Correct the paths?

## Steps to Reproduce (for bugs)

Select Gecko --> No opens nothing
Check components, click on refresh, show the above error.

1.
2.
3.
4.

## Your Environment

* Version used: 1.77.1.27654 - MSI
<img width="379" alt="Error mremoteNG" src="https://user-images.githubusercontent.com/6543090/75345701-856f6000-589d-11ea-8cf6-41b7b81ed9c2.png">

* Operating System and version (e.g. Windows 10 1709 x64): Microsoft Windows 10 1909 x64

**Comment by createthisnl** [comment]
Installing "Update for Visual C++ 2013 and Visual C++ Redistributable Package" fixed it for me. 
Downloaded it from this page:
https://support.microsoft.com/en-us/help/3179560/update-for-visual-c-2013-and-visual-c-redistributable-package

Please note this update is released as a download-only update and isn’t distributed through Windows Update.

**Comment by JaRaBcN** [comment]
It works!

Thank you!!

**Comment by WimDeGroote** [comment]
Indeed. It works!
