### ISSUE TITLE
exception throw when open connection 

### ISSUE THREAD

**Issue by long-nguyenxuan** [mRemoteNG/mRemoteNG#1778]
## Steps to Reproduce (for bugs)

1. double click on a connection (RDP) in left panel 

## Expected Behavior
connect to remote server 

## Current Behavior
mremoteng throw exception 

## Your Environment

```
Exception Message
"Unable to cast object of type 'mRemoteNG.Connection.ConnectionInfo' to type 'mRemoteNG.Connection.InterfaceControl'."

Stack trace
   at mRemoteNG.UI.Tabs.ConnectionTab.OnFormClosing(FormClosingEventArgs e)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Environment
OS: Microsoft Windows NT 10.0.17763.0
mRemoteNG Version: 1.77.1.27713
Edition: Portable
Cmd line args: 

```

**Comment by farosch** [comment]
This might be caused by the **very** outdated version of windows your running.
Please update your OS and try again.
That version of mRemote has been release since Sep 02, 2019. I think if nobody is able to use RDP we would have heard about it ;)
So chances are very high that it is not a problem of mrng itself but of your computer.

**Comment by long-nguyenxuan** [comment]
thanks for reply, I would update my OS Version and confirm if any other issue happen.
