### ISSUE TITLE
Specified argument was out of the range of valid values.

### ISSUE THREAD

**Issue by Laim** [mRemoteNG/mRemoteNG#1779]
When connecting to a server that is under a group/folder, occasionally it will throw the following error.

## Expected Behavior
Connect to server under group

## Current Behavior
Connection fails

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
1. Add server under group
2. Connect to server

Other method:
1. Add server under group
2. Connect to server while disconnecting from another

## Your Environment
Connections via SQL Server
```
Exception Message
"Specified argument was out of the range of valid values."

Stack trace
   at WeifenLuo.WinFormsUI.Docking.DockContentCollection.GetVisibleContent(Int32 index)
   at WeifenLuo.WinFormsUI.Docking.DockContentCollection.get_Item(Int32 index)
   at WeifenLuo.WinFormsUI.Docking.DockPaneStripBase.TabCollection.get_Item(Int32 index)
   at WeifenLuo.WinFormsUI.Docking.DockPaneStripBase.SelectClosestPane(Int32 index)
   at WeifenLuo.WinFormsUI.Docking.DockPaneStripBase.TryCloseTab(Int32 index)
   at mRemoteNG.UI.Tabs.DockPaneStripNG.TabCloseButtonHit(Int32 index) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Tabs\DockPaneStripNG.cs:line 1166
   at mRemoteNG.UI.Tabs.DockPaneStripNG.OnMouseClick(MouseEventArgs e) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Tabs\DockPaneStripNG.cs:line 1158
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at WeifenLuo.WinFormsUI.Docking.DockPaneStripBase.WndProc(Message& m)
   at mRemoteNG.UI.Tabs.DockPaneStripNG.WndProc(Message& m) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Tabs\DockPaneStripNG.cs:line 1409
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Environment
OS: Microsoft Windows NT 10.0.18363.0
mRemoteNG Version: 1.77.0.41252
Edition: MSI
Cmd line args: 

```

**Comment by farosch** [comment]
You are running an **extremely** outdated version of a **development build** of mrng!
Please update to the latest version and file a new issue if the problem still exists.
