### ISSUE TITLE
After Windows 10 May 2020 Update, it does not open anymore

### ISSUE THREAD

**Issue by gdufourc** [mRemoteNG/mRemoteNG#1787]
After Microsoft applied the mandatory Windows 10 May 2020 Update, it does not open anymore
The application raise 3 errors in the windows eventlog, each time I try to open it, that are:

```
**.NET RUNTIME ERROR**
Application: mRemoteNG.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Xml.XmlException
   at System.Xml.XmlTextReaderImpl.Throw(System.Exception)
   at System.Xml.XmlTextReaderImpl.Throw(System.String, System.String[])
   at System.Xml.XmlTextReaderImpl.ParseText(Int32 ByRef, Int32 ByRef, Int32 ByRef)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlTextReaderImpl.Skip()
   at System.Xml.XmlTextReader.Skip()
   at System.Configuration.XmlUtil.StrictSkipToNextElement(System.Configuration.ExceptionAction)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   at System.Configuration.BaseConfigurationRecord.ScanSections(System.Configuration.XmlUtil)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(System.Configuration.ConfigurationSchemaErrors)
   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs)

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs)
   at System.Configuration.Internal.InternalConfigRoot.OnConfigRemoved(System.Configuration.Internal.InternalConfigEventArgs)
   at System.Configuration.Internal.InternalConfigRoot.RemoveConfigImpl(System.String, System.Configuration.BaseConfigurationRecord)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(System.String, Boolean, Boolean, Boolean, Boolean, System.Object ByRef, System.Object ByRef)
   at System.Configuration.BaseConfigurationRecord.GetSection(System.String)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(System.String)
   at System.Configuration.ConfigurationManager.GetSection(System.String)
   at System.Configuration.ClientSettingsStore.ReadSettings(System.String, Boolean)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(System.Configuration.SettingsContext, System.Configuration.SettingsPropertyCollection)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(System.Configuration.SettingsProvider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(System.String)
   at System.Configuration.SettingsBase.get_Item(System.String)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(System.String)
   at System.Configuration.ApplicationSettingsBase.get_Item(System.String)
   at mRemoteNG.Settings.get_SingleInstance()
   at mRemoteNG.App.ProgramRoot.Main(System.String[])
-------------------------------------------------------------------------------------------
**Application Error**
Faulting application name: mRemoteNG.exe, version: 1.76.20.24615, time stamp: 0x5cb09552
Faulting module name: KERNELBASE.dll, version: 10.0.18362.815, time stamp: 0x67005c2a
Exception code: 0xe0434352
Fault offset: 0x00114402
Faulting process id: 0x382c
Faulting application start time: 0x01d640201b56543a
Faulting application path: C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: dbcdd7a9-65c1-4314-a0f4-7b132ef05337
Faulting package full name: 
Faulting package-relative application ID: 
-------------------------------------------------------------------------------------------
**Information: Windows Error Reporting**
Fault bucket 1713025841022344044, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: mRemoteNG.exe
P2: 1.76.20.24615
P3: 5cb09552
P4: System.Xml
P5: 4.8.3752.0
P6: 5c7a2412
P7: b85
P8: 27
P9: IOIBMURHYNRXKW0ZXKYRVFN0BOYYUFOW
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7801.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER789F.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER78AF.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER78BD.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER790C.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_mRemoteNG.exe_ccf9f1be4a9c46bc3c28a8c42796fa162261d1_994caac1_cce6d3bb-820e-4aa7-83d1-46bd6d08fc4f

Analysis symbol: 
Rechecking for solution: 0
Report Id: dbcdd7a9-65c1-4314-a0f4-7b132ef05337
Report Status: 268435456
Hashed bucket: 8a378efa195a6e2457c5e3ed29339b6c
```
-------------------------------------------------------------------------------------------
Additionally, I tried installing the Prerelease v1.77.1 application, but when I run it, it asks me for a password I don't know which is

So finally, I was not able to execute mRemoteNG after the last Microsoft Windows 10 May 2020 upgrade

Regards!
Guillermo

**Comment by farosch** [comment]
@gdufourc Looks like your connections file was somehow corrupted.

**Comment by nmat** [comment]
I have tested to start mremoteng on 2004 and it works for me with no problems at all. Need a bit more information here I think

**Comment by pjfrutuoso** [comment]
I had the same error after Windows update.
The only way was to install version Prerelease 1.77.1.

About asking you for a password when you run mRemote, it happened to me some time ago.
Go to your %appdata%/Roaming/mRemoteNG folder , see if you have any ConfCons.xml backup and open any of the most recent files.

**Comment by farosch** [comment]
@gdufourc Were you also using v1.76?
@gdufourc @pjfrutuoso Was mRemoteNG running, when you ran the Windows update?

**Comment by pjfrutuoso** [comment]
@farosch yes.

**Comment by farosch** [comment]
I have the following theory:
If mRemoteNG was running during the upgrade it could be, that Windows at some point sent a terminate signal to every application.
If mRemoteNG was too slow to save the xml file before Windows sends the term signal it might leave you with a corrupted config file.

Though this is just an unverified idea at this point. Will have to take a closer look at the source code to verify this.

**Comment by pjfrutuoso** [comment]
@farosch in that theory, if you unistall mRemote, delete the appdata folder, and install it again it with no config files previously created shouldn't run normally?

**Comment by gdufourc** [comment]
> @gdufourc Were you also using v1.76?
@farosch, the version was 1.76.20.24669
The problem was that the configuration file was corrupted, so I restored a recent configuration file backup, and the application start correctly.
I guess that it would be very usefull to show an alert saying that the config has not the correct format, when it can't be read successfully
Regards!

**Comment by rustyjarz** [comment]
I have the same problem, after a windows crash I can't open mRemoteNG any longer. I've uninstalled/reinstalled, renamed the %appdata%/Roaming/mRemoteNG folder and reinstalled, the folder wan't recreated and still unable to open. I'm on the 2004 update too.

**Comment by farosch** [comment]
@rustyjarz 
Have you tried [this](https://mremoteng.readthedocs.io/en/latest/troubleshooting.html#recovering-corrupted-connections-file)?
There should be no need to roll back your windows version.
This error clearlky comes from the XMNL parser and is an indication for a corrupted configuration file.
You can also copy the content of your connections file to some site like https://www.xmlvalidation.com/?L=2 to see if it has any syntax errors.

**Comment by aney1** [comment]
I have the same issue after Windows installed an update for the Flash Player on 1909 (KB4561600).
Uninstalling mRemoteNG and deleting the folder in AppData\Roaming and reinstalling the app doesn't help.
The folder in AppData is not created when launching mRemoteNG. It just silently fails and I get the same log entry like gdufourc. Seems like after that update mRemoteNG forgot where its config file is located?

**Comment by farosch** [comment]
> I guess that it would be very usefull to show an alert saying that the config has not the correct format, when it can't be read successfully

@gdufourc Will do!

**Comment by rustyjarz** [comment]
> @rustyjarz
> Have you tried [this](https://mremoteng.readthedocs.io/en/latest/troubleshooting.html#recovering-corrupted-connections-file)?
> There should be no need to roll back your windows version.
> This error clearly comes from the XML parser and is an indication of a corrupted configuration file.
> You can also copy the content of your connections file to some site like https://www.xmlvalidation.com/?L=2 to see if it has any syntax errors.

Hi,

As mentioned I uninstalled, renamed the mRemoteNG folder in my user profile, but after re-install the folder is not re-created.

I didn't rol-back the 2004 update because of mRemoteNG I rolled back because the update is shit and breaks lot's of stuff!

**Comment by nmat** [comment]
I am on 2004 update and I am using the 1.76 version.

- Removed the roaming, local and other files in the APPDATA directory - started mremoteng and they are recreated
- Upgraded to version 1.77.1 using msi file - Tried starting application with no problem
- Also removed the data files for APPDATA one by one and they are recreated on startup

Windows 10 version: 2004 (OS Build 19041.329)

**Log output:**
mRemoteNG 1.77.1.27654 starting.
Command Line: C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe
Microsoft Windows 10 Pro  64-bit
Microsoft .NET CLR 4.0.30319.42000
System Culture: en-US/English (United States)

**Comment by biglanzi** [comment]
I occured this problem a few days ago when I poweroff my pc forcely.
I cannot start mRemteNg any more,and finnaly I resolved it with deleting  the AppData/Local/mRemoteNg and Appdata/Roaming/mRemoteNg folder ,reinstall mRemoteNg,now It works again

**Comment by TheTram** [comment]
Thank you for the thread, was able to get it working with Biglanzi method.

**Comment by CallumCarmicheal** [comment]
For those who are having this issue, I narrowed it down to corrupt user configuration files.

Check the following files and if they are corrupt either delete them or attempt to recovery parts of them:
`%localappdata%\mRemoteNG\` `mRemoteNG.exe_Url_{version_hash}\{version}\user.config`
`%appdata%\mRemoteNG\` - Any xml files in here.
`{install_dir}\mRemoteNG.settings`
`{install_dir}\mRemoteNG.exe.config`

I would advise you to rename the folder and let mRemoteNG regenerate the files and copy a backup file back into `%appdata%\mRemoteNG\`  once the application re-opens.

----
Walkthrough to find what file is corrupted if you still cannot get it working:

If you still have this issue, Download `dnSpy` and launch `dnSpy-x86.exe`, drag in mRemoteNG.exe and click on it in the explorer panel. Press Start at the top of the screen and wait until the `ConfigurationErrorsException` exception is thrown and press OK. 

This will now leave you in a debugger context, at the bottom in the `Locals` window click on `$exception` and find `_innerException` click on that again, there should be a variable saying `_firstFilename`, this is the location to the file that is corrupted. Right click copy and paste it into a notepad where you can copy the folder path and paste it into windows explorer. Now either rename the file and manually copy what parts are fine or just delete it and mRemoteNG will recreate it. If the file is `confCons.xml` open up the .backup files until you find one that is not corrupt and copy that for later. Delete or rename the file and then launch mRemoteNG. 
If it now crashes again, repeat this process. 
If it works, take a not of what was corrupt so you know what settings are missing and will need reconfigured.

I'm linking some other issues to link back to this one as they are all the same errors: 
#1816 #1695 #1573 #1478 #707 #645

**Comment by Kvarkas** [comment]
not relevant to new version
