### ISSUE TITLE
Mremote Crash when closing a tab

### ISSUE THREAD

**Issue by oznxzar** [mRemoteNG/mRemoteNG#1794]
## Expected Behavior
Sometimen when I close a tab that contains some open connections inside mremote crash and i need to close it a reset when it shouldn't.

As you can see in the error windows something is pointing to path "C:\jenkins\workspace\Publish\Build" that don't exists in my setup

Error Message:

![image](https://user-images.githubusercontent.com/44467849/84734789-1cbe0780-afa2-11ea-9bf9-e67b7c093b4f.png)

Full infortmation from error message below:

```
Exception Message
"No se puede obtener acceso al objeto desechado.
Nombre del objeto: 'ConnectionWindow'."

Stack trace
   en System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   en System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   en System.Windows.Forms.Control.Invoke(Delegate method)
   en mRemoteNG.UI.Window.ConnectionWindow.Prot_Event_Closed(Object sender) en C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Window\ConnectionWindow.cs:línea 802
   en mRemoteNG.Connection.Protocol.ProtocolBase.ClosedEventHandler.Invoke(Object sender)
   en mRemoteNG.Connection.Protocol.ProtocolBase.CloseBG() en C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Connection\Protocol\ProtocolBase.cs:línea 154
   en System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   en System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   en System.Threading.ThreadHelper.ThreadStart()

Environment
OS: Microsoft Windows NT 10.0.18363.0
mRemoteNG Version: 1.77.1.27654
Edition: MSI
Cmd line args: 
``

**Comment by NyvenZA** [comment]
Reproduced with a test tab containing a CEF Browser tab. 

Clicking the close button on the "General" Tab
![image](https://user-images.githubusercontent.com/64709994/84872312-04bdb500-b082-11ea-9b47-af041a7fe8fe.png)

```
Exception Message
"Cannot access a disposed object.
Object name: 'ConnectionWindow'."

Stack trace
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Delegate method)
   at mRemoteNG.UI.Window.ConnectionWindow.Prot_Event_Closed(Object sender) in C:\Users\USER\Documents\GitHub\mRemoteNG\mRemoteNG\UI\Window\ConnectionWindow.cs:line 803
   at mRemoteNG.Connection.Protocol.ProtocolBase.ClosedEventHandler.Invoke(Object sender)
   at mRemoteNG.Connection.Protocol.ProtocolBase.CloseBG() in C:\Users\USER\Documents\GitHub\mRemoteNG\mRemoteNG\Connection\Protocol\ProtocolBase.cs:line 155
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Environment
OS: Microsoft Windows NT 10.0.18363.0
mRemoteNG Version: 1.77.1.17188
Edition: Portable
Cmd line args: 

```

**Comment by farosch** [comment]
i couldn't reproduce this but added a check that might fix this issue.
can anybody confirm this?

**Comment by oznxzar** [comment]
I will check it tomorrow so I will provide feedback about that issue.

**Comment by oznxzar** [comment]
Hi @farosch , How can I apply the fix you mention? I can't find this file in my mremoteNG Install, if you can provide a new installer or telle how can i check it i will do it.

**Comment by farosch** [comment]
@oznxzar You can grad the lastest build from Appveyor: https://ci.appveyor.com/project/mremoteng/mremoteng/builds/33630769/job/rcjjfr03bn5u8kkt/artifacts

**Comment by david-hale** [comment]
I grabbed latest build from link above.  Looks like its still happening.
![issue_1794](https://user-images.githubusercontent.com/46064123/85230416-c4717600-b3a4-11ea-9f98-f86a05dad70e.gif)

**Comment by NyvenZA** [comment]
Could simulate as above, with the first tabs opening and closing without a crash, but when I open and close second tab, it crashes. 

```
Exception Message
"Cannot access a disposed object.
Object name: 'ConnectionWindow'."

Stack trace
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Delegate method)
   at mRemoteNG.UI.Window.ConnectionWindow.Prot_Event_Closed(Object sender) in C:\Users\USER\Documents\GitHub\mRemoteNG\mRemoteNG\UI\Window\ConnectionWindow.cs:line 803
   at mRemoteNG.Connection.Protocol.ProtocolBase.ClosedEventHandler.Invoke(Object sender)
   at mRemoteNG.Connection.Protocol.ProtocolBase.CloseBG() in C:\Users\USER\Documents\GitHub\mRemoteNG\mRemoteNG\Connection\Protocol\ProtocolBase.cs:line 155
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Environment
OS: Microsoft Windows NT 10.0.18363.0
mRemoteNG Version: 1.77.1.18774
Edition: Portable
Cmd line args: 

```

**Comment by robertpopa22** [comment]
**Fix available for testing**

A fix for this issue has been implemented in our community fork (`robertpopa22/mRemoteNG`, branch `main`). A beta build including this fix is available from the fork's Releases page.

Please test and report if this resolves your issue.

---

> *We sincerely appreciate the mRemoteNG maintainers and the wonderful community that has kept this project alive and thriving for over a decade. Your work powers thousands of IT professionals worldwide, including us. Our fork builds entirely on your foundation — we're preparing a consolidated Pull Request to contribute these improvements back to the official project. Thank you for everything you've built.*
>
> *— robertpopa22, community contributor*
