### ISSUE TITLE
An unhandled exception has occurred

### ISSUE THREAD

**Issue by klngh** [mRemoteNG/mRemoteNG#1822]
This exception will force mRemoteNG to close. Cannot access a disposed object. Object name: 'ConnectionWindow'.

## Expected Behavior
Reporting a bug. When closing a saved SSH connection window, the window should close.

## Current Behavior
When closing a saved SSH connection window, an unhandled exception has occurred window pops up and force closes mRemoteNG. See error below:

   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Delegate method)
   at mRemoteNG.UI.Window.ConnectionWindow.Prot_Event_Closed(Object sender) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Window\ConnectionWindow.cs:line 802
   at mRemoteNG.Connection.Protocol.ProtocolBase.ClosedEventHandler.Invoke(Object sender)
   at mRemoteNG.Connection.Protocol.ProtocolBase.CloseBG() in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Connection\Protocol\ProtocolBase.cs:line 154
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

OS: Microsoft Windows NT 10.0.19041.0
mRemoteNG Version: 1.77.1.27654
Edition: MSI
Cmd line args: 

## Possible Solution
Bug does not exist in 1.76.11.40527 version.

## Steps to Reproduce (for bugs)
1. Create a new connection in mRemoteNG Version: 1.77.1.27654
2. Change the protocol to SSH version 2.
3. Use Default Settings for the PuTTY Session.
4. Enter a hostname or IP of a server that has SSH running.
5. Connection to this server.
6. Close the General Panel Tab.
7. Note: The error does not occur when closing the Server Tab first, followed by the General Panel Tab.

## Context
Application constantly crashes when closing these tabs. The stable version (1.76.11.40527) does not have all the features I make use and I would prefer to report this bug so that it can be address in a future release.

## Your Environment
OS: Microsoft Windows NT 10.0.19041.0 (Version 2004 - 19041.388)
mRemoteNG Version: 1.77.1.27654
Edition: MSI
Cmd line args:

**Comment by kmscode** [comment]
I was able to reproduce this

```
Exception Message
"Cannot access a disposed object.
Object name: 'ConnectionWindow'."

Stack trace
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Delegate method)
   at mRemoteNG.UI.Window.ConnectionWindow.Prot_Event_Closed(Object sender)
   at mRemoteNG.Connection.Protocol.ProtocolBase.ClosedEventHandler.Invoke(Object sender)
   at mRemoteNG.Connection.Protocol.ProtocolBase.CloseBG()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Environment
OS: Microsoft Windows NT 10.0.19043.0
mRemoteNG Version: 1.77.2.40538
Edition: Portable
Cmd line args: 

```

**Comment by robertpopa22** [comment]
Triage refresh (P4 version-label debt): this issue is tagged with legacy version labels. Please retest on the latest build (fork v1.79.x or upstream dev), then share reproducible steps and expected vs actual behavior. If still valid, keep open and relabel to current triage scope (for example Need 2 check). If fixed, close with resolution.

Current legacy version labels: 1.77.2

**Comment by robertpopa22** [comment]
**Fix available for testing**

A fix for this issue has been implemented in our community fork (`robertpopa22/mRemoteNG`, branch `main`). A beta build including this fix is available from the fork's Releases page.

Please test and report if this resolves your issue.

---

> *We sincerely appreciate the mRemoteNG maintainers and the wonderful community that has kept this project alive and thriving for over a decade. Your work powers thousands of IT professionals worldwide, including us. Our fork builds entirely on your foundation — we're preparing a consolidated Pull Request to contribute these improvements back to the official project. Thank you for everything you've built.*
>
> *— robertpopa22, community contributor*
