### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by cumt673** [mRemoteNG/mRemoteNG#1839]
Object reference not set to an instance of an object.

## Expected Behavior

When I click the software, it shows an unhandled exception has occurred.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

at mRemoteNG.App.Update.UpdateInfo.CheckIfValid() in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\App\Update\UpdateInfo.cs:line 53
   at mRemoteNG.App.Update.UpdateInfo.FromString(String input) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\App\Update\UpdateInfo.cs:line 45
   at mRemoteNG.App.Update.AppUpdater.GetUpdateInfo() in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\App\Update\AppUpdater.cs:line 247
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
## Your Environment

* Version used:mRemoteNG Version: 1.77.0.41252
* Operating System and version (e.g. Windows 10 1709 x64):Microsoft Windows NT 10.0.16299.0

**Comment by Kvarkas** [comment]
Not supported version anymore
