### ISSUE TITLE
Crash log

### ISSUE THREAD

**Issue by gianmaxfactor** [mRemoteNG/mRemoteNG#1927]
```
Exception Message
"Object reference not set to an instance of an object."

Stack trace
   at mRemoteNG.UI.Tabs.DockPaneStripNG.get_ButtonOverflow()
   at mRemoteNG.UI.Tabs.DockPaneStripNG.SetInertButtons()
   at mRemoteNG.UI.Tabs.DockPaneStripNG.OnRefreshChanges()
   at WeifenLuo.WinFormsUI.Docking.DockPaneStripBase.RefreshChanges()
   at WeifenLuo.WinFormsUI.Docking.DockPane.RefreshChanges(Boolean performLayout)
   at WeifenLuo.WinFormsUI.Docking.DockPane.RefreshChanges()
   at WeifenLuo.WinFormsUI.Docking.DockContentHandler.SetDockState(Boolean isHidden, DockState visibleState, DockPane oldPane)
   at WeifenLuo.WinFormsUI.Docking.DockContentHandler.set_DockState(DockState value)
   at WeifenLuo.WinFormsUI.Docking.DockContentHandler.Show(DockPanel dockPanel, DockState dockState)
   at WeifenLuo.WinFormsUI.Docking.DockContentHandler.Show(DockPanel dockPanel)
   at WeifenLuo.WinFormsUI.Docking.DockContent.Show(DockPanel dockPanel)
   at mRemoteNG.UI.Menu.ViewMenu.mMenViewConnections_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Environment
OS: Microsoft Windows NT 10.0.18363.0
mRemoteNG Version: 1.77.0.41307
Edition: Portable
Cmd line args: 

```

**Comment by Kvarkas** [comment]
cant reproduce in NB, perhaps has been fixed
