### ISSUE TITLE
.Net Errors with mRemoteNG

### ISSUE THREAD

**Issue by RADjheisler** [mRemoteNG/mRemoteNG#1932]
First off - Love this software.
Now, with that out the way, I'm getting .NET Errors with the program. I realize this may not be an mRemoteNG issue specifically, but its the only program I use that does this so I thought maybe someone else may have encountered similar issues.

## Current Behavior
So, what happens is, when I try to start the program, my cursor gets the spinning loading wheel for 2-3 seconds and then mRemoteNG doesn't open. A quick peak at my event viewer shows a .NET Runtime error

## Possible Solution
Fixes I've Tried:
- sfc /scannow
- Run as Admin
- Uninstall/Reinstall like 4-5 times now
- Install into non "_Program File_" Folders _(Ex. C:\Tools\mRemoteNG)_
- - This would ask me for a password. But I'm not sure what password.
- .NET Repair Tool
- Turn .NET Features Off then On
- Restarted the PC

## Steps to Reproduce
1. Run mRemoteNG
2. Then it wouldn't start
3. Open Event Viewer
4. See .NET Runtime Error
5. Cry

## Your Environment
* mRemoteNG Version used: v1.76.20
* .NET Runtime: v4.0.30319
* Operating System and version: Windows 10 Enterprise 2004 (19041.804)

Big thanks to anyone offering suggestions!
Like I said, really love this software and just want to be able to use it again.

![image](https://user-images.githubusercontent.com/78984538/107825853-d946b380-6d51-11eb-977d-f4d7842204d2.png)
![image](https://user-images.githubusercontent.com/78984538/107825891-ea8fc000-6d51-11eb-9fbd-07a529f37135.png)

**Comment by Barmp** [comment]
Same issue with .NET errors here, similar behavior (app crashes when connecting to VNC session) and I've just installed and started using the app. Appears to be a different error, might be helpful for context / debugging.

Log Name:      Application
Source:        .NET Runtime
Date:          2/12/2021 3:54:59 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-xxx
Description:
Application: mRemoteNG.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at VncSharp.Encodings.EncodedRectangle.Draw(System.Drawing.Bitmap)
   at VncSharp.RemoteDesktop.VncUpdate(System.Object, VncSharp.VncEventArgs)

Exception Info: System.Reflection.TargetInvocationException
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
   at System.Delegate.DynamicInvokeImpl(System.Object[])
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.ScrollableControl.WndProc(System.Windows.Forms.Message ByRef)
   at VncSharp.RemoteDesktop.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.OnMessage(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG ByRef)
   at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application.Run(System.Windows.Forms.Form)
   at mRemoteNG.App.ProgramRoot.StartApplication()
   at mRemoteNG.App.ProgramRoot.Main(System.String[])

**Comment by VShawn** [comment]
@Barmp it seems like the error of VncSharp, a new ticket is needed, maybe. 

Since VncSharp was archived for 3 years, I think it is better to use XRDP to access Linux desktop.

@RADjheisler 
You can try my app before they fix the error : )
https://github.com/VShawn/PRemoteM

**Comment by FlikFlok** [comment]
Hello,

I had the same issue, and managed to solve it this way : 

1/ I downloaded and installed the prerelease version (v1.77.0). It then asked me to enter a password. None of mine were working and then I had an error message prompting pointing to a conf file in %LOCALAPPDATA%\..\Roaming\mRemoteNG

2/ I then uninstalled mRemoteNG and deleted those two directories : 
    - %LOCALAPPDATA%\..\Roaming\mRemoteNG
    - %LOCALAPPDATA%\mRemoteNG

3/ Reinstall Stable version (v1.76.20)

As well, my computer was fully up to date (Windows 10 v20H2, with all .NET Fx updates)

I hope it will help !

**Comment by RADjheisler** [comment]
> Hello,
> 
> I had the same issue, and managed to solve it this way :
> 
> 1/ I downloaded and installed the prerelease version (v1.77.0). It then asked me to enter a password. None of mine were working and then I had an error message prompting pointing to a conf file in %LOCALAPPDATA%..\Roaming\mRemoteNG
> 
> 2/ I then uninstalled mRemoteNG and deleted those two directories :
> - %LOCALAPPDATA%..\Roaming\mRemoteNG
> - %LOCALAPPDATA%\mRemoteNG
> 
> 3/ Reinstall Stable version (v1.76.20)
> 
> As well, my computer was fully up to date (Windows 10 v20H2, with all .NET Fx updates)
> 
> I hope it will help !

THANK YOU THANK YOU THANK YOU!!!

mRmoteNG hasn't worked for me for over 6 months. This was the solution. You are a true hero my friend.
