### ISSUE TITLE
unhandled exception on launching

### ISSUE THREAD

**Issue by LeeOliver24** [mRemoteNG/mRemoteNG#1937]
Attempting to open mRemoteNG:-

An item with the same key has already been added.

at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at mRemoteNG.App.Update.UpdateFile.FromString(String content) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\App\Update\UpdateFile.cs:line 57
   at mRemoteNG.App.Update.UpdateFile..ctor(String content) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\App\Update\UpdateFile.cs:line 22
   at mRemoteNG.App.Update.UpdateInfo.FromString(String input) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\App\Update\UpdateInfo.cs:line 32
   at mRemoteNG.App.Update.AppUpdater.GetUpdateInfo() in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\App\Update\AppUpdater.cs:line 247
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

OS: Microsoft Windows NT 10.0.17763.0
mRemoteNG Version: 1.77.0.41252
Edition: MSI
Cmd line args:

**Comment by AlexMhr** [comment]
Happened to me today as well, something failing with the update check (possible bad/no response from update site?).
In case it helps anyone, you can work around it by opening mRemoteNG.settings and disabling it:
`<setting name="CheckForUpdatesOnStartup">False</setting>`

**Comment by crayfishuk** [comment]
Yep - I get the same thing today too. I'm guessing a) something's offline, and/or b) the handling of this isn't as eloquent as it could be...

**Comment by PecceG2** [comment]
It seems to be an issue related to the website currently under maintenance, checking I see traffic going to the mremoteng.org dns and then milliseconds after starting to receive response data the program crashes.

![image](https://github.com/mRemoteNG/mRemoteNG/assets/31479677/ce9ce6d9-7f19-4cca-96d6-0b480b355352)


Probably, as @crayfishuk indicates, there is not good exception handling in case the site is down.

Disable automatic updates temporarily fixes this issue.

**Comment by simonai1254** [comment]
Linking this to #2541...

**Comment by Kvarkas** [comment]
> Yep - I get the same thing today too. I'm guessing a) something's offline, and/or b) the handling of this isn't as eloquent as it could be...

We need to move domain to new hoster, its takes up to 24h, selected festive time for minimize impact, but wasn't expected it will hit what way :) sorry for such, at morning I believe it will be normalized.
