### ISSUE TITLE
Unhandled exception when changing theme colors

### ISSUE THREAD

**Issue by teddyross** [mRemoteNG/mRemoteNG#1955]
I changed a few colors in my theme, hit OK, and an unhandled exception occurred.

```
Exception Message
"Empty path name is not legal."

Stack trace
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at System.IO.File.ReadAllBytes(String path)
   at mRemoteNG.Themes.ThemeSerializer.UpdateThemeXMLValues(ThemeInfo themeToUpdate) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Themes\ThemeSerializer.cs:line 35
   at mRemoteNG.Themes.ThemeManager.updateTheme(ThemeInfo themeToUpdate) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Themes\ThemeManager.cs:line 263
   at mRemoteNG.UI.Forms.OptionsPages.ThemePage.SaveSettings() in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Forms\OptionsPages\ThemePage.cs:line 102
   at mRemoteNG.UI.Forms.FrmOptions.btnOK_Click(Object sender, EventArgs e) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Forms\FrmOptions.cs:line 128
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Steps to Reproduce 

1. Opened Tools > Options > Theme tab
2. Sorted by 'Element'
3. Made changes to List_background color, and changed the color of some other settings I don't remember
4. Pressed OK. Unhandled exception occurred.

## Your Environment
OS: Microsoft Windows NT 10.0.19042.0
mRemoteNG Version: 1.77.1.27654
Edition: MSI
Cmd line args:

**Comment by robertpopa22** [comment]
"%MSG%"

**Comment by robertpopa22** [comment]
**Fix available for testing**

A fix for this issue has been implemented in our community fork (`robertpopa22/mRemoteNG`, branch `main`). A beta build including this fix is available from the fork's Releases page.

Please test and report if this resolves your issue.

---

> *We sincerely appreciate the mRemoteNG maintainers and the wonderful community that has kept this project alive and thriving for over a decade. Your work powers thousands of IT professionals worldwide, including us. Our fork builds entirely on your foundation — we're preparing a consolidated Pull Request to contribute these improvements back to the official project. Thank you for everything you've built.*
>
> *— robertpopa22, community contributor*
