### ISSUE TITLE
Invalid Value: The value of DockAreas conflicts with current DockState.

### ISSUE THREAD

**Issue by raphaperizzato** [mRemoteNG/mRemoteNG#1956]
Can't see the default view. When I click on View > Reset layout:

Execption message: Invalid Value: The value of DockAreas conflicts with current DockState.

Stack trace:  at WeifenLuo.WinFormsUI.Docking.DockContentHandler.set_DockAreas(DockAreas value)
   at WeifenLuo.WinFormsUI.Docking.DockContent.set_DockAreas(DockAreas value)
   at mRemoteNG.UI.Forms.FrmMain.SetDefaultLayout() in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Forms\FrmMain.cs:line 696
   at mRemoteNG.UI.Menu.ViewMenu.mMenViewResetLayout_Click(Object sender, EventArgs e) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Menu\ViewMenu.cs:line 357
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Environment: OS: Microsoft Windows NT 10.0.17763.0
mRemoteNG Version: 1.77.0.41252
Edition: MSI
Cmd line args:

**Comment by farosch** [comment]
Closing as v.1.77.0 is way outdated and never was a stable release.
Issue is probably already fixed.
