### ISSUE TITLE
An unhandled exception has occurred

### ISSUE THREAD

**Issue by iamsixxxx** [mRemoteNG/mRemoteNG#1964]
Cannot access a disposed object.
Object name: 'ConnectionWindow'.

   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Delegate method)
   at mRemoteNG.UI.Window.ConnectionWindow.Prot_Event_Closed(Object sender) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Window\ConnectionWindow.cs:line 802
   at mRemoteNG.Connection.Protocol.ProtocolBase.ClosedEventHandler.Invoke(Object sender)
   at mRemoteNG.Connection.Protocol.ProtocolBase.CloseBG() in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Connection\Protocol\ProtocolBase.cs:line 152
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

OS: Microsoft Windows NT 10.0.19042.0
mRemoteNG Version: 1.77.0.41252
Edition: MSI
Cmd line args:

**Comment by farosch** [comment]
@iamsixxxx You are running an outdated prerelease.
Please update to 1.77.1. I think your issue might already be resolved in this version.

**Comment by blasphemite** [comment]
Received the same error on v1.77.2.41427 when closing connection panel with active connections.

```
Exception Message
"Cannot access a disposed object.
Object name: 'ConnectionWindow'."

Stack trace
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Delegate method)
   at mRemoteNG.UI.Window.ConnectionWindow.Prot_Event_Closed(Object sender) in D:\Work\mRemoteNG\Branch Dev\mRemoteNG\UI\Window\ConnectionWindow.cs:line 803
   at mRemoteNG.Connection.Protocol.ProtocolBase.ClosedEventHandler.Invoke(Object sender)
   at mRemoteNG.Connection.Protocol.ProtocolBase.CloseBG() in D:\Work\mRemoteNG\Branch Dev\mRemoteNG\Connection\Protocol\ProtocolBase.cs:line 155
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Environment
OS: Microsoft Windows NT 10.0.19042.0
mRemoteNG Version: 1.77.2.41427
Edition: MSI
Cmd line args: 

```

**Comment by Russssty** [comment]
The same here on 1.77.2.41427

It happens when closing a panel containing at least one active ssh or telnet connection. 
The panels with RDP only are working fine.

**Comment by simonai1254** [comment]
> It happens when closing a panel containing at least one active ssh or telnet connection.
> The panels with RDP only are working fine.

Funny thing is that I just got a similar unhandled exception, but with RDP... (see #2118)

**Comment by Kvarkas** [comment]
cant reproduce
