### ISSUE TITLE
Column 'Domain' does not belong to table .

### ISSUE THREAD

**Issue by SanderGit** [mRemoteNG/mRemoteNG#1977]
## Expected Behavior
Updated from 1.77.1 to 1.77.2 nightly. This loses the settings.

## Current Behavior
Connect to the 1.77.1 SQL database (MSSQL)

Error: An unhandled exception has occurred
Exception Message: Column 'Domain' does not belong to table .

## Steps to Reproduce (for bugs)
1. Update mRemoteNG to 1.77.2 nightly
2. Open it
3. Configure MSSQL connection

## Context
Try to get my connections back

## Your Environment
Windows Server 2012R2, SQL Server 2014
OS: Microsoft Windows NT 6.3.9600.0
mRemoteNG Version: 1.77.2.28860
Edition: MSI
Cmd line args:

Detailed stack trace:
```
   at System.Data.DataRow.GetDataColumn(String columnName)
   at System.Data.DataRow.get_Item(String columnName)
   at mRemoteNG.Config.Serializers.ConnectionSerializers.MsSql.DataTableDeserializer.PopulateConnectionInfoFromDatarow(DataRow dataRow, ConnectionInfo connectionInfo) in D:\Work\mRemoteNG\Branch Dev\mRemoteNG\Config\Serializers\ConnectionSerializers\MsSql\DataTableDeserializer.cs:line 87
   at mRemoteNG.Config.Serializers.ConnectionSerializers.MsSql.DataTableDeserializer.DeserializeContainerInfo(DataRow row) in D:\Work\mRemoteNG\Branch Dev\mRemoteNG\Config\Serializers\ConnectionSerializers\MsSql\DataTableDeserializer.cs:line 71
   at mRemoteNG.Config.Serializers.ConnectionSerializers.MsSql.DataTableDeserializer.CreateNodesFromTable(DataTable table) in D:\Work\mRemoteNG\Branch Dev\mRemoteNG\Config\Serializers\ConnectionSerializers\MsSql\DataTableDeserializer.cs:line 51
   at mRemoteNG.Config.Serializers.ConnectionSerializers.MsSql.DataTableDeserializer.Deserialize(DataTable table) in D:\Work\mRemoteNG\Branch Dev\mRemoteNG\Config\Serializers\ConnectionSerializers\MsSql\DataTableDeserializer.cs:line 33
   at mRemoteNG.Config.Connections.SqlConnectionsLoader.Load() in D:\Work\mRemoteNG\Branch Dev\mRemoteNG\Config\Connections\SqlConnectionsLoader.cs:line 57
   at mRemoteNG.Connection.ConnectionsService.LoadConnections(Boolean useDatabase, Boolean import, String connectionFileName) in D:\Work\mRemoteNG\Branch Dev\mRemoteNG\Connection\ConnectionsService.cs:line 137
   at mRemoteNG.UI.Forms.OptionsPages.SqlServerPage.ReinitializeSqlUpdater() in D:\Work\mRemoteNG\Branch Dev\mRemoteNG\UI\Forms\OptionsPages\SqlServerPage.cs:line 83
   at mRemoteNG.UI.Forms.OptionsPages.SqlServerPage.SaveSettings() in D:\Work\mRemoteNG\Branch Dev\mRemoteNG\UI\Forms\OptionsPages\SqlServerPage.cs:line 73
   at mRemoteNG.UI.Forms.FrmOptions.BtnOK_Click(Object sender, EventArgs e) in D:\Work\mRemoteNG\Branch Dev\mRemoteNG\UI\Forms\FrmOptions.cs:line 132
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by theoneandonly-vector** [comment]
@SanderGit what did you do to fix the "Column 'VmId' does not belong to table"?

**Comment by theoneandonly-vector** [comment]
ok.. I just exported all my setting shten recreated th etable with the latest script and imported.

**Comment by robertpopa22** [comment]
Triage refresh (P4 version-label debt): this issue is tagged with legacy version labels. Please retest on the latest build (fork v1.79.x or upstream dev), then share reproducible steps and expected vs actual behavior. If still valid, keep open and relabel to current triage scope (for example Need 2 check). If fixed, close with resolution.

Current legacy version labels: 1.77.2

**Comment by robertpopa22** [comment]
**Fix available for testing**

A fix for this issue has been implemented in our community fork (`robertpopa22/mRemoteNG`, branch `main`). A beta build including this fix is available from the fork's Releases page.

Please test and report if this resolves your issue.

---

> *We sincerely appreciate the mRemoteNG maintainers and the wonderful community that has kept this project alive and thriving for over a decade. Your work powers thousands of IT professionals worldwide, including us. Our fork builds entirely on your foundation — we're preparing a consolidated Pull Request to contribute these improvements back to the official project. Thank you for everything you've built.*
>
> *— robertpopa22, community contributor*
