### ISSUE TITLE
Can`t connection to sql database

### ISSUE THREAD

**Issue by Traineratwot** [mRemoteNG/mRemoteNG#1986]
![screenshot](https://i.imgur.com/498FrcY.png)

I create Database by [wiki](https://mremoteng.readthedocs.io/en/latest/sql_configuration.html?highlight=sql),
enter my connection data,
and get that error

[dump my database without data](https://drive.google.com/file/d/1iyWfdB1rPdC1AawauG6V8Hz7Pw_bWy0t/view?usp=sharing)

`Unable to cast object of type 'System.DBNull' to type 'System.String'.`
```
   at mRemoteNG.Config.Serializers.MsSql.DataTableDeserializer.PopulateConnectionInfoFromDatarow(DataRow dataRow, ConnectionInfo connectionInfo) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\MsSql\DataTableDeserializer.cs:line 92
   at mRemoteNG.Config.Serializers.MsSql.DataTableDeserializer.DeserializeContainerInfo(DataRow row) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\MsSql\DataTableDeserializer.cs:line 73
   at mRemoteNG.Config.Serializers.MsSql.DataTableDeserializer.CreateNodesFromTable(DataTable table) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\MsSql\DataTableDeserializer.cs:line 53
   at mRemoteNG.Config.Serializers.MsSql.DataTableDeserializer.Deserialize(DataTable table) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\MsSql\DataTableDeserializer.cs:line 35
   at mRemoteNG.Config.Connections.SqlConnectionsLoader.Load() in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Connections\SqlConnectionsLoader.cs:line 57
   at mRemoteNG.Connection.ConnectionsService.LoadConnections(Boolean useDatabase, Boolean import, String connectionFileName) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Connection\ConnectionsService.cs:line 126
   at mRemoteNG.UI.Forms.OptionsPages.SqlServerPage.ReinitializeSqlUpdater() in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Forms\OptionsPages\SqlServerPage.cs:line 82
   at mRemoteNG.UI.Forms.OptionsPages.SqlServerPage.SaveSettings() in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Forms\OptionsPages\SqlServerPage.cs:line 72
   at mRemoteNG.UI.Forms.FrmOptions.btnOK_Click(Object sender, EventArgs e) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Forms\FrmOptions.cs:line 128
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

Operating System Windows 10 Pro 19042.1081

**Comment by Kvarkas** [comment]
Yes we know its an issue, could you try an nightly build ?

**Comment by Traineratwot** [comment]
I try nightly build.

It looks like I misunderstood what the problem is, apparently I have a wrongly created database
![https://i.imgur.com/nPW94iy.jpeg ](img)

Previously, I manually added columns without which I received an error

Where can I find an up-to-date one for the night build?
SQL query to create datatbase?

**Comment by Kvarkas** [comment]
working on that bit

**Comment by robertpopa22** [comment]
**Fix available for testing**

A fix for this issue has been implemented in our community fork (`robertpopa22/mRemoteNG`, branch `main`). A beta build including this fix is available from the fork's Releases page.

Please test and report if this resolves your issue.

---

> *We sincerely appreciate the mRemoteNG maintainers and the wonderful community that has kept this project alive and thriving for over a decade. Your work powers thousands of IT professionals worldwide, including us. Our fork builds entirely on your foundation — we're preparing a consolidated Pull Request to contribute these improvements back to the official project. Thank you for everything you've built.*
>
> *— robertpopa22, community contributor*
