### ISSUE TITLE
Unable to launch app

### ISSUE THREAD

**Issue by cheekychick** [mRemoteNG/mRemoteNG#2020]
Application has suddenly stopped launching for me.

I have tried an uninstall and reinstall, below are the errors in event log.  Any assistance would be appreciated

Log Name:      Application
Source:        Application Error
Date:          11/08/2021 07:57:46
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      ******
Description:
Faulting application name: mRemoteNG.exe, version: 1.76.20.24615, time stamp: 0x5cb09552
Faulting module name: KERNELBASE.dll, version: 10.0.18362.1474, time stamp: 0xf0a6699c
Exception code: 0xe0434352
Fault offset: 0x001146d2
Faulting process id: 0x2ce8
Faulting application start time: 0x01d78e7e305ebfd7
Faulting application path: C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: ebe6840d-3384-4910-862a-ac9d206529a9
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-08-11T06:57:46.191769300Z" />
    <EventRecordID>1953348</EventRecordID>
    <Channel>Application</Channel>
    <Computer>*********</Computer>
    <Security />
  </System>
  <EventData>
    <Data>mRemoteNG.exe</Data>
    <Data>1.76.20.24615</Data>
    <Data>5cb09552</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.18362.1474</Data>
    <Data>f0a6699c</Data>
    <Data>e0434352</Data>
    <Data>001146d2</Data>
    <Data>2ce8</Data>
    <Data>01d78e7e305ebfd7</Data>
    <Data>C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe</Data>
    <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data>
    <Data>ebe6840d-3384-4910-862a-ac9d206529a9</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

Application: mRemoteNG.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Xml.XmlException
   at System.Xml.XmlTextReaderImpl.Throw(System.Exception)
   at System.Xml.XmlTextReaderImpl.Throw(System.String, System.String[])
   at System.Xml.XmlTextReaderImpl.ParseText(Int32 ByRef, Int32 ByRef, Int32 ByRef)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlTextReaderImpl.Skip()
   at System.Xml.XmlTextReader.Skip()
   at System.Configuration.XmlUtil.StrictSkipToNextElement(System.Configuration.ExceptionAction)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   at System.Configuration.BaseConfigurationRecord.ScanSections(System.Configuration.XmlUtil)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(System.Configuration.ConfigurationSchemaErrors)
   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs)

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs)
   at System.Configuration.Internal.InternalConfigRoot.OnConfigRemoved(System.Configuration.Internal.InternalConfigEventArgs)
   at System.Configuration.Internal.InternalConfigRoot.RemoveConfigImpl(System.String, System.Configuration.BaseConfigurationRecord)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(System.String, Boolean, Boolean, Boolean, Boolean, System.Object ByRef, System.Object ByRef)
   at System.Configuration.BaseConfigurationRecord.GetSection(System.String)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(System.String)
   at System.Configuration.ConfigurationManager.GetSection(System.String)
   at System.Configuration.ClientSettingsStore.ReadSettings(System.String, Boolean)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(System.Configuration.SettingsContext, System.Configuration.SettingsPropertyCollection)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(System.Configuration.SettingsProvider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(System.String)
   at System.Configuration.SettingsBase.get_Item(System.String)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(System.String)
   at System.Configuration.ApplicationSettingsBase.get_Item(System.String)
   at mRemoteNG.Settings.get_SingleInstance()
   at mRemoteNG.App.ProgramRoot.Main(System.String[])

Currently using Windows 10 1909 x64

**Comment by HZO-IT** [comment]
I have some suggestions.

1. Try downloading the mRemoteNG portable version and see if that runs. Do you have any 3rd party antivirus?
2. Run SFC /SCANNOW using guide https://support.microsoft.com/en-us/topic/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system-files-79aa86cb-ca52-166a-92a3-966e85d4094e 
3. Try running the app in Safe Mode per guide https://support.microsoft.com/en-us/windows/start-your-pc-in-safe-mode-in-windows-10-92c27cff-db89-8644-1ce4-b3e5e56fe234
4. Rename folder mRemoteNG inside %APPDATA% then try running the app again.

**Comment by farosch** [comment]
@cheekychick your version of windows is EOL! You should update ASAP (https://docs.microsoft.com/de-de/lifecycle/products/windows-10-home-and-pro)

This error might be due to a damaged connections file. Please remove all connection files and see if mrng can then startup.
Try the portable version like @HZO-IT suggested or try out the preview version.

**Comment by anielk** [comment]
I have the same problem:
version of windows: 21H1

Error in eventvwr:
Naam van toepassing met fout: mRemoteNG.exe, versie: 1.76.20.24615, tijdstempel: 0x5cb09552
Naam van module met fout: KERNELBASE.dll, versie: 10.0.19041.1151, tijdstempel: 0x5da51925
Uitzonderingscode: 0xe0434352
Foutmarge: 0x0012b512
Id van proces met fout: 0x4350
Starttijd van toepassing met fout: 0x01d7901a5b88c56e
Pad naar toepassing met fout: C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe
Pad naar module met fout: C:\WINDOWS\System32\KERNELBASE.dll
Rapport-id: 800d910b-b410-4924-b296-8f18634d157a
Volledige pakketnaam met fout: 
Relatieve toepassings-id van pakket met fout: 

Toepassing: mRemoteNG.exe
Framework-versie: v4.0.30319
Beschrijving: het proces is beëindigd als gevolg van een onverwerkte uitzondering.
Uitzonderingsinformatie: System.Xml.XmlException
   bij System.Xml.XmlTextReaderImpl.Throw(System.Exception)
   bij System.Xml.XmlTextReaderImpl.Throw(System.String, System.String[])
   bij System.Xml.XmlTextReaderImpl.ParseText(Int32 ByRef, Int32 ByRef, Int32 ByRef)
   bij System.Xml.XmlTextReaderImpl.ParseText()
   bij System.Xml.XmlTextReaderImpl.ParseElementContent()
   bij System.Xml.XmlTextReaderImpl.Read()
   bij System.Xml.XmlTextReader.Read()
   bij System.Xml.XmlTextReaderImpl.Skip()
   bij System.Xml.XmlTextReader.Skip()
   bij System.Configuration.XmlUtil.StrictSkipToNextElement(System.Configuration.ExceptionAction)
   bij System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   bij System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   bij System.Configuration.BaseConfigurationRecord.ScanSections(System.Configuration.XmlUtil)
   bij System.Configuration.BaseConfigurationRecord.InitConfigFromFile()

Uitzonderingsinformatie: System.Configuration.ConfigurationErrorsException
   bij System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean)
   bij System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(System.Configuration.ConfigurationSchemaErrors)
   bij System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   bij System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs)

Uitzonderingsinformatie: System.Configuration.ConfigurationErrorsException
   bij System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs)
   bij System.Configuration.Internal.InternalConfigRoot.OnConfigRemoved(System.Configuration.Internal.InternalConfigEventArgs)
   bij System.Configuration.Internal.InternalConfigRoot.RemoveConfigImpl(System.String, System.Configuration.BaseConfigurationRecord)
   bij System.Configuration.BaseConfigurationRecord.GetSectionRecursive(System.String, Boolean, Boolean, Boolean, Boolean, System.Object ByRef, System.Object ByRef)
   bij System.Configuration.BaseConfigurationRecord.GetSection(System.String)
   bij System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(System.String)
   bij System.Configuration.ConfigurationManager.GetSection(System.String)
   bij System.Configuration.ClientSettingsStore.ReadSettings(System.String, Boolean)
   bij System.Configuration.LocalFileSettingsProvider.GetPropertyValues(System.Configuration.SettingsContext, System.Configuration.SettingsPropertyCollection)
   bij System.Configuration.SettingsBase.GetPropertiesFromProvider(System.Configuration.SettingsProvider)
   bij System.Configuration.SettingsBase.GetPropertyValueByName(System.String)
   bij System.Configuration.SettingsBase.get_Item(System.String)
   bij System.Configuration.ApplicationSettingsBase.GetPropertyValue(System.String)
   bij System.Configuration.ApplicationSettingsBase.get_Item(System.String)
   bij mRemoteNG.Settings.get_SingleInstance()
   bij mRemoteNG.App.ProgramRoot.Main(System.String[])

I renamed the folder in : mRemoteNG inside %APPDATA% but still no go

I will now try a night build to check if that one is working

**Comment by Kvarkas** [comment]
not relevant
