### ISSUE TITLE
rename fails

### ISSUE THREAD

**Issue by fxrsliberty** [mRemoteNG/mRemoteNG#2043]
## Expected Behavior

simple object rename failed

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):
```
Exception Message
"InvalidArgument=Value of '4' is not valid for 'index'.
Parameter name: index"

Stack trace
   at System.Windows.Forms.ListView.ListViewItemCollection.get_Item(Int32 index)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at BrightIdeasSoftware.ObjectListView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Environment
OS: Microsoft Windows NT 10.0.19043.0
mRemoteNG Version: 1.77.0.41252
Edition: MSI
Cmd line args: 

```

**Comment by Kvarkas** [comment]
hello, could you specify that exactly you was try to rename?

**Comment by fxrsliberty** [comment]
I was trying to rename a connection object

**Comment by Kvarkas** [comment]
it don't like it, mRemoteNG have special fillings to connection object :) that already know - will be used a bit different approach in feature version so we avoid such
