### ISSUE TITLE
unhandled exception

### ISSUE THREAD

**Issue by sharuzzaman** [mRemoteNG/mRemoteNG#2056]
## Expected Behavior

should not show an error message

## Current Behavior

showing error message

## Possible Solution

not sure.

## Steps to Reproduce (for bugs)

1. VNC to a remote Windows computer (running TightVNC)
2. Close the VNC window
3. Error pop up
4.

## Context

Trying to close a VNC window connected to a PC in local LAN

## Your Environment

* Version used: mRemoteNG Version: 1.77.0.41307 Portable
* Operating System and version (e.g. Windows 10 1709 x64): Microsoft Windows 10 Pro 10.0.19043 N/A Build 19043
                

```
Exception Message
"Cannot access a disposed object.
Object name: 'ConnectionWindow'."

Stack trace
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Delegate method)
   at mRemoteNG.UI.Window.ConnectionWindow.Prot_Event_Closed(Object sender)
   at mRemoteNG.Connection.Protocol.ProtocolBase.ClosedEventHandler.Invoke(Object sender)
   at mRemoteNG.Connection.Protocol.ProtocolBase.CloseBG()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Environment
OS: Microsoft Windows NT 10.0.19043.0
mRemoteNG Version: 1.77.0.41307
Edition: Portable
Cmd line args: 

```

**Comment by farosch** [comment]
Please use either a release version or a current preview version and retry this scenario.
When the issue still persists, just reply and I will reopen the issue. Unfortunately, this may be only solvable by implementing  #2025
