### ISSUE TITLE
Changes in RenderingEngine enums prevents loading existing SQL connections

### ISSUE THREAD

**Issue by sarog** [mRemoteNG/mRemoteNG#2057]
This is migrating from mRemoteNG 1.77.1.29095 to 1.77.2.20593 (Debug Portable).

## Expected Behavior
Loading existing connections in a SQL database from version to version without issues.

## Current Behavior
Existing connections saved in a SQL database fail to load after an upgrade to mRemoteNG due to referencing an unknown `RenderingEngine` enum ("CEF").

## Possible Solution
The main problem here is that a developer is [never supposed to modify/remove existing enum values](https://github.com/mRemoteNG/mRemoteNG/pull/2022/files#diff-2b3a953599a88f76d55ea8059111616c022af1c6be54a74f25c8857be8acb5d6L291) as it breaks compatibility, even if there was never an official release of mRNG with CEF since 2019. The correct procedure was to simply add another enum value and handle references to the outgoing value separately, say in the connection loading function. Consider the day when we finally deploy workstations without IE and disable the compat engine in Edge -- how will we handle such a change then?

Possible solution can be to update references to "CEF" with "EdgeChromium" in the `tblcons` table via SQL (under `Versioning`):
`update tblcons set RenderingEngine = 'EdgeChromium' where RenderingEngine = 'CEF';`

But that SQL command won't work because the `RenderingEngine` column is a [varchar(10)](https://github.com/mRemoteNG/mRemoteNG/blob/develop/mRemoteNGDocumentation/mysql_db_setup.sql#L73) field.

## Steps to Reproduce (for bugs)
1. Use mRemoteNG 1.77.1 (or a version before #2022) with connections saved in a SQL database.
2. Upgrade mRemoteNG to latest build with said pull request.
3. Start mRemoteNG and wait for the connections to load from the database.
4. Crash with an error message: "Load from SQL failed" => "Requested value 'CEF' was not found."

## Context
Unable to migrate mRemoteNG without having to manually modify database tables, affecting user experience.

## Your Environment
* Version (old): 1.77.1.29095 (Debug Portable, built from source)
* Version (new): 1.77.2.20593 (Debug Portable, built from source)
* Operating System: Windows 10 x64 21H1

Full stack trace:

```
Exception Message
"Requested value 'CEF' was not found."

Stack trace
   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at System.Enum.Parse(Type enumType, String value)
   at mRemoteNG.Config.Serializers.ConnectionSerializers.MsSql.DataTableDeserializer.PopulateConnectionInfoFromDatarow(DataRow dataRow, ConnectionInfo connectionInfo) in E:\Code\mRemoteNG\mRemoteNG\Config\Serializers\ConnectionSerializers\MsSql\DataTableDeserializer.cs:line 100
   at mRemoteNG.Config.Serializers.ConnectionSerializers.MsSql.DataTableDeserializer.DeserializeContainerInfo(DataRow row) in E:\Code\mRemoteNG\mRemoteNG\Config\Serializers\ConnectionSerializers\MsSql\DataTableDeserializer.cs:line 71
   at mRemoteNG.Config.Serializers.ConnectionSerializers.MsSql.DataTableDeserializer.CreateNodesFromTable(DataTable table) in E:\Code\mRemoteNG\mRemoteNG\Config\Serializers\ConnectionSerializers\MsSql\DataTableDeserializer.cs:line 51
   at mRemoteNG.Config.Serializers.ConnectionSerializers.MsSql.DataTableDeserializer.Deserialize(DataTable table) in E:\Code\mRemoteNG\mRemoteNG\Config\Serializers\ConnectionSerializers\MsSql\DataTableDeserializer.cs:line 33
   at mRemoteNG.Config.Connections.SqlConnectionsLoader.Load() in E:\Code\mRemoteNG\mRemoteNG\Config\Connections\SqlConnectionsLoader.cs:line 57
   at mRemoteNG.Connection.ConnectionsService.LoadConnections(Boolean useDatabase, Boolean import, String connectionFileName) in E:\Code\mRemoteNG\mRemoteNG\Connection\ConnectionsService.cs:line 138
   at mRemoteNG.UI.Forms.OptionsPages.SqlServerPage.ReinitializeSqlUpdater() in E:\Code\mRemoteNG\mRemoteNG\UI\Forms\OptionsPages\SqlServerPage.cs:line 83
   at mRemoteNG.UI.Forms.OptionsPages.SqlServerPage.SaveSettings() in E:\Code\mRemoteNG\mRemoteNG\UI\Forms\OptionsPages\SqlServerPage.cs:line 73
   at mRemoteNG.UI.Forms.FrmOptions.BtnOK_Click(Object sender, EventArgs e) in E:\Code\mRemoteNG\mRemoteNG\UI\Forms\FrmOptions.cs:line 134
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Environment
OS: Microsoft Windows NT 10.0.19043.0
mRemoteNG Version: 1.77.2.20593
Edition: Portable
Cmd line args: 

```

**Comment by Vest** [comment]
Hello @sarog 
I have extended the field from 10 chars to 16, but since there are not "migration" scripts in the project, I don't know how your bug can be fixed. Probably, this report should be closed with "by design" status (for now). I think, your report can be used as a reference for other users in case, if they have the same error.

**Comment by sarog** [comment]
Hi @Vest, thank you for the follow-up. I'll go ahead and close this issue for now.
