### ISSUE TITLE
inheritance causes exception?

### ISSUE THREAD

**Issue by tecxx** [mRemoteNG/mRemoteNG#2075]
when i select any folder or connection in the tree, 

![image](https://user-images.githubusercontent.com/4305825/144909309-80eab164-057d-4d22-b1e7-89b200259833.png)

i get an exception in ConnectionInfoPropertyGrid:

![image](https://user-images.githubusercontent.com/4305825/144908940-d4ffff50-9f0e-4a78-bb55-31102cb91b35.png)

this happens with a fresh confCons.xml as well.

when i go to the root node ("Connections") and set the inheritance to "inherit all: yes", and then back to "inherit all: no"
![image](https://user-images.githubusercontent.com/4305825/144909014-ac6b7de6-e090-4186-977c-5985bb2bceee.png)

the error goes away, until i restart mremote.

note that this is a fresh clone of the develop code base, date 2021-12-06, no changes done on my side. am i the only one experiencing this?

**Comment by Kvarkas** [comment]
thanks for reporting will check, so far you are first facing such

**Comment by tecxx** [comment]
i tried to investigate this for some time, but whatever i tried, i cannot find the cause. only more errors. 
for example, selecting a folder, putting the cursor in "SSH Tunnel" and pressing TAB (or mousewhell scroll) results in this error:

   at System.Windows.Forms.PropertyGridInternal.GridEntry.NonParentEquals(Object obj)
   at System.Windows.Forms.PropertyGridInternal.GridEntry.Equals(Object obj)
   at System.Collections.Generic.ObjectEqualityComparer`1.IndexOf(T[] array, T value, Int32 startIndex, Int32 count)
   at System.Array.IndexOf[T](T[] array, T value, Int32 startIndex, Int32 count)
   at System.Collections.Generic.List`1.Contains(T item)
   at mRemoteNG.UI.Controls.FilteredPropertyGrid.FilteredPropertyGrid.GetVisibleGridItemsRecursive(GridItem item, List`1 gridItems) in C:\DATA\SVN\mRemoteNG\mRemoteNG\mRemoteNG\UI\Controls\FilteredPropertyGrid\FilteredPropertyGrid.cs:line 153
   at mRemoteNG.UI.Controls.FilteredPropertyGrid.FilteredPropertyGrid.GetVisibleGridItemsRecursive(GridItem item, List`1 gridItems) in C:\DATA\SVN\mRemoteNG\mRemoteNG\mRemoteNG\UI\Controls\FilteredPropertyGrid\FilteredPropertyGrid.cs:line 161
   at mRemoteNG.UI.Controls.FilteredPropertyGrid.FilteredPropertyGrid.GetVisibleGridItemsRecursive(GridItem item, List`1 gridItems) in C:\DATA\SVN\mRemoteNG\mRemoteNG\mRemoteNG\UI\Controls\FilteredPropertyGrid\FilteredPropertyGrid.cs:line 161
   at mRemoteNG.UI.Controls.FilteredPropertyGrid.FilteredPropertyGrid.GetVisibleGridItems() in C:\DATA\SVN\mRemoteNG\mRemoteNG\mRemoteNG\UI\Controls\FilteredPropertyGrid\FilteredPropertyGrid.cs:line 148
   at mRemoteNG.UI.Controls.FilteredPropertyGrid.FilteredPropertyGrid.FindNextGridItemProperty(GridItem startItem) in C:\DATA\SVN\mRemoteNG\mRemoteNG\mRemoteNG\UI\Controls\FilteredPropertyGrid\FilteredPropertyGrid.cs:line 210
   at mRemoteNG.UI.Controls.FilteredPropertyGrid.FilteredPropertyGrid.SelectNextGridItem() in C:\DATA\SVN\mRemoteNG\mRemoteNG\mRemoteNG\UI\Controls\FilteredPropertyGrid\FilteredPropertyGrid.cs:line 256
   at mRemoteNG.UI.Window.ConfigWindow.ProcessCmdKey(Message& msg, Keys keyData) in C:\DATA\SVN\mRemoteNG\mRemoteNG\mRemoteNG\UI\Window\ConfigWindow.cs:line 286
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.TextBoxBase.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.TextBox.ProcessCmdKey(Message& m, Keys keyData)
   at System.Windows.Forms.PropertyGridInternal.PropertyGridView.GridViewEdit.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)

![image](https://user-images.githubusercontent.com/4305825/145024057-334ee7f9-ddfc-43ef-a745-75de9c490ab7.png)


clicking buttons in the toolbar results in similar errors:
![image](https://user-images.githubusercontent.com/4305825/145024964-2c581f57-0fac-4805-a10a-3228e039c169.png)


i am not sure if this is maybe just a bug with winforms in .net6. this error did not appear in previous mremote code revisions. am i really still the only one experiencing this? :)

**Comment by Kvarkas** [comment]
something weird happening with serialization/deserialization as tests failing at them as well - so expecting need to check if .net6 not involve into that and we recently add one option that perhaps add mess to such as well :(

**Comment by tecxx** [comment]
might have found the issue.
i removed all traces of OpeningCommand from AbstractConnectionRecord.cs, and all references from the codebase. all errors gone.

![image](https://user-images.githubusercontent.com/4305825/146100908-bc772c39-17c8-4f44-9d19-794594d99515.png)


will investigate further.

**Comment by Kvarkas** [comment]
Its looks like try to get translation from lang file and I expect its don't exist so its not able to trace it

**Comment by tecxx** [comment]
yes, something along those lines. i added lang file stuff for OpeningCommand, but that didn't fully solve it. digging deeper i found that there seems to be a mismatch between two other properties:

StartProgram and RDPStartProgram

there is
![image](https://user-images.githubusercontent.com/4305825/146197497-ef0514cd-344d-41bc-bac3-1564e664dac4.png)

and
![image](https://user-images.githubusercontent.com/4305825/146197758-40e13bac-4fb0-4f8c-a4e8-747cced71f73.png)


removing "startprogram" and naming everything "RDPStartProgram" made the final fix for me. before i submit a PR, i need to understand is "StartProgram" something different? or was it renamed to "RDPStartProgram" and just forgotten to cleanup correctly?

**Comment by Vest** [comment]
I don't know if this is how OpeningCommand was supposed to work, but if I use it for SSH, but my SSH connection requires a key, the opening command is executed **before** the login, meaning that it is falsely used as my PIN.
![I use OpeningCommand](https://user-images.githubusercontent.com/1671049/147384360-c5980686-2271-4fc3-8aa1-25c92012cb48.png)

In other words, the feature probably doesn't work as it should.

**Comment by tecxx** [comment]
i have no idea about this feature, all i did was fix the crash caused by it, by adding/fixing the missing resource stuff. hence the "TODO" language table entry as i wasn't sure what to write there....

**Comment by Vest** [comment]
Hm. Ok. Thanks. I found an old feature that was added. But it seems that it doesn’t work well.
