### ISSUE TITLE
Unhandled Exception when closing mRemoteNG having multiple panels open

### ISSUE THREAD

**Issue by simonai1254** [mRemoteNG/mRemoteNG#2118]
## Expected Behavior
When having opened connections in multiple panels and then closing mRemoteNG through the Exit Button in the top right corner a promt is displayed for each panel if should really be closed. After confirming mRemoteNG should close.

## Current Behavior
When having opened connections in multiple panels and then closing mRemoteNG through the Exit Button in the top right corner a promt is displayed for each panel if should really be closed. After confirming the first panel, an unhandled exception is thrown:

```
Exception Message
"Cannot access a disposed object.
Object name: 'ConnectionWindow'."

Stack trace
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Action method)
   at mRemoteNG.UI.Window.ConnectionWindow.Prot_Event_Closed(Object sender)
   at mRemoteNG.UI.Window.ConnectionWindow.Prot_Event_Closed(Object sender)
   at mRemoteNG.UI.Window.ConnectionWindow.Prot_Event_Closed(Object sender)
   at mRemoteNG.Connection.Protocol.ProtocolBase.CloseBG()
   at mRemoteNG.Connection.Protocol.ProtocolBase.CloseBG()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

Environment
OS: Microsoft Windows NT 10.0.19044.0
mRemoteNG Version: 1.77.2
Edition: MSI
Cmd line args: 

```
After exiting the exception prompt the second prompt is displayed and mRemoteNG closes.

## Possible Solution
Setting "Share Clipboard" to" yes" in the rdp configuration (disabled by default after migration from 1.76.20) for the devices in the inactive panel did prevent the exception to arise.
This also occours only when multiple panels are used.

## Steps to Reproduce (for bugs)

1. Open 2 rdp session (windows server 2019 with at least one device that has clipboard sharing disabled) and 2 ssh sessions (ubuntu 20) in panel 1
2. Open 2 rdp session (windows server 2019) and 2 ssh sessions (ubuntu 20) in panel 2
3. Cycle through all remote sessions and make sure all are connected
4. Bring a connection from panel 2 into foreground
5. Exit mRemoteNG

Note: I could not reproduce this when connecting to less devices than stated above, though with more the reproduction was not a problem.

## Context
I have enabled that the sessions should be reopened after closing mRemoteNG (File>Options>Startup/Exit>Reconnect to previously opened sessions on startup) and would like to get them opened again so I can continue where I left off.
Also I do have multiple panels to differ between customers, therefore there are days when I do have multiple panels open.

## Your Environment
OS: Microsoft Windows NT 10.0.19044.0
mRemoteNG Version: 1.77.2-nb (20220107)
.Net Runtime: windowsdesktop-runtime-6.0.1-win-x64
Edition: MSI
Cmd line args:

**Comment by simonai1254** [comment]
This issue might be connected to issue #2119

**Comment by djkraven** [comment]
This happens when trying to close connection groups with open/active sessions under them. It isn't easy to reduce the connection group or get to an empty set and start over when a large group of sessions is open. 

![image](https://github.com/mRemoteNG/mRemoteNG/assets/5774810/815f8a05-779e-480c-894b-1ac5d81718a5)

**Comment by robertpopa22** [comment]
Likely same close-sequence crash cluster already addressed by close-panel hardening and follow-up main-close cancellation fixes: PR #3106 and PR #3124. 
 
Please retest on latest RC candidate build from fork. If no longer reproducible, recommend closing as resolved/duplicate of panel-close crash issues.

---

> *We sincerely appreciate the mRemoteNG maintainers and the wonderful community that has kept this project alive and thriving for over a decade. Your work powers thousands of IT professionals worldwide, including us. Our fork builds entirely on your foundation — we're preparing a consolidated Pull Request to contribute these improvements back to the official project. Thank you for everything you've built.*
>
> *— robertpopa22, community contributor*

**Comment by robertpopa22** [comment]
This appears to match the same ConnectionWindow.Prot_Event_Closed disposed-object close-path as #3069. Candidate upstream fix package is PR #3106: PR #3106 on `mRemoteNG/mRemoteNG` After merge in parent, please retest on a build that includes that commit; if still reproducible with exact steps/logs, keep this issue open, otherwise close as duplicate of #3069.

---

> *We sincerely appreciate the mRemoteNG maintainers and the wonderful community that has kept this project alive and thriving for over a decade. Your work powers thousands of IT professionals worldwide, including us. Our fork builds entirely on your foundation — we're preparing a consolidated Pull Request to contribute these improvements back to the official project. Thank you for everything you've built.*
>
> *— robertpopa22, community contributor*

**Comment by robertpopa22** [comment]
**Fix available for testing**

**Commit:** `a1717026` (fork `robertpopa22/mRemoteNG`, branch `main`)
**What changed:** Unhandled Exception when closing mRemoteNG having multiple p

A beta build (v1.81.0-beta.4) including this fix is available from the fork's Releases page.

---

> *We sincerely appreciate the mRemoteNG maintainers and the wonderful community that has kept this project alive and thriving for over a decade. Your work powers thousands of IT professionals worldwide, including us. Our fork builds entirely on your foundation — we're preparing a consolidated Pull Request to contribute these improvements back to the official project. Thank you for everything you've built.*
>
> *— robertpopa22, community contributor*
