### ISSUE TITLE
mRemoteNG crashes if panel containing connection(s) is closed

### ISSUE THREAD

**Issue by C4rb0n** [mRemoteNG/mRemoteNG#2163]
When connections belonging to more than one panel are open (thus making the panel tabs appear), if a panel is closed, by clicking the "X" or right-clicking and choosing "X Close" on the panel tab itself, mRemoteNG crashes with the following exception:

   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Action method)
   at mRemoteNG.UI.Window.ConnectionWindow.Prot_Event_Closed(Object sender)
   at mRemoteNG.Connection.Protocol.ProtocolBase.CloseBG()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Action method)
   at mRemoteNG.UI.Window.ConnectionWindow.Prot_Event_Closed(Object sender)
   at mRemoteNG.Connection.Protocol.ProtocolBase.CloseBG()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

Clicking "Report a Bug" on the exception window also generates an exception

## Expected Behavior

Panel, including all associated connections should be terminated without mRemoteNG crashing.

## Current Behavior

mRemoteNG crashes.  This is a regression from prior releases that did not crash.

## Steps to Reproduce (for bugs)

1. Open connections belonging to different panels, such that the panel tabs become visible
2. Close one of the panels by either clicking the "X" or right-clicking and choosing "X Close" on the panel tab itself.

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):
mRemoteNG Nightly v1.77.2-nb
Windows 10 Pro Version 21H2 (OS Build 19044.1348)
.NET version 6.0.121.56705

**Comment by simonai1254** [comment]
This could be related to #2118, just caused manually and not when closing the Window itself...

**Comment by PetbkA** [comment]
I guess the problem is with connections that require Putty (Telnet, SSH etc.). Tried with RDP, VNC, Telnet and SSH connections and only the latter two are causing crash. Exception is the same:

```
Exception Message
"Cannot access a disposed object.
Object name: 'ConnectionWindow'."

Stack trace
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Action method)
   at mRemoteNG.UI.Window.ConnectionWindow.Prot_Event_Closed(Object sender)
   at mRemoteNG.Connection.Protocol.ProtocolBase.CloseBG()
   at System.Threading.Thread.StartHelper.Callback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Thread.StartCallback()

Environment
OS: Microsoft Windows NT 10.0.19044.0
mRemoteNG Version: 1.77.2
Edition: MSI
Cmd line args: 
```

**Comment by robertpopa22** [comment]
Likely addressed by close-panel stability package in PR #3106 (same panel-close/disposed connection path). 
 
Please retest on latest fork RC candidate build; if no longer reproducible, this can be closed as duplicate of #3069.

---

> *We sincerely appreciate the mRemoteNG maintainers and the wonderful community that has kept this project alive and thriving for over a decade. Your work powers thousands of IT professionals worldwide, including us. Our fork builds entirely on your foundation — we're preparing a consolidated Pull Request to contribute these improvements back to the official project. Thank you for everything you've built.*
>
> *— robertpopa22, community contributor*

**Comment by robertpopa22** [comment]
This appears to match the same ConnectionWindow.Prot_Event_Closed disposed-object close-path as #3069. Candidate upstream fix package is PR #3106: PR #3106 on `mRemoteNG/mRemoteNG` After merge in parent, please retest on a build that includes that commit; if still reproducible with exact steps/logs, keep this issue open, otherwise close as duplicate of #3069.

---

> *We sincerely appreciate the mRemoteNG maintainers and the wonderful community that has kept this project alive and thriving for over a decade. Your work powers thousands of IT professionals worldwide, including us. Our fork builds entirely on your foundation — we're preparing a consolidated Pull Request to contribute these improvements back to the official project. Thank you for everything you've built.*
>
> *— robertpopa22, community contributor*

**Comment by robertpopa22** [comment]
**Fix available for testing**

A fix for this issue has been implemented in our community fork (`robertpopa22/mRemoteNG`, branch `main`). A beta build including this fix is available from the fork's Releases page.

Please test and report if this resolves your issue.

---

> *We sincerely appreciate the mRemoteNG maintainers and the wonderful community that has kept this project alive and thriving for over a decade. Your work powers thousands of IT professionals worldwide, including us. Our fork builds entirely on your foundation — we're preparing a consolidated Pull Request to contribute these improvements back to the official project. Thank you for everything you've built.*
>
> *— robertpopa22, community contributor*
