### ISSUE TITLE
Crashes / Tab Issues When Idling and Resized

### ISSUE THREAD

**Issue by jcefoli** [mRemoteNG/mRemoteNG#2166]
I am not sure how to completely reproduce this, but have experienced a crash when I use regular RDP to an instance (ie - juimp server) and run mRemoteNG in that RDP session. When the RDP resizes or if I disconnect, I notice that in some special instances mRemoteNG tabs will become messed up and disassociate with the RDP session. They cannot be closed or removed unless you exit the app. I don't know how toi reproduce this 100%, but noted that it happens when mRemoteNG remains connected in an RDP session and is resized, or some time passes

I have two stack traces that are possibly related:

**Collection was modified; enumeration operation may not execute.** 
```
   at System.Collections.ArrayList.ArrayListEnumeratorSimple.MoveNext()
   at mRemoteNG.UI.Forms.FrmMain.frmMain_FormClosing(Object sender, FormClosingEventArgs e)
   at System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at mRemoteNG.UI.Forms.FrmMain.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

and

Object reference not set to an instance of an object

```
   at WeifenLuo.WinFormsUI.Docking.DockPanel.OnLayout(LayoutEventArgs levent)
   at System.Windows.Forms.Control.PerformLayout(LayoutEventArgs args)
   at System.Windows.Forms.Control.PerformLayout()
   at System.Windows.Forms.Control.ResumeLayout(Boolean performLayout)
   at WeifenLuo.WinFormsUI.Docking.DockPanel.ResumeLayout(Boolean performLayout, Boolean allWindows)
   at WeifenLuo.WinFormsUI.Docking.DockPane.CloseContent(IDockContent content)
   at WeifenLuo.WinFormsUI.Docking.DockPaneStripBase.TryCloseTab(Int32 index)
   at mRemoteNG.UI.Tabs.DockPaneStripNG.TabCloseButtonHit(Int32 index)
   at mRemoteNG.UI.Tabs.DockPaneStripNG.OnMouseClick(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at WeifenLuo.WinFormsUI.Docking.DockPaneStripBase.WndProc(Message& m)
   at mRemoteNG.UI.Tabs.DockPaneStripNG.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) 
```

## Expected Behavior
- Tabs should not become unassociated from their RDP instances or lose control from the UI

## Current Behavior
Tabs stop working if the application is idle in an RDP session and that parent RDP window is resized or reconnected. It is not exactly reproducible every time, but happens a lot

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64): Windows Server 2019, Windows 10 21H2

**Comment by simonai1254** [comment]
Interesting Bug. Would you mind telling us what Version of mRemoteNG you are using on both systems? 
Is that the latest build 1.77.2-nb (20220107) or is it the latest stable release 1.76.20? You can find that information in the Help>About window.

**Comment by jcefoli** [comment]
That's a good question, because I compile the dev branches myself. Pretty sure this still happens in the latest v1.77.3-dev branch

**Comment by robertpopa22** [comment]
Triage refresh (P4 version-label debt): this issue is tagged with legacy version labels. Please retest on the latest build (fork v1.79.x or upstream dev), then share reproducible steps and expected vs actual behavior. If still valid, keep open and relabel to current triage scope (for example Need 2 check). If fixed, close with resolution.

Current legacy version labels: 1.77.3

**Comment by robertpopa22** [comment]
Likely addressed by panel-close behavior fixes already packaged upstream: PR #3106 and follow-up panel empty-state fix on fork release branch. 
 
Please retest on latest RC candidate build; if resolved, recommend close as duplicate/resolved.

---

> *We sincerely appreciate the mRemoteNG maintainers and the wonderful community that has kept this project alive and thriving for over a decade. Your work powers thousands of IT professionals worldwide, including us. Our fork builds entirely on your foundation — we're preparing a consolidated Pull Request to contribute these improvements back to the official project. Thank you for everything you've built.*
>
> *— robertpopa22, community contributor*

**Comment by robertpopa22** [comment]
RC update: packaged in parent PR #3129 and ready for retest on latest RC builds. 
PR: PR #3129 on `mRemoteNG/mRemoteNG` 
Scope: harden document-tab close path during resize/reconnect layout churn (deferred close plus guards in DockPaneStripNG). 
Note: the FormClosing enumeration trace from this issue is covered by parent PR #3124.

---

> *We sincerely appreciate the mRemoteNG maintainers and the wonderful community that has kept this project alive and thriving for over a decade. Your work powers thousands of IT professionals worldwide, including us. Our fork builds entirely on your foundation — we're preparing a consolidated Pull Request to contribute these improvements back to the official project. Thank you for everything you've built.*
>
> *— robertpopa22, community contributor*

**Comment by robertpopa22** [comment]
**Fix available in community release**

This fix is included in a community build from our fork (`robertpopa22/mRemoteNG`, branch `main`). Available from the fork's Releases page.

Please test and let us know if the issue is fully resolved.

---

> *We sincerely appreciate the mRemoteNG maintainers and the wonderful community that has kept this project alive and thriving for over a decade. Your work powers thousands of IT professionals worldwide, including us. Our fork builds entirely on your foundation — we're preparing a consolidated Pull Request to contribute these improvements back to the official project. Thank you for everything you've built.*
>
> *— robertpopa22, community contributor*
