### ISSUE TITLE
Could not load file or assembly

### ISSUE THREAD

**Issue by csbulak** [mRemoteNG/mRemoteNG#2205]
```
Exception Message
"Could not load file or assembly 'System.Management, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The file or directory is corrupted and unreadable. (Exception from HRESULT: 0x80070570)"

Stack trace
   at mRemoteNG.App.Initialization.StartupDataLogger.GetOperatingSystemData()
   at mRemoteNG.App.Initialization.StartupDataLogger.LogSystemData() in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\App\Initialization\StartupDataLogger.cs:line 32
   at mRemoteNG.App.Initialization.StartupDataLogger.LogStartupData() in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\App\Initialization\StartupDataLogger.cs:line 25
   at mRemoteNG.App.Startup.InitializeProgram(MessageCollector messageCollector) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\App\Startup.cs:line 43
   at mRemoteNG.UI.Forms.FrmMain.frmMain_Load(Object sender, EventArgs e) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Forms\FrmMain.cs:line 148
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at mRemoteNG.UI.Forms.FrmMain.WndProc(Message& m) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Forms\FrmMain.cs:line 565
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Environment
OS: Microsoft Windows NT 10.0.19044.0
mRemoteNG Version: 1.77.1.27654
Edition: MSI
Cmd line args: 

```

**Comment by Kvarkas** [comment]
Please use newer version https://mremoteng.org/download
