### ISSUE TITLE
Column 'DomainName' does not belong to table tblCons.

### ISSUE THREAD

**Issue by Gronkstar** [mRemoteNG/mRemoteNG#2221]
```
Exception Message
"Column 'DomainName' does not belong to table tblCons."

Stack trace
   at System.Data.DataRow.GetDataColumn(String columnName)
   at System.Data.DataRow.get_Item(String columnName)
   at mRemoteNG.Config.Serializers.MsSql.DataTableDeserializer.PopulateConnectionInfoFromDatarow(DataRow dataRow, ConnectionInfo connectionInfo)
   at mRemoteNG.Config.Serializers.MsSql.DataTableDeserializer.DeserializeContainerInfo(DataRow row)
   at mRemoteNG.Config.Serializers.MsSql.DataTableDeserializer.CreateNodesFromTable(DataTable table)
   at mRemoteNG.Config.Serializers.MsSql.DataTableDeserializer.Deserialize(DataTable table)
   at mRemoteNG.Config.Connections.SqlConnectionsLoader.Load()
   at mRemoteNG.Connection.ConnectionsService.LoadConnections(Boolean useDatabase, Boolean import, String connectionFileName)
   at mRemoteNG.UI.Forms.OptionsPages.SqlServerPage.ReinitializeSqlUpdater()
   at mRemoteNG.UI.Forms.OptionsPages.SqlServerPage.SaveSettings()
   at mRemoteNG.UI.Forms.FrmOptions.btnOK_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Environment
OS: Microsoft Windows NT 10.0.19044.0
mRemoteNG Version: 1.77.1.27713
Edition: Portable
Cmd line args: 

```

Stable release does not have MYSQL in it so i am forced to use a BETA.

**Comment by Gronkstar** [comment]
aaThe nightly build works flawlessly - other then it does not open VNC connections what so ever

**Comment by robertpopa22** [comment]
Triage refresh (P2): this issue has been inactive for a long time. Please retest on the latest build and share reproducible steps, expected vs actual behavior, and logs/screenshots. If there is no confirmation/update, maintainers can close it as stale or not reproducible.

**Comment by robertpopa22** [comment]
**Fix available for testing**

A fix for this issue has been implemented in our community fork (`robertpopa22/mRemoteNG`, branch `main`). A beta build including this fix is available from the fork's Releases page.

Please test and report if this resolves your issue.

---

> *We sincerely appreciate the mRemoteNG maintainers and the wonderful community that has kept this project alive and thriving for over a decade. Your work powers thousands of IT professionals worldwide, including us. Our fork builds entirely on your foundation — we're preparing a consolidated Pull Request to contribute these improvements back to the official project. Thank you for everything you've built.*
>
> *— robertpopa22, community contributor*
