### ISSUE TITLE
VNC connection error

### ISSUE THREAD

**Issue by TimKras** [mRemoteNG/mRemoteNG#2321]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at VncSharp.VncClippedDesktopPolicy.RepositionImage(Image desktopImage)
   at VncSharp.RemoteDesktop.OnPaint(PaintEventArgs pe)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at VncSharp.RemoteDesktop.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
mRemoteNG
    Assembly Version: 1.76.20.24615
    Win32 Version: 1.76.20.24615
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/mRemoteNG.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4536.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4590.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4550.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Assembly Version: 2.16.0.0
    Win32 Version: 2.16.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
mRemoteNG.resources
    Assembly Version: 1.76.20.24615
    Win32 Version: 1.76.20.24615
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/en-US/mRemoteNG.resources.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking.ThemeVS2003
    Assembly Version: 2.16.0.0
    Win32 Version: 2.16.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/WeifenLuo.WinFormsUI.Docking.ThemeVS2003.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking.ThemeVS2012
    Assembly Version: 2.16.0.0
    Win32 Version: 2.16.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/WeifenLuo.WinFormsUI.Docking.ThemeVS2012.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking.ThemeVS2013
    Assembly Version: 2.16.0.0
    Win32 Version: 2.16.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/WeifenLuo.WinFormsUI.Docking.ThemeVS2013.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking.ThemeVS2015
    Assembly Version: 2.16.0.0
    Win32 Version: 2.16.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/WeifenLuo.WinFormsUI.Docking.ThemeVS2015.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
MagicLibrary
    Assembly Version: 1.7.4.0
    Win32 Version: 1.7.4.0
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/MagicLibrary.DLL
----------------------------------------
log4net
    Assembly Version: 2.0.8.0
    Win32 Version: 2.0.8.0
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/log4net.DLL
----------------------------------------
BouncyCastle.Crypto
    Assembly Version: 1.8.1.0
    Win32 Version: 1.8.15362.1
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/BouncyCastle.Crypto.DLL
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4435.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
ObjectListView
    Assembly Version: 2.9.1.1072
    Win32 Version: 2.9.1.0
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/ObjectListView.DLL
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4494.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
VncSharp
    Assembly Version: 1.2.0.0
    Win32 Version: 1.2.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/VncSharp.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by Kvarkas** [comment]
look like as framework is missing on the system?

**Comment by TimKras** [comment]
Other VNC connections are working fine.

**Comment by simonai1254** [comment]
> Other VNC connections are working fine.

Do you get the faulty connection running with an other tool than mRemoteNG? And could you verify the connection settings in mRemoteNG if they are any different for the one that works and the broken one? Or are there other differences between the Hosts that work and the one that doesn't? 

Also it would be interesting to know what version of mRemoteNG you are using.

**Comment by TimKras** [comment]
Other tools (Temrinals and VNC viewer) are working fine.
Connection settings are identical (apart from IP and username) to working connections.
Currently using this version: 
![image](https://user-images.githubusercontent.com/5257192/211862491-3e9c42a5-c1d2-4bfc-af3b-57f162ffad81.png)

**Comment by Kvarkas** [comment]
Could you try to use latest 1.77.3 for test? I am unable to reproduce such :(

**Comment by ziotibia81** [comment]
I don't know if it's the same problem but I've troubles with VNC connections. 

mRemoteNG 1.77.3 Portable Edition


`2023-02-06 15:38:20,244 [1] ERROR - Apertura della connessione fallita! Value cannot be null. (Parameter 'stream')` 
`2023-02-06 15:38:20,261 [1] ERROR - Protocol Event Disconnected fallito.
{0}
Unable to cast object of type 'VncSharpCore.RemoteDesktop' to type 'mRemoteNG.Connection.Protocol.ProtocolBase'.
   at mRemoteNG.Connection.ConnectionInitiator.Prot_Event_Disconnected(Object sender, String disconnectedMessage, Nullable'1 reasonCode)
` 

Same error on mRemoteNG-1.76.20.24669

VNC Server is:
- 5.0.6 (r113416) - Built on Oct  3 2013 12:40:58, 32bit build
- Mode: Service Mode

---------------

When using VNC Server:
    x11vnc: 0.9.13

Work on mRemoteNG-1.76.20.24669
"Unable to cast.." error on mRemoteNG 1.77.3

**Comment by lipoforall** [comment]
Similiar problem

2023-03-08 14:58:09,840 [1] INFO  - mRemoteNG 1.77.2 Portable Edition starting.
2023-03-08 14:58:09,846 [1] INFO  - Command Line: C:\Users\USERNAME\gdrive\SW\mRemoteNG\mRemoteNG.dll
2023-03-08 14:58:10,006 [1] INFO  - Microsoft Windows 10 Enterprise  64-bit
2023-03-08 14:58:10,007 [1] INFO  - Microsoft .NET CLR 6.0.14
2023-03-08 14:58:10,007 [1] INFO  - System Culture: en/English
2023-03-08 14:58:10,007 [1] INFO  - Checking FIPS policy...
2023-03-08 14:58:10,008 [1] INFO  - FIPS2003: False
2023-03-08 14:58:10,009 [1] INFO  - FIPS2008+: False
2023-03-08 14:58:10,012 [1] INFO  - Checking Lenovo AutoScroll Utility...
2023-03-08 14:58:10,019 [1] INFO  - Lenovo AutoScroll Utility not found
2023-03-08 14:58:10,084 [1] ERROR - Error loading default connectioninfo property UserViaAPI
No property with name 'ConDefaultUserViaAPI' found.
   at mRemoteNG.Connection.DefaultConnectionInfo.LoadFrom[TSource](TSource sourceInstance, Func`2 propertyNameMutator)
2023-03-08 14:58:10,086 [1] ERROR - Error loading default connectioninfo property EC2InstanceId
No property with name 'ConDefaultEC2InstanceId' found.
   at mRemoteNG.Connection.DefaultConnectionInfo.LoadFrom[TSource](TSource sourceInstance, Func`2 propertyNameMutator)
2023-03-08 14:58:10,087 [1] ERROR - Error loading default connectioninfo property OpeningCommand
No property with name 'ConDefaultOpeningCommand' found.
   at mRemoteNG.Connection.DefaultConnectionInfo.LoadFrom[TSource](TSource sourceInstance, Func`2 propertyNameMutator)
2023-03-08 14:58:10,091 [1] ERROR - DefaultConInherit-LoadFrom: Could not load UserViaAPI
2023-03-08 14:58:10,092 [1] ERROR - DefaultConInherit-LoadFrom: Could not load OpeningCommand
2023-03-08 14:58:17,242 [1] ERROR - Opening connection failed!
Value cannot be null. (Parameter 'stream')
   at System.Drawing.Image.FromStream(Stream stream, Boolean useEmbeddedColorManagement, Boolean validateImageData)
   at System.Drawing.Image.FromStream(Stream stream)
   at VncSharpCore.RemoteDesktop..ctor()
   at mRemoteNG.Connection.Protocol.VNC.ProtocolVNC..ctor()
   at mRemoteNG.Connection.Protocol.ProtocolFactory.CreateProtocol(ConnectionInfo connectionInfo)
   at mRemoteNG.Connection.ConnectionInitiator.OpenConnection(ConnectionInfo connectionInfo, Force force, ConnectionWindow conForm)

2022.01.07-1.77.2-nb.mRemoteNG.Portable

UVNC server 1.3.8.1

and same error for:

2022.01.07-1.77.2-nb.mRemoteNG.Portable

UVNC server 1.4.0.6

2023-03-08 15:13:44,422 [1] ERROR - Opening connection failed!
Value cannot be null. (Parameter 'stream')
   at System.Drawing.Image.FromStream(Stream stream, Boolean useEmbeddedColorManagement, Boolean validateImageData)
   at System.Drawing.Image.FromStream(Stream stream)
   at VncSharpCore.RemoteDesktop..ctor()
   at mRemoteNG.Connection.Protocol.VNC.ProtocolVNC..ctor()
   at mRemoteNG.Connection.Protocol.ProtocolFactory.CreateProtocol(ConnectionInfo connectionInfo)
   at mRemoteNG.Connection.ConnectionInitiator.OpenConnection(ConnectionInfo connectionInfo, Force force, ConnectionWindow conForm)

[20230303]  https://github.com/mRemoteNG/mRemoteNG/releases/tag/2023.03.03-v1.77.3-nb

UVNC server 1.4.0.6

2023-03-08 15:24:26,006 [1] ERROR - Opening connection failed!
Value cannot be null. (Parameter 'stream')
2023-03-08 15:24:26,015 [1] ERROR - Protocol Event Disconnected failed.
{0}
Unable to cast object of type 'VncSharpCore.RemoteDesktop' to type 'mRemoteNG.Connection.Protocol.ProtocolBase'.
   at mRemoteNG.Connection.ConnectionInitiator.Prot_Event_Disconnected(Object sender, String disconnectedMessage, Nullable`1 reasonCode)
2023-03-08 15:24:26,015 [21] INFO  - Connection Event Closed
2023-03-08 15:24:26,017 [21] INFO  - Connection to pchostname via VNC closed by user myuser6.
2023-03-08 15:24:26,021 [20] INFO  - Connection Event Closed
2023-03-08 15:24:26,022 [20] INFO  - Connection to pchostname via VNC closed by user myuser.
2023-03-08 15:24:27,287 [10] INFO  - Successfully saved connections

**Comment by Kvarkas** [comment]
Hi, @lipoforall could you try latest alfa know as Nightly build for same: https://github.com/mRemoteNG/mRemoteNG/releases/download/2023.03.03-v1.77.3-nb/mRemoteNG-Installer-1.77.3.nb-1784.msi

**Comment by ArchemedIan** [comment]
i am getting 
```
----------
ErrorMsg
03/11/2023 01:48:06
Opening connection failed!
Value cannot be null. (Parameter 'stream')
----------
```
on every version past 1.76.20.24669
i built the source to test, here is output from vs2022
```
DebugMsg: Panel got focused: General
DebugMsg: Tab got focused: New Connection
'mRemoteNG.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.14\System.Security.Cryptography.Csp.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Exception thrown: 'System.ArgumentNullException' in System.Windows.Forms.dll
ErrorMsg: Opening connection failed!
Value cannot be null. (Parameter 'stream')
Exception thrown: 'System.InvalidCastException' in System.Private.CoreLib.dll
'mRemoteNG.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.14\System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'mRemoteNG.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.14\System.Reflection.Metadata.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'mRemoteNG.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.14\System.Collections.Immutable.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
ErrorMsg: Protocol Event Disconnected failed.
{0}
Unable to cast object of type 'VncSharpCore.RemoteDesktop' to type 'mRemoteNG.Connection.Protocol.ProtocolBase'.
   at mRemoteNG.Connection.ConnectionInitiator.Prot_Event_Disconnected(Object sender, String disconnectedMessage, Nullable`1 reasonCode) in C:\Users\neo\Documents\GitHub\mRemoteNG\mRemoteNG\Connection\ConnectionInitiator.cs:line 367
InformationMsg: Connection Event Closed
InformationMsg: Connection to 192.168.50.7 via VNC closed by user neo.

```

**Comment by omarie56** [comment]
Hello,

Just install Mremote NG msi 1.77.3.nb-1784 version, and i'll get the same error message 
Opening connection failed!
Value cannot be null. (Parameter 'stream')

Thanks

**Comment by TimKras** [comment]
Beta version is working for me.

**Comment by femarschall** [comment]
> Hello,
> 
> Just install Mremote NG msi 1.77.3.nb-1784 version, and i'll get the same error message Opening connection failed! Value cannot be null. (Parameter 'stream')
> 
> Thanks

I'm also using  1.77.3.nb-1784  and got the same error

**Comment by nyze88** [comment]
Hi,

some minutes ago I installed MSI version mRemoteNG-Installer-1.77.3.nb-1784.msi and got the same error for my VNC connection :(

**Comment by druidgeek** [comment]
Same. I'm running 1.77.3 NB 1784
I get the "Opening connection failed! Value cannot be null. (Parameter 'stream')" when trying to connect to my tightvnc server on my Ubuntu box. The Password Box displays, but then I get the error after entering the PW.

**Comment by nenny-hash** [comment]
Same issue here

**Comment by pelya1986** [comment]
version 1.77.3 NB 1784
Same. Don't work connect to VNC. 
![image](https://github.com/mRemoteNG/mRemoteNG/assets/94042835/024021a7-eaaf-4477-855d-3bc54bd81939)

**Comment by bcford219** [comment]
@pelya1986 and @TimKras 

Works for me now!

VNC Protocol seems to work fine in version 1.76 but didn't in 1.77. After comparing the .exe.config files between the two versions, one line was present in 1.77 that was not in 1.76. The following string was located in Lines 541-543 of the 1.77 config file. I removed those lines and saved config file (made a copy of the file just in case of course), then launched "MRemoteNG version 1.77" and the VNC conneciton started working right away for me.

NOTE: I honestly don't know if this has broken anything else at the moment. my other connections are still working.

Delete Line 541-543 (mRemoteNG.exe.config file of version 1.77)
-------------------
setting name="ConDefaultUseVmId" serializeAs="String"
     value>False</value
/setting

**Comment by Kvarkas** [comment]
interesting one!

**Comment by Quickerxil** [comment]
Same issue here. Not able to use Stable version because of potential vulnerabilities that has been fixed in Nightly

![2024-02-27 08_29_07-Window](https://github.com/mRemoteNG/mRemoteNG/assets/161429031/3f5289f9-9973-465b-9c1e-15b89f2f7eaa)
![2024-02-27 08_29_25-Window](https://github.com/mRemoteNG/mRemoteNG/assets/161429031/9401bae3-8458-4b85-b4f9-fde941c9bd68)

**Comment by pinkmercedes** [comment]
Same here.
Tried Portable and MSI versions of 1.77.3.1784.
Win10x64.
Can it be fixed somehow?
```
2024-03-06 16:17:24,769 [1] ERROR - Opening connection failed!
Value cannot be null. (Parameter 'stream')
2024-03-06 16:17:24,777 [1] ERROR - Protocol Event Disconnected failed.
{0}
Unable to cast object of type 'VncSharpCore.RemoteDesktop' to type 'mRemoteNG.Connection.Protocol.ProtocolBase'.
   at mRemoteNG.Connection.ConnectionInitiator.Prot_Event_Disconnected(Object sender, String disconnectedMessage, Nullable`1 reasonCode)
```

**Comment by GDB4J** [comment]
Same here with version
mRemoteNG-Installer-1.77.3.nb-1784.msi

![image](https://github.com/mRemoteNG/mRemoteNG/assets/108238720/40c0c6f2-c25f-4e4d-860a-047bb16ca37f)

![image](https://github.com/mRemoteNG/mRemoteNG/assets/108238720/16565c94-478d-410a-9c74-ddfffe53a139)

Can this be fixed please?
Or is there a known work around to get this VNC working on this version?

FYI because of this issue #2019 I need to upgrade to fix this vulnerability...

**Comment by simohauml** [comment]
> @pelya1986 and @TimKras
> 
> Works for me now!
> 
> VNC Protocol seems to work fine in version 1.76 but didn't in 1.77. After comparing the .exe.config files between the two versions, one line was present in 1.77 that was not in 1.76. The following string was located in Lines 541-543 of the 1.77 config file. I removed those lines and saved config file (made a copy of the file just in case of course), then launched "MRemoteNG version 1.77" and the VNC conneciton started working right away for me.
> 
> NOTE: I honestly don't know if this has broken anything else at the moment. my other connections are still working.
> 
> ## Delete Line 541-543 (mRemoteNG.exe.config file of version 1.77)
> setting name="ConDefaultUseVmId" serializeAs="String" value>False</value /setting

Where is this config file? I can't find it.

**Comment by Kvarkas** [comment]
Traveling now with limited access to internet, but should be looking into a bit later this week
> FYI because of this issue #2019 I need to upgrade to fix this vulnerability...

**Comment by Kvarkas** [comment]
Something wrong goes there then its build a pointer, need investigate what exactly is happening, will try to fix before NB new release

**Comment by femarschall** [comment]
I used the mRemoteNG.exe.config from v1.76 but it still didn't work

**Comment by stommy989** [comment]
I've been unable to VNC to a SLES 15 using the default VNC service (TigerVNC) with 1.77.1.27654:

2025-01-08 09:09:37,745 [1] ERROR - Opening connection failed!
Parameter is not valid.
2025-01-08 09:09:37,751 [1] ERROR - Protocol Event Disconnected failed.
{0}
Unable to cast object of type 'VncSharp.RemoteDesktop' to type 'mRemoteNG.Connection.Protocol.ProtocolBase'.
   at mRemoteNG.Connection.ConnectionInitiator.Prot_Event_Disconnected(Object sender, String disconnectedMessage, Nullable`1 reasonCode) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Connection\ConnectionInitiator.cs:line 214
2025-01-08 09:09:37,751 [15] INFO  - Connection Event Closed
2025-01-08 09:09:37,753 [15] INFO  - Connection to x.x.x.x via VNC closed by user xxxxx. <-- I redacted this info.
2025-01-08 09:09:37,756 [14] INFO  - Connection Event Closed

If I use the 1.77.3.1784 NB to the same SLES 15:
Opening connection failed!
Value cannot be null. (Parameter 'stream')

However, I couldn’t find the config/log file to get the full error.

I tried the Delete Line 541-543 suggestion, that didn’t work.

For either version, I was able to VNC OK to a RHEL 9 (also runs TigerVNC). Also able to VNC to various versions of Windows and MacOS OK. I’m able to VNC to the SLES as expected with a different VNC viewer (RealVNC). 

Wondering if this issue may be specific to certain Linux distros, but not sure. 

This also appears to be similar to https://github.com/mRemoteNG/mRemoteNG/issues/2262

**Comment by 2PintChristianN** [comment]
Running and compiling from git

```
Unable to cast object of type 'VncSharp.RemoteDesktop' to type 'mRemoteNG.Connection.Protocol.ProtocolBase'.
at mRemoteNG.Connection.ConnectionInitiator.Prot_Event_Disconnected(Object sender, String disconnectedMessage, Nullable`1 reasonCode)
```
Originate from
```
                _vnc.ConnectionLost += VNCEvent_Disconnected;
```
In `VNCEvent_Disconnected` change
```diff
-Event_Disconnected(sender, @"VncSharp Disconnected.", null);
+Event_Disconnected(this, @"VncSharp Disconnected.", null);
```

But that is just the message after the stream failing. In my case I have
```
System.ArgumentNullException: Value cannot be null. (Parameter 'stream')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at System.Windows.Forms.Cursor..ctor(Stream stream)
   at VncSharpCore.RemoteDesktop.SetState(RuntimeState newState)
   at VncSharpCore.RemoteDesktop.Initialize()
   at VncSharpCore.RemoteDesktop.Connect(String host, Int32 display, Boolean viewOnly, Boolean scaled)
   at VncSharpCore.RemoteDesktop.Connect(String host, Boolean viewOnly, Boolean scaled)
   at mRemoteNG.Connection.Protocol.VNC.ProtocolVNC.Connect() in mRemoteNG\mRemoteNG\Connection\Protocol\VNC\Connection.Protocol.VNC.cs:line 64
```

After change from VncSharpCore package to include the project directly https://github.com/mRemoteNG/VncSharpCore.git it just works, so maybe builds are referencing old versions of VncSharpCore, or no releases done?
I did also change it's target from net60 to net80.

**Comment by robertpopa22** [comment]
Triage refresh (P4 version-label debt): this issue is tagged with legacy version labels. Please retest on the latest build (fork v1.79.x or upstream dev), then share reproducible steps and expected vs actual behavior. If still valid, keep open and relabel to current triage scope (for example Need 2 check). If fixed, close with resolution.

Current legacy version labels: 1.77.3, 1.76.20

**Comment by robertpopa22** [comment]
**Fix available for testing**

**Commit:** `6c110776` (fork `robertpopa22/mRemoteNG`, branch `main`)
**What changed:** VNC connection error

A beta build (v1.81.0-beta.4) including this fix is available from the fork's Releases page.

---

> *We sincerely appreciate the mRemoteNG maintainers and the wonderful community that has kept this project alive and thriving for over a decade. Your work powers thousands of IT professionals worldwide, including us. Our fork builds entirely on your foundation — we're preparing a consolidated Pull Request to contribute these improvements back to the official project. Thank you for everything you've built.*
>
> *— robertpopa22, community contributor*
