### ISSUE TITLE
Cannot access a disposed object. Object name: 'ConnectionWindow'.

### ISSUE THREAD

**Issue by ninja915** [mRemoteNG/mRemoteNG#2355]
While flipping the screen from high res to low res and vice versa the window is very unstable. 

at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Delegate method)
   at mRemoteNG.UI.Window.ConnectionWindow.Prot_Event_Closed(Object sender) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Window\ConnectionWindow.cs:line 0
   at mRemoteNG.Connection.Protocol.ProtocolBase.ClosedEventHandler.Invoke(Object sender)
   at mRemoteNG.Connection.Protocol.ProtocolBase.CloseBG() in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Connection\Protocol\ProtocolBase.cs:line 152

OS: Microsoft Windows NT 10.0.19044.0
mRemoteNG Version: 1.77.0.41252
Edition: MSI
Cmd line args:

**Comment by BlueBlock** [comment]
When you say high res and low res, what specifically are the screen dimensions?

**Comment by ninja915** [comment]
1920x1080,  native laptop screen and another monitor and 3rd one which i generally prefer to use is 3840x2160. i wanted to share some screen shots but looks like i can't
when switching from these 2 windows using the same mremoteng instance the scale goes messed up badly.

**Comment by BlueBlock** [comment]
Thank you for the details. I'll see if I can replicate the issue.

**Comment by simonai1254** [comment]
Do you have scaling enabled in Windows (e.g. 200% on 4K and 125% on the notebook screen)?

**Comment by Kvarkas** [comment]
@rakeshbitsindri could you try for same our nb version 1.77.3?

**Comment by BlueBlock** [comment]
The exception in ProtocolBase.cs was recently resolved and will be included in the next 1.77.3 nightly build.

The scaling issue, I am able to replicate. Investigating a solution.

**Comment by BlueBlock** [comment]
Closing as fixed.
