### ISSUE TITLE
Column 'OpeningCommand' does not belong to table tblCons.

### ISSUE THREAD

**Issue by omarie56** [mRemoteNG/mRemoteNG#2390]
## Expected Behavior
Hello,
just want to update MremoteNG 1.77.2.41 to 1.77.3_NB
In sql server TAb option, i just indicate information to connect my mremonteng Mysql database with content

## Current Behavior
The connexion indicate it's Ok but when i clicl on Apply button i have an error windows tha appears (see below)

is there an sql script to apply to update database schema in order to be compatible with last mremonteng version ?

```
Message de l'exception
"Column 'OpeningCommand' does not belong to table tblCons."

Pile d'appels
   at System.Data.DataRow.GetDataColumn(String columnName)
   at System.Data.DataRow.get_Item(String columnName)
   at mRemoteNG.Config.Serializers.ConnectionSerializers.MsSql.DataTableDeserializer.PopulateConnectionInfoFromDatarow(DataRow dataRow, ConnectionInfo connectionInfo)
   at mRemoteNG.Config.Serializers.ConnectionSerializers.MsSql.DataTableDeserializer.DeserializeContainerInfo(DataRow row)
   at mRemoteNG.Config.Serializers.ConnectionSerializers.MsSql.DataTableDeserializer.CreateNodesFromTable(DataTable table)
   at mRemoteNG.Config.Serializers.ConnectionSerializers.MsSql.DataTableDeserializer.Deserialize(DataTable table)
   at mRemoteNG.Config.Connections.SqlConnectionsLoader.Load()
   at mRemoteNG.Connection.ConnectionsService.LoadConnections(Boolean useDatabase, Boolean import, String connectionFileName)
   at mRemoteNG.UI.Forms.OptionsPages.SqlServerPage.ReinitializeSqlUpdater()
   at mRemoteNG.UI.Forms.OptionsPages.SqlServerPage.SaveSettings()
   at mRemoteNG.UI.Forms.FrmOptions.BtnOK_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

Environnement
OS: Microsoft Windows NT 10.0.19045.0
mRemoteNG Version: 1.77.3
Edition: Portable
Cmd line args: 

```

**Comment by sarog** [comment]
Indeed, I just spent 3+ hours fixing the database schema myself. Here is my _crusty_ migration SQL script (tested on MariaDB 10.4) in case you're still stuck. This will upgrade you from schema 2.8 to 3.0 but beware that mRemoteNG doesn't seem to like anything beyond 2.9 (complains about an incompatible schema version).

**Don't forget to backup your database before running this script.**

```sql
-- These were removed a while ago IIRC, but somehow are back in the schema:
alter table tblcons add ICAEncryptionStrength varchar(32) not null after VmId;
alter table tblcons add InheritICAEncryptionStrength tinyint(1) not null after InheritFavorite;

-- pre 2.8, might already be applied:
alter table tblcons modify RenderingEngine varchar(16) null;

-- 2.8 to 2.9
ALTER TABLE tblCons MODIFY COLUMN `InheritUseRestrictedAdmin` tinyint(1) NOT NULL;
ALTER TABLE tblCons MODIFY COLUMN `UseRCG` tinyint(1) NOT NULL;
ALTER TABLE tblCons MODIFY COLUMN `UseRestrictedAdmin` tinyint(1) NOT NULL;
ALTER TABLE tblCons MODIFY COLUMN `InheritUseRCG` tinyint(1) NOT NULL;
ALTER TABLE tblCons MODIFY COLUMN `InheritRDGatewayExternalCredentialProvider` tinyint(1) NOT NULL;
ALTER TABLE tblCons MODIFY COLUMN `InheritRDGatewayUserViaAPI` tinyint(1) NOT NULL;
ALTER TABLE tblCons MODIFY COLUMN `InheritExternalCredentialProvider` tinyint(1) NOT NULL;
ALTER TABLE tblCons MODIFY COLUMN `InheritUserViaAPI` tinyint(1) NOT NULL;
ALTER TABLE tblCons MODIFY COLUMN `EC2Region` varchar(32) DEFAULT NULL;
ALTER TABLE tblCons MODIFY COLUMN `EC2InstanceId` varchar(32) DEFAULT NULL;
ALTER TABLE tblCons MODIFY COLUMN `ExternalCredentialProvider` varchar(256) DEFAULT NULL;
ALTER TABLE tblCons MODIFY COLUMN `ExternalAddressProvider` varchar(256) DEFAULT NULL;

SET SQL_SAFE_UPDATES=0;
UPDATE tblCons SET InheritUseEnhancedMode = 0 WHERE InheritUseEnhancedMode IS NULL;
ALTER TABLE tblCons MODIFY COLUMN InheritUseEnhancedMode tinyint(1) NOT NULL;
UPDATE tblCons SET UseEnhancedMode = 0 WHERE UseEnhancedMode IS NULL;
ALTER TABLE tblCons MODIFY COLUMN UseEnhancedMode tinyint(1) NOT NULL;
UPDATE tblCons SET InheritVmId = 0 WHERE InheritVmId IS NULL;
ALTER TABLE tblCons MODIFY COLUMN InheritVmId tinyint(1) NOT NULL;
UPDATE tblCons SET InheritUseVmId = 0 WHERE InheritUseVmId IS NULL;
ALTER TABLE tblCons MODIFY COLUMN InheritUseVmId tinyint(1) NOT NULL;
UPDATE tblCons SET UseVmId = 0 WHERE UseVmId IS NULL;
ALTER TABLE tblCons MODIFY COLUMN UseVmId tinyint(1) NOT NULL;
SET SQL_SAFE_UPDATES=1;

-- 2.9 to 3.0
ALTER TABLE tblCons ADD COLUMN `InheritRedirectDiskDrivesCustom` tinyint(1) NOT NULL;
ALTER TABLE tblCons ADD COLUMN `OpeningCommand` varchar(512) NOT NULL;
ALTER TABLE tblCons ADD COLUMN `InheritOpeningCommand` tinyint(1) NOT NULL;
ALTER TABLE tblCons ADD COLUMN `UserViaAPI` varchar(512) NOT NULL;

-- Note: DataTableDeserializer fails on null, so the following 4 changes differ from the stock schema:
ALTER TABLE tblCons ADD COLUMN `StartProgram` varchar(512) DEFAULT '' NOT NULL;
ALTER TABLE tblCons ADD COLUMN `StartProgramWorkDir` varchar(512) DEFAULT '' NOT NULL;
ALTER TABLE tblCons MODIFY COLUMN `RedirectDiskDrives` varchar(32) DEFAULT '' NOT NULL;
ALTER TABLE tblCons ADD COLUMN `RedirectDiskDrivesCustom` varchar(32) DEFAULT '' NOT NULL;

-- Update the schema version:
ALTER TABLE tblRoot MODIFY COLUMN `ConfVersion` VARCHAR(15) NOT NULL;
UPDATE tblRoot SET ConfVersion='3.0' WHERE Name = 'Connections';
```

Also, it seems like #2395 also introduced a number of issues as well. The above schema changes include a workaround for it.

Let me know if you are still receiving errors after applying these changes as I may have omitted 1 or 2 last minute fixes.

**Opinion**: This project really needs to look into a database migration framework (e.g. [flyway](https://github.com/flyway/flyway)) to avoid these issues.

**Comment by BlueBlock** [comment]
I think I've resolved all those issues. 

Thanks for the flyway suggestion.. I'll take a look. The current implementation is definitely difficult to maintain and change.

I'll look at your "column updates where NULL" since that should likely be included for the SQL 3.0 database schema update.

https://github.com/mRemoteNG/mRemoteNG/pull/2399

**Comment by sarog** [comment]
Flyway is great: it's written in Java, but it'll work with any system. However, since mRemoteNG is written in C#, an alternative and better solution might be the [Entity Framework](https://learn.microsoft.com/en-us/ef/) by Microsoft as it includes [database migrations](https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/?tabs=dotnet-core-cli).

I appreciate your contributions to this project!

**Comment by BlueBlock** [comment]
Thanks sarog. There is definitely better ways to handle the schemas, but it will be a task after getting everything fixed.

I've also found the Drives PR updated the xml schema to 2.8 but all tests still refer to 2.7
Working to get it all fixed and the unit tests running clean.

**Comment by BlueBlock** [comment]
Closing this but re-open it if the solution doesn't seem complete.
