### ISSUE TITLE
MySQL database connection needs a table

### ISSUE THREAD

**Issue by KeinSupporter** [mRemoteNG/mRemoteNG#2429]
As soon as I want to create a new database connection via MySQL, this error message appears after the connection test (see screenshot)

Version: v1.77.3.1442-NB

![Screenshot 2023-04-25 113307](https://user-images.githubusercontent.com/131761636/234238547-3db14379-77a2-4dc7-9145-619275c7d387.png)

```
Fehlermeldung
"Table 'mRemoteNG.tblRoot' doesn't exist"

Stack trace
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at mRemoteNG.Config.Serializers.ConnectionSerializers.MsSql.SqlDatabaseMetaDataRetriever.GetDatabaseMetaData(IDatabaseConnector databaseConnector)
   at mRemoteNG.Config.Connections.SqlConnectionsLoader.Load()
   at mRemoteNG.Connection.ConnectionsService.LoadConnections(Boolean useDatabase, Boolean import, String connectionFileName)
   at mRemoteNG.UI.Forms.OptionsPages.SqlServerPage.ReinitializeSqlUpdater()
   at mRemoteNG.UI.Forms.OptionsPages.SqlServerPage.SaveSettings()
   at mRemoteNG.UI.Forms.FrmOptions.BtnOK_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

Environment
OS: Microsoft Windows NT 10.0.22621.0
mRemoteNG Version: 1.77.3
Edition: Portable
Cmd line args: 

```

**Comment by drdobler** [comment]
See here
https://github.com/mRemoteNG/mRemoteNG/issues/2425

They removed the SQL script from the documentation that sets up your DB. But no one seems to care about it...

**Comment by KeinSupporter** [comment]
Thank you for your advice!

**Comment by Kvarkas** [comment]
we have fix in newest code, it will create required tables

**Comment by TARLoki** [comment]
Hello together,

on my Database the issue already exists.
I created an empty database.
Imported my old xml connection file to the mRemoteNG software.
Entered under Options the server information and get the same issue like at the old version.

Is there any information where I will find the script, where you are talking about and how I can use it?

here is the error Message:
```
Fehlermeldung
"Invalid object name 'tblRoot'."

Stack trace
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at mRemoteNG.Config.Serializers.ConnectionSerializers.MsSql.SqlDatabaseMetaDataRetriever.GetDatabaseMetaData(IDatabaseConnector databaseConnector)
   at mRemoteNG.Config.Connections.SqlConnectionsLoader.Load()
   at mRemoteNG.Connection.ConnectionsService.LoadConnections(Boolean useDatabase, Boolean import, String connectionFileName)
   at mRemoteNG.UI.Forms.OptionsPages.SqlServerPage.ReinitializeSqlUpdater()
   at mRemoteNG.UI.Forms.OptionsPages.SqlServerPage.SaveSettings()
   at mRemoteNG.UI.Forms.FrmOptions.BtnOK_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

Environment
OS: Microsoft Windows NT 10.0.19045.0
mRemoteNG Version: 1.77.3
Edition: Portable
Cmd line args: 

```

**Comment by KeinSupporter** [comment]
> Hello together,
> 
> on my Database the issue already exists. I created an empty database. Imported my old xml connection file to the mRemoteNG software. Entered under Options the server information and get the same issue like at the old version.
> 
> Is there any information where I will find the script, where you are talking about and how I can use it?
> 
> here is the error Message:
> 
> ```
> Fehlermeldung
> "Invalid object name 'tblRoot'."
> 
> Stack trace
>    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
>    at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
>    at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
>    at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
>    at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
>    at System.Data.SqlClient.SqlDataReader.get_MetaData()
>    at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
>    at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
>    at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)
>    at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
>    at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
>    at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
>    at System.Data.Common.DbCommand.ExecuteReader()
>    at mRemoteNG.Config.Serializers.ConnectionSerializers.MsSql.SqlDatabaseMetaDataRetriever.GetDatabaseMetaData(IDatabaseConnector databaseConnector)
>    at mRemoteNG.Config.Connections.SqlConnectionsLoader.Load()
>    at mRemoteNG.Connection.ConnectionsService.LoadConnections(Boolean useDatabase, Boolean import, String connectionFileName)
>    at mRemoteNG.UI.Forms.OptionsPages.SqlServerPage.ReinitializeSqlUpdater()
>    at mRemoteNG.UI.Forms.OptionsPages.SqlServerPage.SaveSettings()
>    at mRemoteNG.UI.Forms.FrmOptions.BtnOK_Click(Object sender, EventArgs e)
>    at System.Windows.Forms.Control.OnClick(EventArgs e)
>    at System.Windows.Forms.Button.OnClick(EventArgs e)
>    at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
>    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.ButtonBase.WndProc(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
> 
> Environment
> OS: Microsoft Windows NT 10.0.19045.0
> mRemoteNG Version: 1.77.3
> Edition: Portable
> Cmd line args: 
> ```

Hey, I had the same problem. Unfortunately, the developer removed the SQL script from the website. But you can still find it on Archive.org.

https://web.archive.org/web/20220709193121/https://mremoteng.readthedocs.io/en/latest/sql_configuration.html

**Comment by mraksus** [comment]
The script worked like a charm - isn't there any way to add it to the repository? It's kinda weird we're forced to copy it from the waybackmachine

**Comment by robertpopa22** [comment]
Triage refresh (P4 version-label debt): this issue is tagged with legacy version labels. Please retest on the latest build (fork v1.79.x or upstream dev), then share reproducible steps and expected vs actual behavior. If still valid, keep open and relabel to current triage scope (for example Need 2 check). If fixed, close with resolution.

Current legacy version labels: 1.77.3

**Comment by robertpopa22** [comment]
**Update from fork `robertpopa22/mRemoteNG`**

Fixed. Added `UpgradeMysqlSchema` that auto-discovers missing columns from the expected schema and creates them automatically. Both MSSQL and MySQL backends now self-heal on startup.

Available in **[CENSORED!] Links to external GitHub repositories are not allowed** and included in **[CENSORED!] Links to external GitHub repositories are not allowed**.
