### ISSUE TITLE
When clicking Tools Options unhandled exception occured.

### ISSUE THREAD

**Issue by rmothers** [mRemoteNG/mRemoteNG#2443]
```
Exception Message
"Decryption failed. {0}"

Stack trace
   at mRemoteNG.Security.SymmetricEncryption.LegacyRijndaelCryptographyProvider.Decrypt(String ciphertextBase64, SecureString password) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Security\SymmetricEncryption\LegacyRijndaelCryptographyProvider.cs:line 107
   at mRemoteNG.UI.Forms.OptionsPages.CredentialsPage.LoadSettings() in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Forms\OptionsPages\CredentialsPage.cs:line 52
   at mRemoteNG.UI.Forms.FrmOptions.AddOptionsPagesToListView() in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Forms\FrmOptions.cs:line 92
   at mRemoteNG.UI.Forms.FrmOptions.frmOptions_Load(Object sender, EventArgs e) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Forms\FrmOptions.cs:line 34
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Environment
OS: Microsoft Windows NT 10.0.22000.0
mRemoteNG Version: 1.77.1.27654
Edition: MSI
Cmd line args: 

```

**Comment by Kvarkas** [comment]
please check nightly version, this one not supported
https://mremoteng.org/download

**Comment by rmothers** [comment]
That fixed it, thank you .


Rodney Mothersbaugh
Senior Systems Engineer
MedRisk
800-225-9675 ext. (1051)
***@***.******@***.***>
