### ISSUE TITLE
Character set 'utf8mb3' is not supported by .Net Framework.

### ISSUE THREAD

**Issue by Nils98Ar** [mRemoteNG/mRemoteNG#2494]
The exception occurs when saving the mysql connection.

**Mariadb/OS:** `Server version: 10.11.3-MariaDB-1-log Debian 12`

**Stack Trace:**
```
   at MySql.Data.MySqlClient.CharSetMap.GetCharacterSet(DBVersion version, String charSetName)
   at MySql.Data.MySqlClient.MySqlField.SetFieldEncoding()
   at MySql.Data.MySqlClient.MySqlField.set_CharacterSetIndex(Int32 value)
   at MySql.Data.MySqlClient.NativeDriver.GetColumnData(MySqlField field)
   at MySql.Data.MySqlClient.NativeDriver.GetColumnsData(MySqlField[] columns)
   at MySql.Data.MySqlClient.Driver.GetColumns(Int32 count)
   at MySql.Data.MySqlClient.ResultSet.LoadColumns(Int32 numCols)
   at MySql.Data.MySqlClient.ResultSet..ctor(Driver d, Int32 statementId, Int32 numCols)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlDataReader.Close()
   at MySql.Data.MySqlClient.MySqlCommand.ResetReader()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at mRemoteNG.Config.Serializers.ConnectionSerializers.MsSql.SqlDatabaseMetaDataRetriever.GetDatabaseMetaData(IDatabaseConnector databaseConnector)
   at mRemoteNG.Config.Connections.SqlConnectionsLoader.Load()
   at mRemoteNG.Connection.ConnectionsService.LoadConnections(Boolean useDatabase, Boolean import, String connectionFileName)
   at mRemoteNG.UI.Forms.OptionsPages.SqlServerPage.ReinitializeSqlUpdater()
   at mRemoteNG.UI.Forms.OptionsPages.SqlServerPage.SaveSettings()
   at mRemoteNG.UI.Forms.FrmOptions.BtnOK_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```
**Environment:**
```
OS: Microsoft Windows NT 10.0.19044.0
mRemoteNG Version: 1.77.2
Edition: MSI
Cmd line args: 
```

**Comment by LeonS13** [comment]
If mRemoteNG is trying to store real UTF8 data then this should be utf8mb4 as real UTF8 needs 4 bytes of space and not 3. This will cause errors only if there is something you try to save that will not fit in 3 bytes. You will find this plastered all over the internet because MySQL used the wrong term UTF8 which meant UTF8MB3. At some version they changed this because it kept causing problems with developers who did not know about the problem.

**Comment by powerscooter** [comment]
Hi all,
i have the same issue.

Has someone a temporary solution?

<img width="622" alt="image" src="https://github.com/mRemoteNG/mRemoteNG/assets/18429672/b51db75d-5224-4577-9b79-77d9af5689d2">

Windows Server 2022

**Comment by ph1046** [comment]
Same Issue here:

Server: Debian 12
MariaDB Version: 10.11.4-MariaDB

Client: Windows 10 22H2 LTSC
Mremote: 1.77.2 - portable 
Also tested with the actual nightly build

Character set 'utf8mb3' is not supported by .Net Framework.


`  bei MySql.Data.MySqlClient.CharSetMap.GetCharacterSet(DBVersion version, String charSetName)
   bei MySql.Data.MySqlClient.MySqlField.SetFieldEncoding()
   bei MySql.Data.MySqlClient.NativeDriver.GetColumnData(MySqlField field)
   bei MySql.Data.MySqlClient.NativeDriver.GetColumnsData(MySqlField[] columns)
   bei MySql.Data.MySqlClient.Driver.GetColumns(Int32 count)
   bei MySql.Data.MySqlClient.ResultSet.LoadColumns(Int32 numCols)
   bei MySql.Data.MySqlClient.ResultSet..ctor(Driver d, Int32 statementId, Int32 numCols)
   bei MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   bei MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   bei MySql.Data.MySqlClient.MySqlDataReader.Close()
   bei MySql.Data.MySqlClient.MySqlCommand.ResetReader()
   bei MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   bei MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   bei System.Data.Common.DbCommand.ExecuteReader()
   bei mRemoteNG.Config.Serializers.ConnectionSerializers.MsSql.SqlDatabaseMetaDataRetriever.GetDatabaseMetaData(IDatabaseConnector databaseConnector) in D:\Work\mRemoteNG\Branch Dev\mRemoteNG\Config\Serializers\ConnectionSerializers\MsSql\SqlDatabaseMetaDataRetriever.cs:Zeile 45.
   bei mRemoteNG.Config.Connections.SqlConnectionsLoader.Load() in D:\Work\mRemoteNG\Branch Dev\mRemoteNG\Config\Connections\SqlConnectionsLoader.cs:Zeile 47.
   bei mRemoteNG.Connection.ConnectionsService.LoadConnections(Boolean useDatabase, Boolean import, String connectionFileName) in D:\Work\mRemoteNG\Branch Dev\mRemoteNG\Connection\ConnectionsService.cs:Zeile 137.
   bei mRemoteNG.UI.Forms.OptionsPages.SqlServerPage.ReinitializeSqlUpdater() in D:\Work\mRemoteNG\Branch Dev\mRemoteNG\UI\Forms\OptionsPages\SqlServerPage.cs:Zeile 83.
   bei mRemoteNG.UI.Forms.OptionsPages.SqlServerPage.SaveSettings() in D:\Work\mRemoteNG\Branch Dev\mRemoteNG\UI\Forms\OptionsPages\SqlServerPage.cs:Zeile 73.
   bei mRemoteNG.UI.Forms.FrmOptions.BtnOK_Click(Object sender, EventArgs e) in D:\Work\mRemoteNG\Branch Dev\mRemoteNG\UI\Forms\FrmOptions.cs:Zeile 132.
   bei System.Windows.Forms.Control.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ButtonBase.WndProc(Message& m)
   bei System.Windows.Forms.Button.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

**Comment by robertpopa22** [comment]
**Fix available for testing**

A fix for this issue has been implemented in our community fork (`robertpopa22/mRemoteNG`, branch `main`). A beta build including this fix is available from the fork's Releases page.

Please test and report if this resolves your issue.

---

> *We sincerely appreciate the mRemoteNG maintainers and the wonderful community that has kept this project alive and thriving for over a decade. Your work powers thousands of IT professionals worldwide, including us. Our fork builds entirely on your foundation — we're preparing a consolidated Pull Request to contribute these improvements back to the official project. Thank you for everything you've built.*
>
> *— robertpopa22, community contributor*
