### ISSUE TITLE
COM object that has been separated from its underlying RCW cannot be used.

### ISSUE THREAD

**Issue by tecxx** [mRemoteNG/mRemoteNG#2510]
When moving the mRemoteNG main window it goes from full screen to window size. 

If there is an active RDP connection, the following error pops up:

![image](https://github.com/mRemoteNG/mRemoteNG/assets/4305825/6b7dcd3b-c8eb-4237-806a-787275b4e2af)

   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at MSTSCLib.IMsRdpClient6.get_AdvancedSettings2()
   at mRemoteNG.Connection.Protocol.RDP.RdpProtocol.get_SmartSize() in C:\SVN\mRemote\mRemoteNG\Connection\Protocol\RDP\RdpProtocol.cs:line 54
   at mRemoteNG.Connection.Protocol.RDP.RdpProtocol8.DoResizeClient() in C:\SVN\mRemote\mRemoteNG\Connection\Protocol\RDP\RdpProtocol8.cs:line 91
   at mRemoteNG.Connection.Protocol.RDP.RdpProtocol8.ResizeEnd(Object sender, EventArgs e) in C:\SVN\mRemote\mRemoteNG\Connection\Protocol\RDP\RdpProtocol8.cs:line 71
   at System.Windows.Forms.Form.OnResizeEnd(EventArgs e)
   at System.Windows.Forms.Form.WmExitSizeMove(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at mRemoteNG.UI.Forms.FrmMain.WndProc(Message& m) in C:\SVN\mRemote\mRemoteNG\UI\Forms\frmMain.cs:line 599
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

when clicking "close" the connection continues to work fine, nothing else happens.

**Comment by robertpopa22** [comment]
Triage refresh (P4 version-label debt): this issue is tagged with legacy version labels. Please retest on the latest build (fork v1.79.x or upstream dev), then share reproducible steps and expected vs actual behavior. If still valid, keep open and relabel to current triage scope (for example Need 2 check). If fixed, close with resolution.

Current legacy version labels: 1.77.3

**Comment by robertpopa22** [comment]
Update from fork release track (v1.79 bootstrap): candidate fix is packaged in PR #3119.  
  
PR: PR #3119 on `mRemoteNG/mRemoteNG`  
Fork CI validation: CI run 21793657159 on `robertpopa22/mRemoteNG`  
  
Patch scope:  
- harden SmartSize COM access against RCW-disconnected state  
- skip resize if RDP control is disposed/unavailable  
  
Please review and relabel/close when verified on upstream branch.

---

> *We sincerely appreciate the mRemoteNG maintainers and the wonderful community that has kept this project alive and thriving for over a decade. Your work powers thousands of IT professionals worldwide, including us. Our fork builds entirely on your foundation — we're preparing a consolidated Pull Request to contribute these improvements back to the official project. Thank you for everything you've built.*
>
> *— robertpopa22, community contributor*

**Comment by robertpopa22** [comment]
**Fix available in community release**

This fix is included in a community build from our fork (`robertpopa22/mRemoteNG`, branch `main`). Available from the fork's Releases page.

Please test and let us know if the issue is fully resolved.

---

> *We sincerely appreciate the mRemoteNG maintainers and the wonderful community that has kept this project alive and thriving for over a decade. Your work powers thousands of IT professionals worldwide, including us. Our fork builds entirely on your foundation — we're preparing a consolidated Pull Request to contribute these improvements back to the official project. Thank you for everything you've built.*
>
> *— robertpopa22, community contributor*
