### ISSUE TITLE
Faulting application name: mRemoteNG.exe, version: 1.76.20.24669 (Windows11 Pro) - Update Checker

### ISSUE THREAD

**Issue by wincentblack** [mRemoteNG/mRemoteNG#2541]
The program just does not want open, it starts open and then close, I did not install any new app or Windows update in logs I se the next eror:

`Application: mRemoteNG.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.ThrowHelper.ThrowArgumentException(System.ExceptionResource)
   at System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Insert(System.__Canon, System.__Canon, Boolean)
   at System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Add(System.__Canon, System.__Canon)
   at mRemoteNG.App.Update.UpdateFile.FromString(System.String)
   at mRemoteNG.App.Update.UpdateFile..ctor(System.String)
   at mRemoteNG.App.Update.UpdateInfo.FromString(System.String)
   at mRemoteNG.App.Update.AppUpdater.GetUpdateInfo()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

`
>>
`Faulting application name: mRemoteNG.exe, version: 1.76.20.24669, time stamp: 0x5cb095bd
Faulting module name: KERNELBASE.dll, version: 10.0.22621.2861, time stamp: 0x9e57f18c
Exception code: 0xe0434352
Fault offset: 0x00149392
Faulting process id: 0x0x586C
Faulting application start time: 0x0x1DA3AFFDA3BC8AC
Faulting application path: C:\Users\master\Downloads\mRemoteNG-Portable-1.76.20.24669-RSLOAD.NET-\mRemoteNG-Portable-1.76.20.24669-RSLOAD.NET-\mRemoteNG.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 90b9431b-245f-4d60-9474-53d71f3eb71f
Faulting package full name: 
Faulting package-relative application ID: `

What can be a reason of this?
I also tried reinstal it and remove user configs, but did not luck
`%APPDATA%\mRemoteNG
%LOCALAPPDATA%\mRemoteNG`

## Your Environment

`Edition	Windows 11 Pro
Version	22H2
OS build	22621.2861
Experience	Windows Feature Experience Pack 1000.22681.1000.0
`

**Comment by wincentblack** [comment]
The same situation after update to new version:
```
Exception Message
"An item with the same key has already been added."

Stack trace
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at mRemoteNG.App.Update.UpdateFile.FromString(String content) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\App\Update\UpdateFile.cs:line 57
   at mRemoteNG.App.Update.UpdateFile..ctor(String content) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\App\Update\UpdateFile.cs:line 22
   at mRemoteNG.App.Update.UpdateInfo.FromString(String input) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\App\Update\UpdateInfo.cs:line 32
   at mRemoteNG.App.Update.AppUpdater.GetUpdateInfo() in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\App\Update\AppUpdater.cs:line 247
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Environment
OS: Microsoft Windows NT 10.0.22621.0
mRemoteNG Version: 1.77.1.27654
Edition: MSI
Cmd line args: 

```

**Comment by DocMoebiuz** [comment]
Same problem for me.

```

**Comment by DocMoebiuz** [comment]
Same

```
Application: mRemoteNG.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.ThrowHelper.ThrowArgumentException(System.ExceptionResource)
   at System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Insert(System.__Canon, System.__Canon, Boolean)
   at System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Add(System.__Canon, System.__Canon)
   at mRemoteNG.App.Update.UpdateFile.FromString(System.String)
   at mRemoteNG.App.Update.UpdateFile..ctor(System.String)
   at mRemoteNG.App.Update.UpdateInfo.FromString(System.String)
   at mRemoteNG.App.Update.AppUpdater.GetUpdateInfo()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by DocMoebiuz** [comment]
I think it might be because their website is down... it looks like the exception is raised when checnking for the latest version.

``` at mRemoteNG.App.Update.AppUpdater.GetUpdateInfo()```

I will try to disable my internet connection while starting.

**Comment by DocMoebiuz** [comment]
Ok... that did the trick for me:

* Disable internet
* Start mRemotNG
* Enable Internet again

Optionally: 
* Disable check for update on start
<img width="586" alt="image" src="https://github.com/mRemoteNG/mRemoteNG/assets/86157512/ee3f36f5-b134-48b0-b8da-a387da83c33e">


But I would assume this is a temporary issue as long as their website is down.

**Comment by zanna241** [comment]
> Ok... that did the trick for me:
> 
> * Disable internet
> * Start mRemotNG
> * Enable Internet again
> 
> Optionally:
> 
> * Disable check for update on start
> 
> <img alt="image" width="586" src="https://private-user-images.githubusercontent.com/86157512/293455001-ee3f36f5-b134-48b0-b8da-a387da83c33e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MzI4NzgsIm5iZiI6MTcwMzkzMjU3OCwicGF0aCI6Ii84NjE1NzUxMi8yOTM0NTUwMDEtZWUzZjM2ZjUtYjEzNC00OGIwLWI4ZGEtYTM4N2RhODNjMzNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDEwMzYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3ZThiYmQwNjY5ZTNjNzU5YjdlOGFhYTExNjg4NGRhYmFjNzU2YmZmYTQ5MzZiNzBmZmZlODdkOTMwYzQxNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UOvEJVnaqvIDnO4jxu-SpOMZe22Zf1_l29t-qdxESmI">
> But I would assume this is a temporary issue as long as their website is down.

working for me!!

**Comment by mgoegel** [comment]
Same here and quickly had the same idea, that it is due to the website, which I checked first...
This might be a bug report, if the response from the update url is not as expected.

**Comment by tolewhite** [comment]
> Same here and quickly had the same idea, that it is due to the website, which I checked first... This might be a bug report, if the response from the update url is not as expected.

The workaround is working. No internet, then disable check for updates.  It definitely should be a bug report. The app should never depend on an external site with no error handling in case it was ever offline.

**Comment by alvinlgs** [comment]
I encountered the same issue. Here's what I did:

1. Delete the configuration file
(%LOCALAPPDATA%\mRemoteNG\<most recently updated folder>\<mRemoteNG version>\user.config)
2. Uninstall
3. Install the latest stable build
4. Customise Settings on the first start to disable auto update

**Comment by rhodester** [comment]
Same problem for me on Win 10 Pro.
I preferred to keep my config file settings so I rather did the following.

1.  Open / Edit   %LOCALAPPDATA%\mRemoteNG\<most recently updated folder>\<mRemoteNG version>\user.config
2.  Search for "CheckForUpdatesOnStartup" and change to "False".

**Comment by wincentblack** [comment]
> I think it might be because their website is down... it looks like the exception is raised when checnking for the latest version.
> 
> ` at mRemoteNG.App.Update.AppUpdater.GetUpdateInfo()`
> 
> I will try to disable my internet connection while starting.

Thanks for tips!  it did a trick, nice catch

**Comment by DocMoebiuz** [comment]
it's not limited to win 10

**Comment by DocMoebiuz** [comment]
@wincentblack wjx did you decide to close this issue in favor of the other one if this one here contains specific steps for a work around?

there should be an issue created now that says: **don't fail on start up when check for update URL not available / returning correct response**

**Comment by Kvarkas** [comment]
Sorry for that! Domain relocation in progress, but that for sure a bug, will make a change so in feature if domain not availbale it will not generate an error.

**Comment by simonai1254** [comment]
> Sorry for that! Domain relocation in progress, but that for sure a bug, will make a change so in feature if domain not availbale it will not generate an error.

Note sure if it's a resolving issue or that the page is not responding with a 200 message, because the website (to me) was displaying a dummy Squarespace page while reports were coming in...

**Comment by Kvarkas** [comment]
yes, its 3 steps process, relocation to new hoster, then all that started, then new hoster acepted, second step was to set dns records to github that they say takes up to 24h, what you see now is new hoster temporary page, once Github finished its verefication (what ever they do) it should start pointing to github pages where all data is stored and work will be normilised :) its tought change so was selected festive time to have less impact on users. But wasnt expected it impact that way! 
![image](https://github.com/mRemoteNG/mRemoteNG/assets/3611964/9cf3ee1c-e200-417e-9c67-075e1f1df6d8)

**Comment by simonai1254** [comment]
The website is back online, I was able to start 1.76.20 without experiencing any issue. 

I guess the problem was, that even though the queried URL got resolved it returned something unexpected, which was not handled correctly by the tool.
This needs to be investigated further and get fixed in the newer versions as it cannot be that the tools stops working just because an unexpected answer is returned by the webserver. The "Disabling the network" and "Hosts-File Redirect" workarounds indicate to me that it's not domain unreachable thing but more related to what Squarespace replied with to the query from the tool.

**Comment by Kvarkas** [comment]
it could be not finished for all regions, but I am sure it will till morning :) complete usualy in 24h, 15 already pass :) 
In fact its coded a bit rude way its explicitly requested data and have no any handler if data will not received - so its crashed. Will definitely work on such, should be easy fix.

**Comment by simonai1254** [comment]
So I looked a little into this and I stumpled across issue #1959 which seems to support my theory of the update handler not being able to parse anything else but plain text replies from the webserver. You should check if the merge #1960 (into 1.77.3) actually solves this issue.
Also in my research I found #1533 which already documented the workaround of disabling the Update Check.
Lastly https://github.com/mRemoteNG/mRemoteNG/issues/527#issuecomment-297805054 gives some interesting insight in the URLs the updater tries to access, maybe this helps isolating the true issue.

@Kvarkas I guess we should proceed with making one issue (I suppose this one as it now holds most information) the main one and closing the related (/duplicate) issues in favor of having all discussions on one place. I identified following issues being based on the same problem (inlcuding the ones mentioned above): 

- #527
- #1533 
- #1839 
- #1937 
- #1959
- #1960
- #2541
- #2542
- #2543
- #2544

**Comment by Kvarkas** [comment]
will be celebrating new year tomorrow so back to work on this from 2nd of January. Yes good idea to aggregate into one and close others. Thanks for such.

**Comment by simonai1254** [comment]
Reopening this as the main issue for update related problems (to minimize duplicates), though it looks as if the updater already was rewritten since the issue was opened and therefore the bug might no longer exists in v1.77.+

**Comment by simonai1254** [comment]
The issue within #1853 with older versions being returned than actually is installed is still present with 1.78.2 NB 3207, so this shall be kept in focus.

**Comment by Kvarkas** [comment]
how you recreate an issue as i not able to?

**Comment by simonai1254** [comment]
> how you recreate an issue as i not able to?

You are not able to what?

I consider this the main issue for the Update Checker, this includes #1853. And I just verified that if I download and run mRemoteNG 1.78.2-3207 and check for updates I still get "Update Available, Current Version is 1.76.11, you are running 1.78.2-3207") which is obviously incorrect. Therefore the update checker needs to be worked on so that works correctly and also takes the release channels properly into account.

**Comment by Kvarkas** [comment]
what already fixed, however we have more channels perhaps worth to add a channel switcher, but original issue is not about that, we could bury this one as in NB version it will be different and older versions are not supouse to be supported. 

to explain a bit wider :) 
we have curently 3 channels: Release / Release Candidate / Nigh Build 
Because curent actual version is NB, once we push it into Release Candidate and a bit late to Release it will push out older version, however for now its shows correctly but dost show for what channel :) For Release channel - 1.76.11 still correct

**Comment by simonai1254** [comment]
Agree, will close this one, and keep #1853 for itself. 

AFAIK release should be 1.76.20 though and not 1.76.11 though
