### ISSUE TITLE
mRemoteNG Crashing at Start Up

### ISSUE THREAD

**Issue by rsford31** [mRemoteNG/mRemoteNG#2544]
After rebooting my computer (was being slow), when I tried to run mRemoteNG it would load then shut down. I deleted the user.config file from C:\Users\_user_\AppData\Local\mRemoteNG\mRemoteNG.exe_Url_pjpxdehxpaaorqg2thmuhl11a34i3ave\1.76.20.24615

Tried launching mRemoteNG again with the same result. 

The logs show:
XmingPortablePuttySessions.Watcher.StartWatching() failed: 'sessions' does not exist.

Event Viewer:
Faulting application name: mRemoteNG.exe, version: 1.76.20.24615, time stamp: 0x5cb09552
Faulting module name: KERNELBASE.dll, version: 10.0.19041.3693, time stamp: 0x64ee7a9c
Exception code: 0xe0434352
Fault offset: 0x0013f932
Faulting process id: 0x5efc
Faulting application start time: 0x01da3b41675a5286
Faulting application path: C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 370a4eba-4e36-4ef3-b02e-6c465bf30d17
Faulting package full name: 
Faulting package-relative application ID: 

OS is Windows 10 Enterprise

**Comment by Riscon** [comment]
I'd like to second that. I tried reinstalling. It seems that it broke during the december update 2023.

Name der fehlerhaften Anwendung: mRemoteNG.exe, Version: 1.76.20.24615, Zeitstempel: 0x5cb09552
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.22621.2861, Zeitstempel: 0x9e57f18c
Ausnahmecode: 0xe0434352
Fehleroffset: 0x00149392
ID des fehlerhaften Prozesses: 0x0x5C90
Startzeit der fehlerhaften Anwendung: 0x0x1DA3B464F67EEE3
Pfad der fehlerhaften Anwendung: C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe
Pfad des fehlerhaften Moduls: C:\Windows\System32\KERNELBASE.dll
Berichtskennung: 07d36144-c4ef-477a-88d2-4f9233afc3e2
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 

I am running Windows 11 Version 23H2 (22631.2861). Obviously it's in german.

**Comment by cemilf** [comment]
PreRelease Version 1.77.1.27713 also crashing at startup.

Os Version: Windows 11 - 23H2 (22631.2861)

```
Exception Message
"An item with the same key has already been added."

Stack trace
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at mRemoteNG.App.Update.UpdateFile.FromString(String content)
   at mRemoteNG.App.Update.UpdateFile..ctor(String content)
   at mRemoteNG.App.Update.UpdateInfo.FromString(String input)
   at mRemoteNG.App.Update.AppUpdater.GetUpdateInfo()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Environment
OS: Microsoft Windows NT 10.0.22631.0
mRemoteNG Version: 1.77.1.27713
Edition: Portable
Cmd line args: 

```

**Comment by simonai1254** [comment]
Have you tried disabling the  update checks on startup"? Looks like the current website rebuild messes with the checker (did not investigate further yet)

See #2541 and related on how to change the setting

**Comment by golfperson** [comment]
> Have you tried disabling the update checks on startup"? Looks like the current website rebuild messes with the checker (did not investigate further yet)
> 
> See #2541 and related on how to change the setting

This fixed the issue for me, thanks!

The app was locking up before I could even open the options, so I created a hosts file entry for mremoteng.com pointing to 0.0.0.0 which also stopped the crashing. That allowed me to turn off the updates check, and then delete the host file entry.

Edit: I should have clicked your link... didn't realize you could disable it outside of the GUI :)

**Comment by Riscon** [comment]
> Have you tried disabling the update checks on startup"? Looks like the current website rebuild messes with the checker (did not investigate further yet)
> 
> See #2541 and related on how to change the setting

Thanks! I've used the instructions to disable the update checks on startup following this post: https://github.com/mRemoteNG/mRemoteNG/issues/2541#issuecomment-1872527525

**Comment by rsford31** [comment]
> Have you tried disabling the update checks on startup"? Looks like the current website rebuild messes with the checker (did not investigate further yet)
> 
> See #2541 and related on how to change the setting

That did it for me! I disabled my connection, launched mRemoteNG without issues. While I had it opened I unchecked that option, reconnected, shut down mRemoteNG and launched again with no issues.
