### ISSUE TITLE
mRemoteNG with SQLDB to share connections

### ISSUE THREAD

**Issue by Weben-is-me** [mRemoteNG/mRemoteNG#2579]
I've just deployed mRemoteNG in a Windows Servers 2016 and I'd like to set SQL as DB to store more than 1000 connections and share them in a team. I've followed the instructions:
    https://github.com/mRemoteNG/mRemoteNG/blob/v1.77.3-dev/mRemoteNGDocumentation/sql_configuration.rst

and deployed the db with the following script:
    https://github.com/mRemoteNG/mRemoteNG/blob/develop/mRemoteNGDocumentation/mssql_db_setup.sql

I'm able to connect to the database I create a connection but when putting the hostname at the Config tab the following error is showed:

----------
ErrorMsg
04/10/2024 17:13:02
Couldn't save connections file as ""!
Column 'InheritExternalCredentialProvider' does not belong to table .
----------

If I close the application and reopen it it shows the following error after reconnecting ti the DB:
   at System.Data.DataRow.GetDataColumn(String columnName)
   at System.Data.DataRow.get_Item(String columnName)
   at mRemoteNG.Config.Serializers.ConnectionSerializers.MsSql.DataTableDeserializer.PopulateConnectionInfoFromDatarow(DataRow dataRow, ConnectionInfo connectionInfo)
   at mRemoteNG.Config.Serializers.ConnectionSerializers.MsSql.DataTableDeserializer.DeserializeConnectionInfo(DataRow row)
   at mRemoteNG.Config.Serializers.ConnectionSerializers.MsSql.DataTableDeserializer.CreateNodesFromTable(DataTable table)
   at mRemoteNG.Config.Serializers.ConnectionSerializers.MsSql.DataTableDeserializer.Deserialize(DataTable table)
   at mRemoteNG.Config.Connections.SqlConnectionsLoader.Load()
   at mRemoteNG.Connection.ConnectionsService.LoadConnections(Boolean useDatabase, Boolean import, String connectionFileName)
   at mRemoteNG.UI.Forms.OptionsPages.SqlServerPage.ReinitializeSqlUpdater()
   at mRemoteNG.UI.Forms.OptionsPages.SqlServerPage.SaveSettings()
   at mRemoteNG.UI.Forms.FrmOptions.SaveOptions()
   at mRemoteNG.UI.Forms.FrmOptions.BtnOK_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

Environment
* Version used: 1.77.3 
* Operating System and version (e.g. Windows 10 1709 x64): Windows Server 2016 / 2022 - SQL Server 2012

Question
Is the SQL script used the correct one to the application version (1.77.3 )?
I've tried with the 3 available versions for downloading 1.76.20.24615 / 1.77.1.27654 / 1.77.3.nb-1784, and get different errors: 

1.76.20.24615 & 1.77.1.27654
----------
ErrorMsg
04/10/2024 17:24:01
Couldn't save connections file as ""!
The given ColumnMapping does not match up with any column in the source or destination.
----------

Thanks for any help!

**Comment by maxXx1** [comment]
I have same problem.

**Stable v1.76.20**

```plaintext
----------
ErrorMsg
01/30/2025 17:09:13
Failed to save join list file ""!
The specified ColumnMapping object does not match any column in the source or target.
----------
```

**Preview v1.77.1**

```plaintext
----------
ErrorMsg
01/30/2025 17:05:27
Metod VerifyDatabaseVersion (Config.Connections.Save) failed. Column names in each table must be unique. Column name 'RedirectClipboard' in table 'tblCons' is specified more than once.
----------
```

**Nightly v1.77.3.1784-NB**

cant connect to DB

**Comment by robertpopa22** [comment]
Triage refresh (P2): this issue has been inactive for a long time. Please retest on the latest build and share reproducible steps, expected vs actual behavior, and logs/screenshots. If there is no confirmation/update, maintainers can close it as stale or not reproducible.

**Comment by robertpopa22** [comment]
**Fix available for testing**

**Commit:** `6c110776` (fork `robertpopa22/mRemoteNG`, branch `main`)
**What changed:** mRemoteNG with SQLDB to share connections

A beta build (v1.81.0-beta.4) including this fix is available from the fork's Releases page.

---

> *We sincerely appreciate the mRemoteNG maintainers and the wonderful community that has kept this project alive and thriving for over a decade. Your work powers thousands of IT professionals worldwide, including us. Our fork builds entirely on your foundation — we're preparing a consolidated Pull Request to contribute these improvements back to the official project. Thank you for everything you've built.*
>
> *— robertpopa22, community contributor*
