### ISSUE TITLE
[dotnet-sdk-9.0.100-preview.6.24325.8] mRemote launch failed with an exception : PlatformNotSupportedException: BinaryFormatter serialization and deserialization have been removed.

### ISSUE THREAD

**Issue by Junjun-zhao** [mRemoteNG/mRemoteNG#2616]
We are doing Application compatibility testing with this application against the latest .NET 9 SDK. When run this application with the latest .NET 9 build "dotnet-sdk-9.0.100-preview.6.24325.8", it failed to launch with error:
```"The type initializer for 'BrightIdeasSoftware.ObjectListView' threw an exception." ```After debugging, we found this exception is caused by ```"PlatformNotSupportedException: BinaryFormatter serialization and deserialization have been removed."```.  

After the investigation, it is related to [Epic- Update BinaryFormatter usage](https://github.com/dotnet/winforms/issues/6267) and this is the [Official BinaryFormatter removal announcement](https://github.com/dotnet/runtime/issues/98245) for your reference.  The suggestion from team is that BrightIdeasSoftware.ObjectListView will need to be updated to use a different form of serialization or add a typeconverter. And a workaround with the [System.Runtime.Serialization.Formatters](https://www.nuget.org/packages/System.Runtime.Serialization.Formatters/9.0.0-preview.6.24327.7) nuget package was provided if needed and accept the security risk concern.

Please refer to more information from https://github.com/dotnet/winforms/issues/11599.

## Expected Behavior

Launch mRemoteNG.exe successfully

## Current Behavior

Launch failed with error:
![image](https://github.com/user-attachments/assets/c2619946-0506-41f2-9f6f-442e4711ca42)
```
The type initializer for 'BrightIdeasSoftware.ObjectListView' threw an exception.
StackTrace:
at BrightIdeasSoftware.ObjectListView.get_IsVistaOrLater()
   at BrightIdeasSoftware.VirtualObjectListView.get_ShowGroups()
   at BrightIdeasSoftware.VirtualObjectListView.BuildList(Boolean shouldPreserveSelection)
   at BrightIdeasSoftware.VirtualObjectListView.set_VirtualListDataSource(IVirtualListDataSource value)
   at BrightIdeasSoftware.VirtualObjectListView..ctor()
   at BrightIdeasSoftware.TreeListView..ctor()
   at mRemoteNG.UI.Controls.ConnectionTree.ConnectionTree..ctor() in C:\Source\mRemoteNG\mRemoteNG\UI\Controls\ConnectionTree\ConnectionTree.cs:line 69
   at mRemoteNG.UI.Window.ConnectionTreeWindow.InitializeComponent() in C:\Source\mRemoteNG\mRemoteNG\UI\Window\ConnectionTreeWindow.Designer.cs:line 24
   at mRemoteNG.UI.Window.ConnectionTreeWindow..ctor(DockContent panel) in C:\Source\mRemoteNG\mRemoteNG\UI\Window\ConnectionTreeWindow.cs:line 45
   at mRemoteNG.UI.Window.ConnectionTreeWindow..ctor() in C:\Source\mRemoteNG\mRemoteNG\UI\Window\ConnectionTreeWindow.cs:line 36
   at mRemoteNG.App.Windows.get_TreeForm() in C:\Source\mRemoteNG\mRemoteNG\App\Windows.cs:line 23
   at mRemoteNG.UI.Forms.FrmMain.SetMenuDependencies() in C:\Source\mRemoteNG\mRemoteNG\UI\Forms\frmMain.cs:line 289
   at mRemoteNG.UI.Forms.FrmMain.FrmMain_Load(Object sender, EventArgs e) in C:\Source\mRemoteNG\mRemoteNG\UI\Forms\frmMain.cs:line 171
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean ignoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at mRemoteNG.UI.Forms.FrmMain.WndProc(Message& m) in C:\Source\mRemoteNG\mRemoteNG\UI\Forms\frmMain.cs:line 598
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

## Steps to Reproduce (for bugs)

1. Change the runtime.config file to let the app run against with dotnet-sdk-9.0.100-preview.6.24325.8.
```
 "frameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "9.0.0-preview.6.24321.8"
      },
      {
        "name": "Microsoft.WindowsDesktop.App",
        "version": "9.0.0-preview.6.24322.3"
      }
    ],
```
2. Turn on EnableUnsafeBinaryFormatterSerialization switch in runtime.config file:
```
"configProperties": {
      "System.Reflection.Metadata.MetadataUpdater.IsSupported": false,
      "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization": true
    }
```
3. Launch mRemoteNG.exe

## Your Environment

Application Name: mRemoteNG(WinForms)
OS： Windows 10 21H2
CPU: X64
.NET Build Number: dotnet-sdk-9.0.100-preview.6.24325.8
Github Link: https://github.com/mRemoteNG/mRemoteNG

**Comment by Kvarkas** [comment]
Hello, current version support officially only .net 6, migration to newest version occurs in next release. However thanks for information I will review it and will see if we could do something about it before migration.

**Comment by Kvarkas** [comment]
not relevant
