### ISSUE TITLE
Creating Databases fails while using SQL server

### ISSUE THREAD

**Issue by TechnVision** [mRemoteNG/mRemoteNG#2649]
Hello there, I don't know if this is already resolved but I'm not able to use SQL server database to store all connections, i've followed all steps mentioned in [This URL](https://github.com/mRemoteNG/mRemoteNG/blob/v1.77.3-dev/mRemoteNGDocumentation/sql_configuration.rst), it threw me an error for able to find database on the server, when I created the database it throws 

``ErrorMsg
10/29/2024 15:50:27
Retrieving database version failed. System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'tblRoot'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader()
   at mRemoteNG.Config.Serializers.MsSql.SqlDatabaseMetaDataRetriever.GetDatabaseMetaData(SqlDatabaseConnector sqlDatabaseConnector) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\MsSql\SqlDatabaseMetaDataRetriever.cs:line 26
ClientConnectionId:aa7b9388-82e0-46d8-8033-38a3ac3a0e30
Error Number:208,State:1,Class:16``

**Comment by TechnVision** [comment]
[SQLScript.txt](https://github.com/user-attachments/files/17622936/SQLScript.txt)

found this file in installation directory
