### ISSUE TITLE
 Index was out of range

### ISSUE THREAD

**Issue by infectormp** [mRemoteNG/mRemoteNG#299]
In empty Connection tree (new installation) create new folder and immediate delete created folder, you get:

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Collections.ArrayList.get_Item(Int32 index)
   at System.Collections.ArrayList.IListWrapper.get_Item(Int32 index)
   at BrightIdeasSoftware.TreeListView.Tree.RebuildObjectMap(Int32 startIndex)
   at BrightIdeasSoftware.TreeListView.Tree.RebuildChildren(Object model)
   at BrightIdeasSoftware.TreeListView.RefreshObjects(IList modelObjects)
   at mRemoteNG.UI.Window.ConnectionTreeWindow.RefreshTreeObjects(IList modelObjects)
   at mRemoteNG.UI.Window.ConnectionTreeWindow.HandleCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at mRemoteNG.Tree.ConnectionTreeModel.RaiseCollectionChangedEvent(Object sender, NotifyCollectionChangedEventArgs args)
   at mRemoteNG.Container.ContainerInfo.RaiseCollectionChangedEvent(Object sender, NotifyCollectionChangedEventArgs args)
   at mRemoteNG.Container.ContainerInfo.RemoveChild(ConnectionInfo removalTarget)
   at mRemoteNG.Connection.ConnectionInfo.RemoveParent()
   at mRemoteNG.Tree.ConnectionTreeModel.DeleteNode(ConnectionInfo connectionInfo)
   at mRemoteNG.UI.Window.ConnectionTreeWindow.DeleteSelectedNode()
   at mRemoteNG.UI.Window.ConnectionTreeWindow.<SetContextMenuEventHandlers>b__33_11(Object sender, EventArgs args)
   at mRemoteNG.UI.Controls.ConnectionContextMenu.OnDeleteClicked(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75 beta 3  |

**Comment by kmscode** [comment]
Reference: https://sourceforge.net/p/objectlistview/bugs/108/

Some bugs in the upstream code that could cause a nearly identical problem... However, those were resolved a few releases ago...

**Comment by sparerd** [comment]
Looks like there are some oddities that slipped by our testing. I'll take this as a task to create more tests around the connection tree

**Comment by sparerd** [comment]
Working on this now

**Comment by sparerd** [comment]
Resolved deletion issue in commit `1e213df`

There are a few other small bugs that are related to this one that I would like to fix under this ticket. Keep this open for now.

**Comment by sparerd** [comment]
Resolved a few other small bugs related to this and move a lot of code out to their own classes to make testing easier.

**Comment by sparerd** [comment]
This fix will be available in the next pre-release.
