### ISSUE TITLE
Error when clicking in Search bar

### ISSUE THREAD

**Issue by nqnguyen2** [mRemoteNG/mRemoteNG#422]
Just downloaded 1.75 Final .msi
When clicking in the Search bar field, the error in screenshot appeared.
Attached error log

[errorlog.zip](https://github.com/mRemoteNG/mRemoteNG/files/812397/errorlog.zip)

![image](https://cloud.githubusercontent.com/assets/23535412/23487460/840cdf32-fea3-11e6-9af6-44dbf5f9f709.png)

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at mRemoteNG.UI.Controls.ConnectionTree.OnMouse_SingleClick(Object sender, MouseEventArgs mouseEventArgs)
   at System.Windows.Forms.Control.OnMouseClick(MouseEventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at BrightIdeasSoftware.ObjectListView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 Final |

**Comment by sparerd** [comment]
Fix will be available in the next release. Cant believe I never encountered this error over months of testing : \

**Comment by Eldaw** [comment]
@sparerd Any chance you could re-release v1.75 with the fix? Rather than waiting months for v1.76.

**Comment by sparerd** [comment]
Yea, we may end up doing that. This one is annoying, but the app will continue working without issue by clicking 'continue'. We'll wait a few days to ensure we didnt miss any other bugs.

**Comment by kmscode** [comment]
@sparerd Agreed. This one is annoying and we should get a quick fix out. I have some ideas on how to make some minimal changes to our release pipeline to make it easier for us to issue small updates like this.

**Comment by sparerd** [comment]
@kmscode 👍 that would be great
