### ISSUE TITLE
Exception when duplicating connection

### ISSUE THREAD

**Issue by BHB3805** [mRemoteNG/mRemoteNG#467]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.AmbiguousMatchException: Ambiguous match found.
   at System.RuntimeType.GetPropertyImpl(String name, BindingFlags bindingAttr, Binder binder, Type returnType, Type[] types, ParameterModifier[] modifiers)
   at System.Type.GetProperty(String name)
   at mRemoteNG.Connection.ConnectionInfo.GetInheritedPropertyValue[TPropertyType](String propertyName)
   at mRemoteNG.Connection.ConnectionInfo.GetPropertyValue[TPropertyType](String propertyName, TPropertyType value)
   at mRemoteNG.Connection.AbstractConnectionInfoData.get_Password()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at mRemoteNG.Connection.ConnectionInfo.GetInheritedPropertyValue[TPropertyType](String propertyName)
   at mRemoteNG.Connection.ConnectionInfo.GetPropertyValue[TPropertyType](String propertyName, TPropertyType value)
   at mRemoteNG.Connection.AbstractConnectionInfoData.get_Password()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at mRemoteNG.Connection.ConnectionInfo.GetInheritedPropertyValue[TPropertyType](String propertyName)
   at mRemoteNG.Connection.ConnectionInfo.GetPropertyValue[TPropertyType](String propertyName, TPropertyType value)
   at mRemoteNG.Connection.AbstractConnectionInfoData.get_Password()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at mRemoteNG.Connection.ConnectionInfo.CopyFrom(ConnectionInfo sourceConnectionInfo)
   at mRemoteNG.Connection.ConnectionInfo.Clone()
   at mRemoteNG.UI.Controls.ConnectionTree.DuplicateSelectedNode()
   at mRemoteNG.UI.Controls.ConnectionContextMenu.OnDuplicateClicked(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1086.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
mRemoteNG
    Assembly Version: 1.75.7000.19194
    Win32 Version: 1.75.7000.19194
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/mRemoteNG.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1088.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1081.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1078.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
mRemoteNG.resources
    Assembly Version: 1.75.7000.19194
    Win32 Version: 1.75.7000.19194
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/en-US/mRemoteNG.resources.DLL
----------------------------------------
BouncyCastle.Crypto
    Assembly Version: 1.8.1.0
    Win32 Version: 1.8.15362.1
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/BouncyCastle.Crypto.DLL
----------------------------------------
log4net
    Assembly Version: 1.2.15.0
    Win32 Version: 1.2.15.0
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/log4net.DLL
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Assembly Version: 2.9.0.0
    Win32 Version: 2.9.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking.ThemeVS2012Light
    Assembly Version: 2.9.0.0
    Win32 Version: 2.9.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/WeifenLuo.WinFormsUI.Docking.ThemeVS2012Light.DLL
----------------------------------------
MagicLibrary
    Assembly Version: 1.7.4.0
    Win32 Version: 1.7.4.0
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/MagicLibrary.DLL
----------------------------------------
ObjectListView
    Assembly Version: 2.9.1.1072
    Win32 Version: 2.9.1.0
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/ObjectListView.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1088.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Geckofx-Core
    Assembly Version: 45.0.22.0
    Win32 Version: 45.0.22.0
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/Geckofx-Core.DLL
----------------------------------------
Geckofx-Winforms
    Assembly Version: 45.0.22.0
    Win32 Version: 45.0.22.0
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/Geckofx-Winforms.DLL
----------------------------------------
Microsoft.mshtml
    Assembly Version: 7.0.3300.0
    Win32 Version: 7.0.3300.0
    CodeBase: file:///C:/Windows/assembly/GAC/Microsoft.mshtml/7.0.3300.0__b03f5f7f11d50a3a/Microsoft.mshtml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

|||
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 aplha 3  |

**Comment by kmscode** [comment]
@BHB3805 Could you provide some more details? What type of connection are you attempting to duplicate? Does it only happen on that connection type, or all connection types?

**Comment by jmbabcock2017** [comment]
Happens to me also. Running on Windows 2012 R2 server. To note, only happens if inheritance of username/password are selected, if left at default (no inheritance) it works fine.

**Comment by kmscode** [comment]
@jmbabcock2017 Thanks for the details. I was unable to reproduce. Could you provide your stack trace? 
Please also attach the [mRemoteNG.log](https://github.com/mRemoteNG/mRemoteNG/wiki/Troubleshooting-and-Logging)

**Comment by selthofer** [comment]
same here, on windows 10 with latest mRemoteNG release.

However there are two different issues here:
- App exception when selecting DUplciate action
- App crash when Quiting app with open connections



App crashes like this only under following conditions:
- start mRemoteNG
- select existing session and right-click and select Duplicate
- application shows exception as shown here in teh screenshot (this is the first issue for which log snippet is shown below)

![image](https://cloud.githubusercontent.com/assets/19431072/25767970/ae1344c0-3241-11e7-8d0b-8bb355cef65c.png)

Only this in the mremoteNG.log file (action was start, select existing session title, right-click and select Duplicate and it throws an exception as above with the same output as in the openning post above):

2017-05-06 09:39:18,584 [1] INFO - mRemoteNG 1.75.7005.28220 starting.
2017-05-06 09:39:18,600 [1] INFO - Command Line: System.String[]
2017-05-06 09:39:19,701 [1] INFO - Microsoft Windows 10 Pro  64-bit
2017-05-06 09:39:19,701 [1] INFO - Microsoft .NET CLR 4.0.30319.42000
2017-05-06 09:39:19,701 [1] INFO - System Culture: en-GB/English (United Kingdom)
2017-05-06 09:39:19,701 [1] INFO - Checking FIPS Policy...
2017-05-06 09:39:19,701 [1] INFO - Checking Lenovo AutoScroll Utility...
2017-05-06 09:39:20,483 [1] INFO - Loading External Apps from: C:\Users\selth\AppData\Roaming\mRemoteNG\extApps.xml
2017-05-06 09:39:20,864 [1] WARN - PuttySessions.Watcher.StartWatching() failed.
Not found 
2017-05-06 09:39:20,864 [1] WARN - XmingPortablePuttySessions.Watcher.StartWatching() failed.
The directory name sessions is invalid.

- now, you have options to Continue and Quit.
- If you any of those Continue or Quit then app either stays up and running or it quits. No problem there.
- However, if you did start your connections before selecting duplicate and then right-click and select Duplicate action and after app exception is thrown you select Quit, then there is a window asking to Close all your connections.
<img width="346" alt="2017-05-06 09_54_10-mremoteng - confcons xml - 10 0 0 40 - dc" src="https://cloud.githubusercontent.com/assets/19431072/25768021/6d57ba3c-3242-11e7-97e2-a57e87749980.png">

- if you choose Yes here then application crashes in windows:

![image](https://cloud.githubusercontent.com/assets/19431072/25768001/36ddc0e6-3242-11e7-85bb-c11efb6cb371.png)


here is crash file but as mentioned above this is just a direct consequence of the Duplicate action for which app shows an exception andonly if you want to Quit and select to close all open connections as described above. 

[AppCrash_mRemoteNG.exe_2dba8f4cbb9774ebf651ee285c1943839efcb_a6930fa6_cab_2bf05a05.zip](https://github.com/mRemoteNG/mRemoteNG/files/980553/AppCrash_mRemoteNG.exe_2dba8f4cbb9774ebf651ee285c1943839efcb_a6930fa6_cab_2bf05a05.zip)

this is just one more (previous) crash for the same action as described above:

[AppCrash_mRemoteNG.exe_2dba8f4cbb9774ebf651ee285c1943839efcb_a6930fa6_08c4efcb.zip](https://github.com/mRemoteNG/mRemoteNG/files/980550/AppCrash_mRemoteNG.exe_2dba8f4cbb9774ebf651ee285c1943839efcb_a6930fa6_08c4efcb.zip)


Therefore, we need the solution for both issues to resolve:
- Duplicate action which is not working either way
- to avoid crash after selecting quit and choosing to close all conections (but this one is not going to be the problem when first issue is resolved since there is no real issue if you start RDP session and then click X to exit the app, it will also ask you to close all sessions and if you choose yes then all good, app will close the sessions and exit).

**Comment by kmscode** [comment]
@selthofer thanks for all the details. Will look into this one further in a few weeks (semi-off grid) unless @spared gets to it first. Should be no problem to get into hf6.
