### ISSUE TITLE
Horizontal scroll bar missing on connections pane

### ISSUE THREAD

**Issue by madmada17** [mRemoteNG/mRemoteNG#501]
The horizontal scroll bar is gone at the bottom of the connections pane.  Was there with version <= 1.74.  If there are many sub-folders and long connection names, they are truncated on the right with "..." and there is no way to scroll over to view the full name any longer.  Perhaps this is the expected behavior with the new Connect Tree object in 1.75 however it is rather frustrating.  It's not an issue if the connections pane isn't pinned as you can expand the pane as wide as necessary over the sessions to view the full names, but if it's pinned, you can't resize without forcing the RDP session to resize/refresh as well.

|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7003.25226  |

**Comment by sparerd** [comment]
resolved this - it will be available in 1.76

**Comment by dekelMP** [comment]
It seemed to create cross-thread error. Should it be in the ExecutePostSetupActions ?

System.InvalidOperationException occurred
HResult=0x80131509
Message=Cross-thread operation not valid: Control 'olvConnections' accessed from a thread other than the thread it was created on.
Source=System.Windows.Forms
StackTrace:
at System.Windows.Forms.Control.get_Handle()
at System.Windows.Forms.Control.SendMessage(Int32 msg, Int32 wparam, IntPtr lparam)
at System.Windows.Forms.ListView.SetColumnWidth(Int32 columnIndex, ColumnHeaderAutoResizeStyle headerAutoResize)
at System.Windows.Forms.ListView.AutoResizeColumn(Int32 columnIndex, ColumnHeaderAutoResizeStyle headerAutoResize)
at System.Windows.Forms.ColumnHeader.AutoResize(ColumnHeaderAutoResizeStyle headerAutoResize)
at mRemoteNG.UI.Controls.ConnectionTree.ResizeColumns() in C:\PublicGitHub\mRemoteNG\mRemoteV1\UI\Controls\ConnectionTree\ConnectionTree.cs:line 328
at mRemoteNG.UI.Controls.ConnectionTree.PopulateTreeView() in C:\PublicGitHub\mRemoteNG\mRemoteV1\UI\Controls\ConnectionTree\ConnectionTree.cs:line 127
at mRemoteNG.UI.Controls.ConnectionTree.set_ConnectionTreeModel(ConnectionTreeModel value) in C:\PublicGitHub\mRemoteNG\mRemoteV1\UI\Controls\ConnectionTree\ConnectionTree.cs:line 46
at mRemoteNG.Connection.ConnectionsService.set_ConnectionTreeModel(ConnectionTreeModel value) in C:\PublicGitHub\mRemoteNG\mRemoteV1\Connection\ConnectionsService.cs:line 20
at mRemoteNG.Config.Connections.Multiuser.RemoteConnectionsSyncronizer.Load() in C:\PublicGitHub\mRemoteNG\mRemoteV1\Config\Connections\Multiuser\RemoteConnectionsSyncronizer.cs:line 40
at mRemoteNG.Config.Connections.Multiuser.RemoteConnectionsSyncronizer.Load(Object sender, ConnectionsUpdateAvailableEventArgs args) in C:\PublicGitHub\mRemoteNG\mRemoteV1\Config\Connections\Multiuser\RemoteConnectionsSyncronizer.cs:line 45
at mRemoteNG.Config.Connections.Multiuser.RemoteConnectionsSyncronizer.<SetEventListeners>b7_0(Object sender, ConnectionsUpdateAvailableEventArgs args) in C:\PublicGitHub\mRemoteNG\mRemoteV1\Config\Connections\Multiuser\RemoteConnectionsSyncronizer.cs:line 33
at mRemoteNG.Config.Connections.SqlConnectionsUpdateChecker.RaiseConnectionsUpdateAvailableEvent() in C:\PublicGitHub\mRemoteNG\mRemoteV1\Config\Connections\Multiuser\SqlConnectionsUpdateChecker.cs:line 107
at mRemoteNG.Config.Connections.SqlConnectionsUpdateChecker.IsUpdateAvailable() in C:\PublicGitHub\mRemoteNG\mRemoteV1\Config\Connections\Multiuser\SqlConnectionsUpdateChecker.cs:line 34
at mRemoteNG.Config.Connections.SqlConnectionsUpdateChecker.<IsUpdateAvailableAsync>b6_0() in C:\PublicGitHub\mRemoteNG\mRemoteV1\Config\Connections\Multiuser\SqlConnectionsUpdateChecker.cs:line 41
at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ThreadHelper.ThreadStart()

**Comment by sparerd** [comment]
This fix was moved up and is available as of v1.75.7009
