### ISSUE TITLE
Exception when Importing File

### ISSUE THREAD

**Issue by jdix531** [mRemoteNG/mRemoteNG#518]
For windows installer version: "mRemoteNG-Installer-1.75.7003.25190"

You get an unhandled exception when doing an 'Import from file' in the connections pane (rt click, import, import from file...) and nothing is selected (you can click any white space in this menu to have this effect).

I believe the behavior should be to either inform the user to select a location for the file import or to use the top level as a default. The top level as a default should suffice since the import comes in separate sub folder anyways.

I have not checked but I imagine the other import options under the import menu also throw an exception when there is no top-level selection made.

Thanks, Josh

**Comment by kmscode** [comment]
```************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at mRemoteNG.UI.Controls.ConnectionContextMenu.OnImportFileClicked(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
