### ISSUE TITLE
Crashing every time I start it on windows 10

### ISSUE THREAD

**Issue by joao-garcia** [mRemoteNG/mRemoteNG#645]
Exception from event viewer

Application: mRemoteNG.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Xml.XmlException
   at System.Xml.XmlTextReaderImpl.Throw(System.Exception)
   at System.Xml.XmlTextReaderImpl.Throw(System.String, System.String[])
   at System.Xml.XmlTextReaderImpl.ParseText(Int32 ByRef, Int32 ByRef, Int32 ByRef)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlTextReaderImpl.Skip()
   at System.Xml.XmlTextReader.Skip()
   at System.Configuration.XmlUtil.StrictSkipToNextElement(System.Configuration.ExceptionAction)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   at System.Configuration.BaseConfigurationRecord.ScanSections(System.Configuration.XmlUtil)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(System.Configuration.ConfigurationSchemaErrors)
   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs)

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs)
   at System.Configuration.Internal.InternalConfigRoot.OnConfigRemoved(System.Configuration.Internal.InternalConfigEventArgs)
   at System.Configuration.Internal.InternalConfigRoot.RemoveConfigImpl(System.String, System.Configuration.BaseConfigurationRecord)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(System.String, Boolean, Boolean, Boolean, Boolean, System.Object ByRef, System.Object ByRef)
   at System.Configuration.BaseConfigurationRecord.GetSection(System.String)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(System.String)
   at System.Configuration.ConfigurationManager.GetSection(System.String)
   at System.Configuration.ClientSettingsStore.ReadSettings(System.String, Boolean)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(System.Configuration.SettingsContext, System.Configuration.SettingsPropertyCollection)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(System.Configuration.SettingsProvider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(System.String)
   at System.Configuration.SettingsBase.get_Item(System.String)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(System.String)
   at System.Configuration.ApplicationSettingsBase.get_Item(System.String)
   at mRemoteNG.Settings.get_SingleInstance()
   at mRemoteNG.App.ProgramRoot.Main(System.String[])

**Comment by kmscode** [comment]
Please see the [troubleshooting and logging](https://github.com/mRemoteNG/mRemoteNG/wiki/Troubleshooting-and-Logging) page.

Try deleting the user.config, if that doesn't help, provide the information as noted.

**Comment by joao-garcia** [comment]
Hi, thanks for the reply.

I deleted the user config, but after that it keeps asking for a passwd..

Best Regards,
João

**Comment by kmscode** [comment]
When are you prompted for the password? When opening mRemoteNG or when attempting to connect to a host? 

@sparerd Any thoughts on this?

**Comment by joao-garcia** [comment]
It happens why I open mRemoteNG

**Comment by sparerd** [comment]
- What is the version of mRemoteNG?

- What is the ConfVersion of your connections file? You can check this by opening your confCons.xml file in a text editor. It will look something like this:
```xml
<Connections Name="Connections" Export="False" EncryptionEngine="AES" BlockCipherMode="GCM" KdfIterations="1000" FullFileEncryption="False" Protected="rJGzXAzCwYztIx7xWO22AemSd8HPLAROXRpE75rsDcXR3muGzWULMQq/0YQZJs+gpz9IRTVBOyZB481GUVxM/ACy" ConfVersion="2.6">
```

**Comment by joao-garcia** [comment]
mRemoteNG version is 1.75.7008.17907

my connections file is all filled with null (empty at first sight but when opened with notepad++, it shows NULL NULL NULL …)
hence the startup error loading the configuration file.

But checking an older backup version with a few days, it shows 2.5

**Comment by kmscode** [comment]
Sounds like you need to restore your conCons.xml from the last good backup and then restart mRemoteNG. Let us know if that allows it to start successfully.

Do you know if you had any system crashes? A system crash/blue screen is the only thing that can think of that would likely corrupt both of these files. Unless you have other (very bad) disk issues...

**Comment by joao-garcia** [comment]
Yes, that works, but I have most of the backups corrupted with this null thing. So, the only one that works is empty.
The last time this happened it was the same thing.

Suddenly the program starts crashing, I need to clean the corrupted connection files and add everything again.

I don’t have any system crashes.
Also, I find it strange that’s disk issues, because these are the only files being corrupted (that I know of)

But if no one else is complaining, it might be something with my pc.

**Comment by kmscode** [comment]
@joao-garcia The zeroing out or corruption of files will likely be resolved when we write/save the configs on change: #340
