### ISSUE TITLE
mRemoteNG.exe throwing 0xe0434352 error code.

### ISSUE THREAD

**Issue by mxplusb** [mRemoteNG/mRemoteNG#707]
|||
|--:|---|
|Operating system | Windows 10 x64 build 16278.1000 |
|mRemoteNG version| 1.74.6023.15437 |

I get these errors when I try to start the application. They are from the WEL.

Application Error:
```
Faulting application name: mRemoteNG.exe, version: 1.74.6023.15437, time stamp: 0x57728afa
Faulting module name: KERNELBASE.dll, version: 10.0.16278.1000, time stamp: 0xc3175b1c
Exception code: 0xe0434352
Fault offset: 0x00100212
Faulting process id: 0x67f0
Faulting application start time: 0x01d329e08515ef48
Faulting application path: C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 91c08ae2-4d15-42b8-be71-c8e528c69b64
Faulting package full name: 
Faulting package-relative application ID: 
```

.NET Runtime:
```
Application: mRemoteNG.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Xml.XmlException
   at System.Xml.XmlTextReaderImpl.Throw(System.Exception)
   at System.Xml.XmlTextReaderImpl.Throw(System.String, System.String[])
   at System.Xml.XmlTextReaderImpl.ParseText(Int32 ByRef, Int32 ByRef, Int32 ByRef)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlTextReaderImpl.Skip()
   at System.Xml.XmlTextReader.Skip()
   at System.Configuration.XmlUtil.StrictSkipToNextElement(System.Configuration.ExceptionAction)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   at System.Configuration.BaseConfigurationRecord.ScanSections(System.Configuration.XmlUtil)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(System.Configuration.ConfigurationSchemaErrors)
   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs)

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs)
   at System.Configuration.Internal.InternalConfigRoot.OnConfigRemoved(System.Configuration.Internal.InternalConfigEventArgs)
   at System.Configuration.Internal.InternalConfigRoot.RemoveConfigImpl(System.String, System.Configuration.BaseConfigurationRecord)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(System.String, Boolean, Boolean, Boolean, Boolean, System.Object ByRef, System.Object ByRef)
   at System.Configuration.BaseConfigurationRecord.GetSection(System.String)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(System.String)
   at System.Configuration.ConfigurationManager.GetSection(System.String)
   at System.Configuration.ClientSettingsStore.ReadSettings(System.String, Boolean)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(System.Configuration.SettingsContext, System.Configuration.SettingsPropertyCollection)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(System.Configuration.SettingsProvider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(System.String)
   at System.Configuration.SettingsBase.get_Item(System.String)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(System.String)
   at System.Configuration.ApplicationSettingsBase.get_Item(System.String)
   at mRemoteNG.Settings.get_SingleInstance()
   at mRemoteNG.App.ProgramRoot.Main(System.String[])
```

**Comment by kmscode** [comment]
Looks similar to #645 are you sure your confCons.xml didn't get corrupted? Try restoring from one of the backups...

Also, once you're back up and running, you'll likely want to upgrade to the latest release:
https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.75Hotfix8

This is much newer than what you are currently running.

**Comment by mxplusb** [comment]
This was almost a year ago, I've long since moved past whatever was causing this so I'm more than happy to say it was some environmental/bad config issue. :)
