### ISSUE TITLE
Jenkins build exception

### ISSUE THREAD

**Issue by kmscode** [mRemoteNG/mRemoteNG#723]
````
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at mRemoteNG.App.Runtime.get_ConnectionTreeModel() in C:\jenkins\workspace\mRemoteNG_mRemoteNG_Patch9-PAQCO6O3GLLFFYVSZ3RGAU45FXHQII4C7X4OC5YEAK5266K2DB4A\mRemoteV1\App\Runtime.cs:line 45
   at mRemoteNG.App.Runtime.SaveConnections() in C:\jenkins\workspace\mRemoteNG_mRemoteNG_Patch9-PAQCO6O3GLLFFYVSZ3RGAU45FXHQII4C7X4OC5YEAK5266K2DB4A\mRemoteV1\App\Runtime.cs:line 449
   at mRemoteNG.App.Runtime.SaveConnectionsBGd() in C:\jenkins\workspace\mRemoteNG_mRemoteNG_Patch9-PAQCO6O3GLLFFYVSZ3RGAU45FXHQII4C7X4OC5YEAK5266K2DB4A\mRemoteV1\App\Runtime.cs:line 443
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
````

https://jenkins.mremoteng.org/job/mRemoteNG/job/mRemoteNG/job/Patch9/28/

doesn't seem to be causing any problems, but should still be reviewed.

**Comment by sparerd** [comment]
Happening due to test `CanDeleteLastFolderInTheTree()`. It calls `ConnectionTree.DeleteSelectedNode()` which calls `Runtime.SaveConnectionsAsync()` directly.

I don't think this is an issue in production, but we should definitely move the call to save connections somewhere else. My recommendation is to register save-actions on the ConnectionTreeModel rather than hard coding it in the ConnectionTree ui class. This was my initial intention when putting in the ObjectListView but just didn't take the time to implement it correctly.

**Comment by kmscode** [comment]
Closing this one out since we're (hopefully) almost done with the AppVeyor implementation.
